defmodule Mix.Tasks.Bao.Gen do
  @shortdoc "Generates the API modules from a captured OpenAPI specification"

  @moduledoc """
  Writes one module per engine from a specification captured by
  `mix bao.openapi`.

      mix bao.gen                                  # the newest file in priv/openapi
      mix bao.gen --spec priv/openapi/2.6.2.json

  ## What it writes

  One function per operation. Path parameters are arguments, in the order
  the path names them; every body or query field is an option, validated by
  name; `:mount` says where the engine lives. The answer is the server's own
  JSON, untouched: the specification describes the shape of a request far
  better than the shape of a response, and guessing at the second would be
  inventing a contract nobody promised.

  ## Generated next to written by hand

  Every module has a block between two markers. Everything inside it is
  rewritten on every run; everything outside it is never touched. A function
  outside the block that carries `@operation "<operationId>"` covers that
  operation, and the generator leaves it alone.

  So curating an operation — giving it real arguments, decoding what it
  answers, documenting what the specification cannot say — is moving its
  function above the block and editing it there. `ExBao.Transit` is the
  model: its hand-made functions cover what matters most, and the rest of
  the engine is generated underneath.

  A written function whose name a generated one would take is an error,
  not a silent overwrite.

  ## One operationId, several operations

  The specification is supposed to name each operation once, and nearly
  always does. Where one id is shared, the operations are told apart by
  what differs between them:

    * the path, when the paths differ — `jwt-login` names both `login` and
      `cel/login`, which become `login` and `login_cel`, with `@operation`
      `"jwt-login"` and `"jwt-login:cel"`;
    * the method, when they share a path — `generate-root-token` names its
      GET, POST and DELETE, which become `generate_root_token_get` and so
      on, with `@operation` `"generate-root-token:get"`.

  `operations/1` applies that rule, and the coverage test uses it too.

  ## Why the output is committed

  Generated code that only exists at compile time cannot be read in a pull
  request, and cannot be documented. Committed, a new OpenBao release is a
  diff: these functions are new, this option is gone.
  """

  use Mix.Task

  @marker "  # ── generated by `mix bao.gen`"
  @end_marker "  # ── end of generated ──"

  @methods ~w(get post patch delete)

  # {path prefix, module, default mount (nil: not movable), operationId
  # prefix to drop, what it is}. Secrets engines sit at the top level, as
  # `ExBao.Transit` does; auth methods under `ExBao.Auth`.
  @groups [
    {"sys", "ExBao.Sys", nil, "", "The system backend: mounts, policies, leases, seal, audit."},
    {"identity", "ExBao.Identity", nil, "",
     "The identity store: entities, groups, aliases, OIDC."},
    {"cubbyhole", "ExBao.Cubbyhole", nil, "cubbyhole-",
     "The cubbyhole engine: storage private to one token."},
    {"auth/token", "ExBao.Auth.Token", nil, "token-", "The token auth method."},
    {"auth/approle", "ExBao.Auth.AppRole", "approle", "app-role-", nil},
    {"auth/cert", "ExBao.Auth.Cert", "cert", "cert-", "The TLS certificate auth method."},
    {"auth/jwt", "ExBao.Auth.JWT", "jwt", "jwt-", "The JWT/OIDC auth method."},
    {"auth/kerberos", "ExBao.Auth.Kerberos", "kerberos", "kerberos-",
     "The Kerberos auth method."},
    {"auth/kubernetes", "ExBao.Auth.Kubernetes", "kubernetes", "kubernetes-",
     "The Kubernetes auth method."},
    {"auth/ldap", "ExBao.Auth.LDAP", "ldap", "ldap-", "The LDAP auth method."},
    {"auth/radius", "ExBao.Auth.Radius", "radius", "radius-", "The RADIUS auth method."},
    {"auth/userpass", "ExBao.Auth.Userpass", "userpass", "userpass-",
     "The username and password auth method."},
    {"database", "ExBao.Database", "database", "database-",
     "The database secrets engine: dynamic and static credentials."},
    {"kubernetes", "ExBao.Kubernetes", "kubernetes", "kubernetes-",
     "The Kubernetes secrets engine: service account tokens."},
    {"kv", "ExBao.KV.V1", "kv", "kv-",
     "Version 1 of the key/value secrets engine: no versions, no metadata."},
    {"secret", "ExBao.KV", "secret", "kv-",
     "Version 2 of the key/value secrets engine: versioned secrets and their metadata."},
    {"ldap", "ExBao.LDAP", "ldap", "ldap-",
     "The LDAP secrets engine: static, dynamic and library accounts."},
    {"pki", "ExBao.PKI", "pki", "pki-",
     "The PKI secrets engine: certificate authorities, issuing, revocation, ACME."},
    {"rabbitmq", "ExBao.RabbitMQ", "rabbitmq", "rabbit-mq-", "The RabbitMQ secrets engine."},
    {"ssh", "ExBao.SSH", "ssh", "ssh-",
     "The SSH secrets engine: signed certificates and one-time passwords."},
    {"totp", "ExBao.TOTP", "totp", "totp-", "The TOTP secrets engine."},
    {"transit", "ExBao.Transit", "transit", "transit-", nil}
  ]

  # Path parameters that are paths themselves and keep their slashes.
  @slashed ~w(path prefix url_lease_id)

  @impl Mix.Task
  def run(argv) do
    {opts, _rest} = OptionParser.parse!(argv, strict: [spec: :string])
    file = opts[:spec] || newest_spec()
    spec = file |> File.read!() |> Jason.decode!()
    version = get_in(spec, ["info", "version"])

    operations = operations(spec)

    unplaced = Enum.filter(operations, &is_nil(&1.group))

    if unplaced != [] do
      Mix.raise("""
      Operations under a path no group claims — add the engine to @groups:

      #{Enum.map_join(unplaced, "\n", &"  #{&1.method} #{&1.path}")}
      """)
    end

    for {prefix, module, mount, id_prefix, title} <- @groups do
      ops = Enum.filter(operations, &(&1.group == prefix))
      write_module(module, mount, id_prefix, title, ops, spec, version)
    end

    Mix.shell().info(
      "generated from #{file} (OpenBao #{version}, #{length(operations)} operations)"
    )
  end

  defp newest_spec do
    case Path.wildcard("priv/openapi/*.json") do
      [] -> Mix.raise("no specification in priv/openapi; capture one with mix bao.openapi")
      files -> Enum.max_by(files, &(&1 |> Path.basename(".json") |> Version.parse!()), Version)
    end
  end

  # ── reading the specification ─────────────────────────────────────────────

  @doc """
  Every operation in a decoded specification, each with the `:key` its
  `@operation` marker carries.
  """
  def operations(spec) do
    ops =
      for {path, item} <- spec["paths"],
          {method, op} <- item,
          method in @methods do
        operation(path, method, op, item, spec)
      end

    ops
    |> Enum.group_by(& &1.id)
    |> Enum.flat_map(fn
      {_id, [op]} -> [op]
      {_id, shared} -> disambiguate(shared)
    end)
  end

  defp disambiguate(ops) do
    segments = Enum.map(ops, &String.split(&1.path, "/", trim: true))
    common = Enum.reduce(segments, &(&2 -- (&2 -- &1)))

    suffixes =
      if ops |> Enum.uniq_by(& &1.path) |> length() == 1,
        do: Enum.map(ops, & &1.method),
        else:
          Enum.map(
            segments,
            &((&1 -- common) |> Enum.map_join("_", fn s -> String.replace(s, ~r/\W+/, "") end))
          )

    Enum.zip_with(ops, suffixes, fn
      op, "" ->
        op

      op, suffix ->
        %{op | key: "#{op.id}:#{suffix}", suffix: "_" <> String.replace(suffix, "-", "_")}
    end)
  end

  defp operation(path, method, op, item, spec) do
    %{
      key: op["operationId"],
      suffix: "",
      path: path,
      method: method,
      id: op["operationId"],
      group: group(path),
      summary: op["summary"] || op["description"] || item["description"],
      description: item["description"],
      parameters: (item["parameters"] || []) ++ (op["parameters"] || []),
      body: body_schema(op, spec),
      sudo: item["x-vault-sudo"] == true,
      unauthenticated: item["x-vault-unauthenticated"] == true
    }
  end

  defp group(path) do
    Enum.find_value(@groups, fn {prefix, _, _, _, _} ->
      if path == "/" <> prefix or String.starts_with?(path, "/" <> prefix <> "/"), do: prefix
    end)
  end

  defp body_schema(op, spec) do
    case get_in(op, ["requestBody", "content", "application/json", "schema", "$ref"]) do
      nil -> %{"properties" => %{}}
      "#/components/schemas/" <> name -> spec["components"]["schemas"][name]
    end
  end

  # ── writing a module ──────────────────────────────────────────────────────

  @doc """
  What a run would generate from a decoded specification, as it stands on
  disk now: one map per function, with its `:module` and `:name` next to
  the operation it comes from. Operations already covered by hand are not
  in it.

  The same list `run/1` writes, so a test can call every generated
  function and hold each to the method and path its operation names.
  """
  def generated(spec) do
    ops = operations(spec)

    Enum.flat_map(@groups, fn {prefix, module, mount, id_prefix, title} ->
      {head, _tail} = split_existing(module_file(module), module, mount, title)

      ops
      |> Enum.filter(&(&1.group == prefix))
      |> functions(head, id_prefix)
      |> Enum.map(&Map.merge(&1, %{module: Module.concat([module]), mount: mount}))
    end)
  end

  defp functions(ops, head, id_prefix) do
    covered = Regex.scan(~r/@operation\s+"([^"]+)"/, head) |> Enum.map(&List.last/1)

    ops
    |> Enum.reject(&(&1.key in covered))
    |> Enum.map(&Map.put(&1, :name, function_name(&1.id, id_prefix) <> &1.suffix))
    |> Enum.sort_by(& &1.name)
  end

  defp write_module(module, mount, id_prefix, title, ops, _spec, version) do
    file = module_file(module)
    {head, tail} = split_existing(file, module, mount, title)

    written = Regex.scan(~r/^\s+defp?\s+([a-z_][a-zA-Z0-9_?!]*)/m, head) |> Enum.map(&List.last/1)
    mount_expr = mount_expr(head, mount)
    functions = functions(ops, head, id_prefix)

    clashes = for f <- functions, f.name in written, do: "#{module}.#{f.name} (#{f.id})"

    if clashes != [] do
      Mix.raise("""
      A generated function would take the name of one written by hand:

      #{Enum.map_join(clashes, "\n", &"  #{&1}")}

      Mark the written one with the `@operation` it covers, or rename it.
      """)
    end

    block =
      [
        "#{@marker} from OpenBao #{version} ──",
        "  # Everything down to the closing marker is rewritten on every run. To",
        "  # curate a function, move it above this block and keep its `@operation`:",
        "  # the next run sees it there and stops generating it.",
        "",
        Enum.map_join(functions, "\n", &function_source(&1, mount, mount_expr)),
        @end_marker
      ]
      |> Enum.join("\n")

    source = head <> block <> "\n" <> tail
    formatted = source |> Code.format_string!() |> IO.iodata_to_binary()

    File.mkdir_p!(Path.dirname(file))
    File.write!(file, formatted <> "\n")
  end

  defp module_file(module) do
    parts = module |> String.split(".") |> Enum.map(&Macro.underscore/1)
    Path.join(["lib" | parts]) <> ".ex"
  end

  # What stays: everything before the block, and the `end` after it. A file
  # without a block gets one before its closing `end`; a file that does not
  # exist gets a head of its own.
  defp split_existing(file, module, mount, title) do
    if File.exists?(file),
      do: split_text(file, File.read!(file)),
      else: {new_head(module, mount, title), "end\n"}
  end

  defp split_text(file, text) do
    case String.split(text, @marker, parts: 2) do
      [head, rest] ->
        [_block, tail] = String.split(rest, @end_marker, parts: 2)
        {head, String.trim_leading(tail, "\n")}

      [_whole] ->
        unless text =~ "use ExBao.Operation",
          do: Mix.raise("#{file} has no `use ExBao.Operation`; add it before generating")

        {String.replace(text, ~r/\nend\s*\z/, "\n") <> "\n", "end\n"}
    end
  end

  defp new_head(module, mount, title) do
    where =
      if mount,
        do: "\n  Every function takes `:mount`, `\"#{mount}\"` by default.\n",
        else: ""

    """
    defmodule #{module} do
      @moduledoc \"\"\"
      #{title}

      Generated from OpenBao's OpenAPI specification by `mix bao.gen`. One
      function per endpoint: path parameters are arguments, every other field
      is an option, and the answer is the server's own JSON body. An option
      the endpoint does not accept raises `ArgumentError` rather than being
      sent and ignored.
      #{where}\"\"\"

      use ExBao.Operation

    """
  end

  defp mount_expr(_head, nil), do: nil

  defp mount_expr(head, mount) do
    if head =~ ~r/defp mount\(opts\)/,
      do: "mount(opts)",
      else: "ExBao.Operation.mount(opts, #{inspect(mount)})"
  end

  # ── writing a function ────────────────────────────────────────────────────

  defp function_name(id, prefix) do
    id
    |> String.replace_prefix(prefix, "")
    |> String.replace("-", "_")
  end

  defp function_source(op, mount, mount_expr) do
    names = Regex.scan(~r/\{(\w+)\}/, op.path) |> Enum.map(&List.last/1)
    params = Map.new(for p <- op.parameters, p["in"] == "path", do: {p["name"], p})
    args = Enum.map(names, &arg_name/1)

    path =
      op.path
      |> String.trim_leading("/")
      |> relocate(mount, mount_expr)
      |> interpolate(names)

    {fixed, query} = query_parameters(op.parameters)
    properties = op.body["properties"] || %{}
    body = properties |> Map.keys() |> Enum.sort()
    required = Enum.sort(op.body["required"] || [])

    spec =
      [
        body: atoms(body),
        query: atoms(Enum.map(query, & &1["name"])),
        required: atoms(required),
        fixed_query: fixed,
        content_type: if(op.method == "patch", do: "application/merge-patch+json")
      ]
      |> Enum.reject(fn {_key, value} -> value in [[], nil, %{}] end)

    arg_types = Enum.map(names, &arg_type(params[&1]))

    """
      @doc ~S\"\"\"
    #{doc(op, names, params, properties, query, required, mount)}
      \"\"\"
      @operation #{inspect(op.key)}
      @spec #{op.name}(#{Enum.join(["ExBao.server()" | arg_types] ++ ["keyword()"], ", ")}) ::
              ExBao.Operation.result()
      def #{op.name}(#{Enum.join(["server" | args] ++ ["opts \\\\ []"], ", ")}) do
        ExBao.Operation.call(server, :#{op.method}, "#{path}", opts, #{inspect(spec, limit: :infinity)})
      end
    """
  end

  # `{name}` in the template becomes the argument, escaped. A parameter that
  # is a path in its own right keeps its slashes.
  defp interpolate(path, names) do
    Enum.reduce(names, path, fn name, acc ->
      escape = if name in @slashed, do: "escape_path", else: "escape"
      String.replace(acc, "{#{name}}", "\#{ExBao.Operation.#{escape}(#{arg_name(name)})}")
    end)
  end

  defp relocate(path, nil, _expr), do: path

  defp relocate("auth/" <> rest, _mount, expr) do
    [_default | tail] = String.split(rest, "/", parts: 2)
    Enum.join(["auth", "\#{#{expr}}" | tail], "/")
  end

  defp relocate(path, _mount, expr) do
    [_default | tail] = String.split(path, "/", parts: 2)
    Enum.join(["\#{#{expr}}" | tail], "/")
  end

  # `list=true` on a LIST is not a choice the caller makes: an endpoint that
  # only lists requires it, and it is sent every time.
  defp query_parameters(parameters) do
    query = Enum.filter(parameters, &(&1["in"] == "query"))

    {fixed, optional} =
      Enum.split_with(
        query,
        &(&1["required"] == true and get_in(&1, ["schema", "enum"]) == ["true"])
      )

    {Map.new(fixed, &{&1["name"], "true"}), optional}
  end

  defp arg_name(name) when name in ~w(server opts), do: name <> "_param"
  defp arg_name(name), do: Macro.underscore(name)

  defp arg_type(%{"schema" => %{"type" => "integer"}}), do: "String.t() | integer()"
  defp arg_type(_param), do: "String.t()"

  defp atoms(names), do: Enum.map(names, &String.to_atom/1)

  # ── documentation ─────────────────────────────────────────────────────────

  defp doc(op, names, params, properties, query, required, mount) do
    summary = text(op.summary) || "`#{op.id}`"

    lines =
      [
        summary,
        "",
        "`#{String.upcase(op.method)} /v1#{op.path}`" <> notes(op),
        if(op.description && text(op.description) != summary,
          do: ["", text(op.description)],
          else: []
        ),
        section("Arguments", Enum.map(names, &arg_line(&1, params[&1]))),
        section(
          "Options",
          Enum.map(Enum.sort(Map.keys(properties)), &option_line(&1, properties[&1], required)) ++
            Enum.map(query, &option_line(&1["name"], &1["schema"] || %{}, [], &1["description"])) ++
            if(mount,
              do: ["  * `:mount` — where the engine is mounted, `\"#{mount}\"` by default."],
              else: []
            )
        )
      ]
      |> List.flatten()

    Enum.map_join(lines, "\n", fn
      "" -> ""
      line -> "  " <> line
    end)
  end

  defp notes(op) do
    [
      if(op.sudo, do: "needs `sudo`"),
      if(op.unauthenticated, do: "needs no token")
    ]
    |> Enum.reject(&is_nil/1)
    |> case do
      [] -> ""
      notes -> " — " <> Enum.join(notes, ", ")
    end
  end

  defp section(_title, []), do: []
  defp section(title, lines), do: ["", "## #{title}", "" | lines]

  defp arg_line(name, param) do
    "  * `#{arg_name(name)}` — " <> (text(param && param["description"]) || "")
  end

  defp option_line(name, schema, required, description \\ nil) do
    kind = schema["format"] || schema["type"] || "any"

    marks =
      Enum.reject(
        [if(name in required, do: "required"), if(schema["deprecated"], do: "deprecated")],
        &is_nil/1
      )

    marks = if marks == [], do: "", else: ", " <> Enum.join(marks, ", ")

    default =
      if Map.has_key?(schema, "default"),
        do: " Defaults to `#{inspect(schema["default"])}`.",
        else: ""

    about = text(description || schema["description"]) || ""

    "  * `#{inspect(String.to_atom(name))}` (#{kind}#{marks}) — #{about}#{default}"
    |> String.trim_trailing()
  end

  # One line, and nothing that would close the heredoc it lands in.
  defp text(nil), do: nil
  defp text(""), do: nil

  defp text(string) do
    string
    |> String.replace(~r/\s+/, " ")
    |> String.replace(~S("""), ~S("\""))
    |> String.trim()
  end
end
