defmodule ExBao.KV.V1 do
  @moduledoc """
    Version 1 of the key/value secrets engine: no versions, no metadata.

    Generated from OpenBao's OpenAPI specification by `mix bao.gen`. One
    function per endpoint: path parameters are arguments, every other field
    is an option, and the answer is the server's own JSON body. An option
    the endpoint does not accept raises `ArgumentError` rather than being
    sent and ignored.
    
    Every function takes `:mount`, `"kv"` by default.
  """

  use ExBao.Operation

  # ── generated by `mix bao.gen` from OpenBao 2.6.2 ──
  # Everything down to the closing marker is rewritten on every run. To
  # curate a function, move it above this block and keep its `@operation`:
  # the next run sees it there and stops generating it.

  @doc ~S"""
  Pass-through secret storage to the storage backend, allowing you to read/write arbitrary data into secret storage.

  `DELETE /v1/kv/{path}`

  ## Arguments

    * `path` — Location of the secret.

  ## Options

    * `:mount` — where the engine is mounted, `"kv"` by default.
  """
  @operation "kv-delete-path"
  @spec delete_path(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_path(server, path, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "#{ExBao.Operation.mount(opts, "kv")}/#{ExBao.Operation.escape_path(path)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Pass-through secret storage to the storage backend, allowing you to read/write arbitrary data into secret storage.

  `GET /v1/kv/{path}`

  ## Arguments

    * `path` — Location of the secret.

  ## Options

    * `:list` (string) — Return a list if `true`
    * `:scan` (string) — Return a recursive list if `true`
    * `:mount` — where the engine is mounted, `"kv"` by default.
  """
  @operation "kv-read-path"
  @spec read_path(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_path(server, path, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "kv")}/#{ExBao.Operation.escape_path(path)}",
      opts,
      query: [:list, :scan]
    )
  end

  @doc ~S"""
  Pass-through secret storage to the storage backend, allowing you to read/write arbitrary data into secret storage.

  `POST /v1/kv/{path}`

  ## Arguments

    * `path` — Location of the secret.

  ## Options

    * `:mount` — where the engine is mounted, `"kv"` by default.
  """
  @operation "kv-write-path"
  @spec write_path(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_path(server, path, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "kv")}/#{ExBao.Operation.escape_path(path)}",
      opts,
      []
    )
  end

  # ── end of generated ──
end
