defmodule ExBao.Auth.AppRole do
  @moduledoc """
  Logging in with AppRole, which is how a service authenticates.

  A role id names *which* service and is not secret — it is fine in a
  configuration file. A secret id is the credential and is not. Splitting
  them is the point of the method: the part that identifies can be deployed
  with the code, and the part that authenticates can be delivered separately
  and rotated without a release.

  What comes back is a token with a lease. Keeping that token alive is
  `ExBao.TokenServer`'s job, not this module's — here you log in once and get
  told how long it lasts.
  """

  alias ExBao.{Auth, Client, Error, Operation}

  use ExBao.Operation

  @doc """
  Exchanges a role id and a secret id for a token.

  ## Options

    * `:role_id` — required. From `BAO_ROLE_ID` otherwise.
    * `:secret_id` — required. From `BAO_SECRET_ID` otherwise.
    * `:mount` — where the method is mounted, `"approle"` by default. A
      server can mount the same method twice under different paths, and then
      the mount is the only thing that says which one you mean. `:path` is
      still accepted for it, as it was in 0.1.0.

  ## Examples

      iex> ExBao.Auth.AppRole.login(client, role_id: "db02de0...", secret_id: "6a17...")
      {:ok, %ExBao.Auth{token: "s.wOrM...", lease_duration: 2_764_800, renewable: true}}
  """
  @operation "app-role-login"
  @spec login(Client.t(), keyword()) :: {:ok, Auth.t()} | {:error, Error.t()}
  def login(%Client{} = client, opts \\ []) do
    with {:ok, role_id} <- fetch(opts, :role_id, "BAO_ROLE_ID"),
         {:ok, secret_id} <- fetch(opts, :secret_id, "BAO_SECRET_ID") do
      client
      |> Client.request(:post, "auth/#{mount(opts)}/login", %{
        "role_id" => role_id,
        "secret_id" => secret_id
      })
      |> then(&Auth.from_response/1)
    end
  end

  @doc """
  Reads the role id of a role. Useful when provisioning, not at runtime.

  Takes a client or a token server, and `:mount` as `login/2` does.
  """
  @operation "app-role-read-role-id"
  @spec read_role_id(ExBao.server(), String.t(), keyword()) ::
          {:ok, String.t()} | {:error, Error.t()}
  def read_role_id(server, role, opts \\ []) do
    case Operation.request(server, :get, role_path(opts, role, "role-id")) do
      {:ok, %{"data" => %{"role_id" => role_id}}} -> {:ok, role_id}
      {:ok, other} -> {:error, Operation.unexpected(other)}
      {:error, error} -> {:error, error}
    end
  end

  @doc """
  Issues a new secret id for a role. Useful when provisioning, not at runtime.

  Takes a client or a token server, and `:mount` as `login/2` does.
  """
  @operation "app-role-write-secret-id"
  @spec generate_secret_id(ExBao.server(), String.t(), keyword()) ::
          {:ok, map()} | {:error, Error.t()}
  def generate_secret_id(server, role, opts \\ []) do
    case Operation.request(server, :post, role_path(opts, role, "secret-id"), %{}) do
      {:ok, %{"data" => data}} -> {:ok, data}
      {:ok, other} -> {:error, Operation.unexpected(other)}
      {:error, error} -> {:error, error}
    end
  end

  # `:path` was the option's name in 0.1.0. It keeps working, and `:mount`
  # wins when both are given, since it is the name every module shares.
  defp mount(opts), do: Operation.mount(opts, Keyword.get(opts, :path, "approle"))

  # The role name is escaped: one from user input must not be able to
  # address a different endpoint. The mount is not, since a method mounted
  # under `team/approle` legitimately has a slash in it.
  defp role_path(opts, role, leaf),
    do: "auth/#{mount(opts)}/role/#{Operation.escape(role)}/#{leaf}"

  # A missing credential is not a request worth making: sending `nil` would
  # get a 400 back and the error would describe the server's opinion of an
  # empty field instead of the fact that nobody configured it.
  defp fetch(opts, key, env_var) do
    case Keyword.get(opts, key) || System.get_env(env_var) ||
           Application.get_env(:ex_bao, key) do
      nil ->
        {:error,
         %Error{
           kind: :invalid_credentials,
           messages: ["missing #{key}: pass it, or set #{env_var}"]
         }}

      value ->
        {:ok, value}
    end
  end

  # ── generated by `mix bao.gen` from OpenBao 2.6.2 ──
  # Everything down to the closing marker is rewritten on every run. To
  # curate a function, move it above this block and keep its `@operation`:
  # the next run sees it there and stops generating it.

  @doc ~S"""
  Impose secret_id to be presented during login using this role.

  `DELETE /v1/auth/approle/role/{role_name}/bind-secret-id`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-delete-bind-secret-id"
  @spec delete_bind_secret_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_bind_secret_id(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/bind-secret-id",
      opts,
      []
    )
  end

  @doc ~S"""
  Deprecated: Comma separated list of CIDR blocks, if set, specifies blocks of IP addresses which can perform the login operation

  `DELETE /v1/auth/approle/role/{role_name}/bound-cidr-list`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-delete-bound-cidr-list"
  @spec delete_bound_cidr_list(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_bound_cidr_list(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/bound-cidr-list",
      opts,
      []
    )
  end

  @doc ~S"""
  Updates the value of 'period' on the role

  `DELETE /v1/auth/approle/role/{role_name}/period`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-delete-period"
  @spec delete_period(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_period(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/period",
      opts,
      []
    )
  end

  @doc ~S"""
  Policies of the role.

  `DELETE /v1/auth/approle/role/{role_name}/policies`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-delete-policies"
  @spec delete_policies(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_policies(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/policies",
      opts,
      []
    )
  end

  @doc ~S"""
  Register an role with the backend.

  `DELETE /v1/auth/approle/role/{role_name}`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-delete-role"
  @spec delete_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_role(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Comma separated list of CIDR blocks, if set, specifies blocks of IP addresses which can perform the login operation

  `DELETE /v1/auth/approle/role/{role_name}/secret-id-bound-cidrs`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-delete-secret-id-bound-cidrs"
  @spec delete_secret_id_bound_cidrs(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_secret_id_bound_cidrs(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/secret-id-bound-cidrs",
      opts,
      []
    )
  end

  @doc ~S"""
  Use limit of the SecretID generated against the role.

  `DELETE /v1/auth/approle/role/{role_name}/secret-id-num-uses`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-delete-secret-id-num-uses"
  @spec delete_secret_id_num_uses(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_secret_id_num_uses(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/secret-id-num-uses",
      opts,
      []
    )
  end

  @doc ~S"""
  Duration in seconds of the SecretID generated against the role.

  `DELETE /v1/auth/approle/role/{role_name}/secret-id-ttl`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-delete-secret-id-ttl"
  @spec delete_secret_id_ttl(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_secret_id_ttl(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/secret-id-ttl",
      opts,
      []
    )
  end

  @doc ~S"""
  Comma separated string or list of CIDR blocks. If set, specifies the blocks of IP addresses which can use the returned token.

  `DELETE /v1/auth/approle/role/{role_name}/token-bound-cidrs`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-delete-token-bound-cidrs"
  @spec delete_token_bound_cidrs(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_token_bound_cidrs(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/token-bound-cidrs",
      opts,
      []
    )
  end

  @doc ~S"""
  Duration in seconds, the maximum lifetime of the tokens issued by using the SecretIDs that were generated against this role, after which the tokens are not allowed to be renewed.

  `DELETE /v1/auth/approle/role/{role_name}/token-max-ttl`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-delete-token-max-ttl"
  @spec delete_token_max_ttl(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_token_max_ttl(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/token-max-ttl",
      opts,
      []
    )
  end

  @doc ~S"""
  Number of times issued tokens can be used

  `DELETE /v1/auth/approle/role/{role_name}/token-num-uses`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-delete-token-num-uses"
  @spec delete_token_num_uses(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_token_num_uses(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/token-num-uses",
      opts,
      []
    )
  end

  @doc ~S"""
  Duration in seconds, the lifetime of the token issued by using the SecretID that is generated against this role, before which the token needs to be renewed.

  `DELETE /v1/auth/approle/role/{role_name}/token-ttl`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-delete-token-ttl"
  @spec delete_token_ttl(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_token_ttl(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/token-ttl",
      opts,
      []
    )
  end

  @doc ~S"""
  Invalidate an issued secret_id

  `POST /v1/auth/approle/role/{role_name}/secret-id/destroy`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:secret_id` (string) — SecretID attached to the role.
    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-destroy-secret-id"
  @spec destroy_secret_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def destroy_secret_id(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/secret-id/destroy",
      opts,
      body: [:secret_id]
    )
  end

  @doc ~S"""
  Invalidate an issued secret_id

  `DELETE /v1/auth/approle/role/{role_name}/secret-id/destroy`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-destroy-secret-id2"
  @spec destroy_secret_id2(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def destroy_secret_id2(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/secret-id/destroy",
      opts,
      []
    )
  end

  @doc ~S"""
  `app-role-destroy-secret-id-by-accessor`

  `POST /v1/auth/approle/role/{role_name}/secret-id-accessor/destroy`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:secret_id_accessor` (string) — Accessor of the SecretID
    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-destroy-secret-id-by-accessor"
  @spec destroy_secret_id_by_accessor(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def destroy_secret_id_by_accessor(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/secret-id-accessor/destroy",
      opts,
      body: [:secret_id_accessor]
    )
  end

  @doc ~S"""
  `app-role-destroy-secret-id-by-accessor2`

  `DELETE /v1/auth/approle/role/{role_name}/secret-id-accessor/destroy`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-destroy-secret-id-by-accessor2"
  @spec destroy_secret_id_by_accessor2(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def destroy_secret_id_by_accessor2(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/secret-id-accessor/destroy",
      opts,
      []
    )
  end

  @doc ~S"""
  Lists all the roles registered with the backend.

  `GET /v1/auth/approle/role`

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-list-roles"
  @spec list_roles(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def list_roles(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "auth/#{mount(opts)}/role", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Generate a SecretID against this role.

  `GET /v1/auth/approle/role/{role_name}/secret-id`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-list-secret-ids"
  @spec list_secret_ids(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def list_secret_ids(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/secret-id",
      opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Read the properties of an issued secret_id

  `POST /v1/auth/approle/role/{role_name}/secret-id/lookup`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:secret_id` (string) — SecretID attached to the role.
    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-look-up-secret-id"
  @spec look_up_secret_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def look_up_secret_id(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/secret-id/lookup",
      opts,
      body: [:secret_id]
    )
  end

  @doc ~S"""
  `app-role-look-up-secret-id-by-accessor`

  `POST /v1/auth/approle/role/{role_name}/secret-id-accessor/lookup`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:secret_id_accessor` (string) — Accessor of the SecretID
    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-look-up-secret-id-by-accessor"
  @spec look_up_secret_id_by_accessor(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def look_up_secret_id_by_accessor(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/secret-id-accessor/lookup",
      opts,
      body: [:secret_id_accessor]
    )
  end

  @doc ~S"""
  Impose secret_id to be presented during login using this role.

  `GET /v1/auth/approle/role/{role_name}/bind-secret-id`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-read-bind-secret-id"
  @spec read_bind_secret_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_bind_secret_id(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/bind-secret-id",
      opts,
      []
    )
  end

  @doc ~S"""
  Deprecated: Comma separated list of CIDR blocks, if set, specifies blocks of IP addresses which can perform the login operation

  `GET /v1/auth/approle/role/{role_name}/bound-cidr-list`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-read-bound-cidr-list"
  @spec read_bound_cidr_list(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_bound_cidr_list(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/bound-cidr-list",
      opts,
      []
    )
  end

  @doc ~S"""
  Enables cluster local secret IDs

  `GET /v1/auth/approle/role/{role_name}/local-secret-ids`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-read-local-secret-ids"
  @spec read_local_secret_ids(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_local_secret_ids(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/local-secret-ids",
      opts,
      []
    )
  end

  @doc ~S"""
  Updates the value of 'period' on the role

  `GET /v1/auth/approle/role/{role_name}/period`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-read-period"
  @spec read_period(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_period(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/period",
      opts,
      []
    )
  end

  @doc ~S"""
  Policies of the role.

  `GET /v1/auth/approle/role/{role_name}/policies`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-read-policies"
  @spec read_policies(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_policies(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/policies",
      opts,
      []
    )
  end

  @doc ~S"""
  Register an role with the backend.

  `GET /v1/auth/approle/role/{role_name}`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-read-role"
  @spec read_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_role(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Comma separated list of CIDR blocks, if set, specifies blocks of IP addresses which can perform the login operation

  `GET /v1/auth/approle/role/{role_name}/secret-id-bound-cidrs`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-read-secret-id-bound-cidrs"
  @spec read_secret_id_bound_cidrs(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_secret_id_bound_cidrs(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/secret-id-bound-cidrs",
      opts,
      []
    )
  end

  @doc ~S"""
  Use limit of the SecretID generated against the role.

  `GET /v1/auth/approle/role/{role_name}/secret-id-num-uses`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-read-secret-id-num-uses"
  @spec read_secret_id_num_uses(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_secret_id_num_uses(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/secret-id-num-uses",
      opts,
      []
    )
  end

  @doc ~S"""
  Duration in seconds of the SecretID generated against the role.

  `GET /v1/auth/approle/role/{role_name}/secret-id-ttl`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-read-secret-id-ttl"
  @spec read_secret_id_ttl(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_secret_id_ttl(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/secret-id-ttl",
      opts,
      []
    )
  end

  @doc ~S"""
  Comma separated string or list of CIDR blocks. If set, specifies the blocks of IP addresses which can use the returned token.

  `GET /v1/auth/approle/role/{role_name}/token-bound-cidrs`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-read-token-bound-cidrs"
  @spec read_token_bound_cidrs(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_token_bound_cidrs(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/token-bound-cidrs",
      opts,
      []
    )
  end

  @doc ~S"""
  Duration in seconds, the maximum lifetime of the tokens issued by using the SecretIDs that were generated against this role, after which the tokens are not allowed to be renewed.

  `GET /v1/auth/approle/role/{role_name}/token-max-ttl`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-read-token-max-ttl"
  @spec read_token_max_ttl(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_token_max_ttl(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/token-max-ttl",
      opts,
      []
    )
  end

  @doc ~S"""
  Number of times issued tokens can be used

  `GET /v1/auth/approle/role/{role_name}/token-num-uses`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-read-token-num-uses"
  @spec read_token_num_uses(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_token_num_uses(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/token-num-uses",
      opts,
      []
    )
  end

  @doc ~S"""
  Duration in seconds, the lifetime of the token issued by using the SecretID that is generated against this role, before which the token needs to be renewed.

  `GET /v1/auth/approle/role/{role_name}/token-ttl`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-read-token-ttl"
  @spec read_token_ttl(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_token_ttl(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/token-ttl",
      opts,
      []
    )
  end

  @doc ~S"""
  Trigger the clean-up of expired SecretID entries.

  `POST /v1/auth/approle/tidy/secret-id`

  ## Options

    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-tidy-secret-id"
  @spec tidy_secret_id(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def tidy_secret_id(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "auth/#{mount(opts)}/tidy/secret-id", opts, [])
  end

  @doc ~S"""
  Impose secret_id to be presented during login using this role.

  `POST /v1/auth/approle/role/{role_name}/bind-secret-id`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:bind_secret_id` (boolean) — Impose secret_id to be presented when logging in using this role. Defaults to `true`.
    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-write-bind-secret-id"
  @spec write_bind_secret_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_bind_secret_id(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/bind-secret-id",
      opts,
      body: [:bind_secret_id]
    )
  end

  @doc ~S"""
  Deprecated: Comma separated list of CIDR blocks, if set, specifies blocks of IP addresses which can perform the login operation

  `POST /v1/auth/approle/role/{role_name}/bound-cidr-list`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:bound_cidr_list` (array) — Deprecated: Please use "secret_id_bound_cidrs" instead. Comma separated string or list of CIDR blocks. If set, specifies the blocks of IP addresses which can perform the login operation.
    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-write-bound-cidr-list"
  @spec write_bound_cidr_list(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_bound_cidr_list(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/bound-cidr-list",
      opts,
      body: [:bound_cidr_list]
    )
  end

  @doc ~S"""
  Assign a SecretID of choice against the role.

  `POST /v1/auth/approle/role/{role_name}/custom-secret-id`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:cidr_list` (array) — Comma separated string or list of CIDR blocks enforcing secret IDs to be used from specific set of IP addresses. If 'bound_cidr_list' is set on the role, then the list of CIDR blocks listed here should be a subset of the CIDR blocks listed on the role.
    * `:metadata` (string) — Metadata to be tied to the SecretID. This should be a JSON formatted string containing metadata in key value pairs.
    * `:num_uses` (integer) — Number of times this SecretID can be used, after which the SecretID expires. Overrides secret_id_num_uses role option when supplied. May not be higher than role's secret_id_num_uses.
    * `:secret_id` (string) — SecretID to be attached to the role.
    * `:token_bound_cidrs` (array) — Comma separated string or list of CIDR blocks. If set, specifies the blocks of IP addresses which can use the returned token. Should be a subset of the token CIDR blocks listed on the role, if any.
    * `:ttl` (seconds) — Duration in seconds after which this SecretID expires. Overrides secret_id_ttl role option when supplied. May not be longer than role's secret_id_ttl.
    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-write-custom-secret-id"
  @spec write_custom_secret_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_custom_secret_id(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/custom-secret-id",
      opts,
      body: [:cidr_list, :metadata, :num_uses, :secret_id, :token_bound_cidrs, :ttl]
    )
  end

  @doc ~S"""
  Updates the value of 'period' on the role

  `POST /v1/auth/approle/role/{role_name}/period`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:period` (seconds, deprecated) — Use "token_period" instead. If this and "token_period" are both specified, only "token_period" will be used.
    * `:token_period` (seconds) — If set, tokens created via this role will have no max lifetime; instead, their renewal period will be fixed to this value. This takes an integer number of seconds, or a string duration (e.g. "24h").
    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-write-period"
  @spec write_period(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_period(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/period",
      opts,
      body: [:period, :token_period]
    )
  end

  @doc ~S"""
  Policies of the role.

  `POST /v1/auth/approle/role/{role_name}/policies`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:policies` (array, deprecated) — Use "token_policies" instead. If this and "token_policies" are both specified, only "token_policies" will be used.
    * `:token_policies` (array) — Comma-separated list of policies
    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-write-policies"
  @spec write_policies(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_policies(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/policies",
      opts,
      body: [:policies, :token_policies]
    )
  end

  @doc ~S"""
  Register an role with the backend.

  `POST /v1/auth/approle/role/{role_name}`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:bind_secret_id` (boolean) — Impose secret_id to be presented when logging in using this role. Defaults to 'true'. Defaults to `true`.
    * `:bound_cidr_list` (array, deprecated) — Use "secret_id_bound_cidrs" instead.
    * `:local_secret_ids` (boolean) — If set, the secret IDs generated using this role will be cluster local. This can only be set during role creation and once set, it can't be reset later.
    * `:period` (seconds, deprecated) — Use "token_period" instead. If this and "token_period" are both specified, only "token_period" will be used.
    * `:policies` (array, deprecated) — Use "token_policies" instead. If this and "token_policies" are both specified, only "token_policies" will be used.
    * `:role_id` (string) — Identifier of the role. Defaults to a UUID.
    * `:secret_id_bound_cidrs` (array) — Comma separated string or list of CIDR blocks. If set, specifies the blocks of IP addresses which can perform the login operation.
    * `:secret_id_num_uses` (integer) — Number of times a SecretID can access the role, after which the SecretID will expire. Defaults to 0 meaning that the the secret_id is of unlimited use.
    * `:secret_id_ttl` (seconds) — Duration in seconds after which the issued SecretID should expire. Defaults to 0, meaning no expiration.
    * `:token_bound_cidrs` (array) — Comma separated string or JSON list of CIDR blocks. If set, specifies the blocks of IP addresses which are allowed to use the generated token.
    * `:token_explicit_max_ttl` (seconds) — If set, tokens created via this role carry an explicit maximum TTL. During renewal, the current maximum TTL values of the role and the mount are not checked for changes, and any updates to these values will have no effect on the token being renewed.
    * `:token_max_ttl` (seconds) — The maximum lifetime of the generated token
    * `:token_no_default_policy` (boolean) — If true, the 'default' policy will not automatically be added to generated tokens
    * `:token_num_uses` (integer) — The maximum number of times a token may be used, a value of zero means unlimited
    * `:token_period` (seconds) — If set, tokens created via this role will have no max lifetime; instead, their renewal period will be fixed to this value. This takes an integer number of seconds, or a string duration (e.g. "24h").
    * `:token_policies` (array) — Comma-separated list of policies
    * `:token_strictly_bind_ip` (boolean) — If true, CIDRs for the token will be strictly bound to the source IP address of the login request
    * `:token_ttl` (seconds) — The initial ttl of the token to generate
    * `:token_type` (string) — The type of token to generate, service or batch Defaults to `"default-service"`.
    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-write-role"
  @spec write_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_role(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}",
      opts,
      body: [
        :bind_secret_id,
        :bound_cidr_list,
        :local_secret_ids,
        :period,
        :policies,
        :role_id,
        :secret_id_bound_cidrs,
        :secret_id_num_uses,
        :secret_id_ttl,
        :token_bound_cidrs,
        :token_explicit_max_ttl,
        :token_max_ttl,
        :token_no_default_policy,
        :token_num_uses,
        :token_period,
        :token_policies,
        :token_strictly_bind_ip,
        :token_ttl,
        :token_type
      ]
    )
  end

  @doc ~S"""
  Returns the 'role_id' of the role.

  `POST /v1/auth/approle/role/{role_name}/role-id`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:role_id` (string) — Identifier of the role. Defaults to a UUID.
    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-write-role-id"
  @spec write_role_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_role_id(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/role-id",
      opts,
      body: [:role_id]
    )
  end

  @doc ~S"""
  Comma separated list of CIDR blocks, if set, specifies blocks of IP addresses which can perform the login operation

  `POST /v1/auth/approle/role/{role_name}/secret-id-bound-cidrs`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:secret_id_bound_cidrs` (array) — Comma separated string or list of CIDR blocks. If set, specifies the blocks of IP addresses which can perform the login operation.
    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-write-secret-id-bound-cidrs"
  @spec write_secret_id_bound_cidrs(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_secret_id_bound_cidrs(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/secret-id-bound-cidrs",
      opts,
      body: [:secret_id_bound_cidrs]
    )
  end

  @doc ~S"""
  Use limit of the SecretID generated against the role.

  `POST /v1/auth/approle/role/{role_name}/secret-id-num-uses`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:secret_id_num_uses` (integer) — Number of times a SecretID can access the role, after which the SecretID will expire.
    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-write-secret-id-num-uses"
  @spec write_secret_id_num_uses(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_secret_id_num_uses(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/secret-id-num-uses",
      opts,
      body: [:secret_id_num_uses]
    )
  end

  @doc ~S"""
  Duration in seconds of the SecretID generated against the role.

  `POST /v1/auth/approle/role/{role_name}/secret-id-ttl`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:secret_id_ttl` (seconds) — Duration in seconds after which the issued SecretID should expire. Defaults to 0, meaning no expiration.
    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-write-secret-id-ttl"
  @spec write_secret_id_ttl(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_secret_id_ttl(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/secret-id-ttl",
      opts,
      body: [:secret_id_ttl]
    )
  end

  @doc ~S"""
  Comma separated string or list of CIDR blocks. If set, specifies the blocks of IP addresses which can use the returned token.

  `POST /v1/auth/approle/role/{role_name}/token-bound-cidrs`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:token_bound_cidrs` (array) — Comma separated string or JSON list of CIDR blocks. If set, specifies the blocks of IP addresses which are allowed to use the generated token.
    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-write-token-bound-cidrs"
  @spec write_token_bound_cidrs(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_token_bound_cidrs(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/token-bound-cidrs",
      opts,
      body: [:token_bound_cidrs]
    )
  end

  @doc ~S"""
  Duration in seconds, the maximum lifetime of the tokens issued by using the SecretIDs that were generated against this role, after which the tokens are not allowed to be renewed.

  `POST /v1/auth/approle/role/{role_name}/token-max-ttl`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:token_max_ttl` (seconds) — The maximum lifetime of the generated token
    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-write-token-max-ttl"
  @spec write_token_max_ttl(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_token_max_ttl(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/token-max-ttl",
      opts,
      body: [:token_max_ttl]
    )
  end

  @doc ~S"""
  Number of times issued tokens can be used

  `POST /v1/auth/approle/role/{role_name}/token-num-uses`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:token_num_uses` (integer) — The maximum number of times a token may be used, a value of zero means unlimited
    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-write-token-num-uses"
  @spec write_token_num_uses(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_token_num_uses(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/token-num-uses",
      opts,
      body: [:token_num_uses]
    )
  end

  @doc ~S"""
  Duration in seconds, the lifetime of the token issued by using the SecretID that is generated against this role, before which the token needs to be renewed.

  `POST /v1/auth/approle/role/{role_name}/token-ttl`

  ## Arguments

    * `role_name` — Name of the role. Must be less than 4096 bytes.

  ## Options

    * `:token_ttl` (seconds) — The initial ttl of the token to generate
    * `:mount` — where the engine is mounted, `"approle"` by default.
  """
  @operation "app-role-write-token-ttl"
  @spec write_token_ttl(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_token_ttl(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{mount(opts)}/role/#{ExBao.Operation.escape(role_name)}/token-ttl",
      opts,
      body: [:token_ttl]
    )
  end

  # ── end of generated ──
end
