defmodule ExBao.Auth.Cert do
  @moduledoc """
    The TLS certificate auth method.

    Generated from OpenBao's OpenAPI specification by `mix bao.gen`. One
    function per endpoint: path parameters are arguments, every other field
    is an option, and the answer is the server's own JSON body. An option
    the endpoint does not accept raises `ArgumentError` rather than being
    sent and ignored.
    
    Every function takes `:mount`, `"cert"` by default.
  """

  use ExBao.Operation

  # ── generated by `mix bao.gen` from OpenBao 2.6.2 ──
  # Everything down to the closing marker is rewritten on every run. To
  # curate a function, move it above this block and keep its `@operation`:
  # the next run sees it there and stops generating it.

  @doc ~S"""
  `cert-configure`

  `POST /v1/auth/cert/config`

  ## Options

    * `:disable_binding` (boolean) — If set, during renewal, skips the matching of presented client identity with the client identity used during login. Defaults to false. Defaults to `false`.
    * `:enable_identity_alias_metadata` (boolean) — If set, metadata of the certificate including the metadata corresponding to allowed_metadata_extensions will be stored in the alias. Defaults to false. Defaults to `false`.
    * `:ocsp_cache_size` (integer) — The size of the in memory OCSP response cache, shared by all configured certs Defaults to `100`.
    * `:mount` — where the engine is mounted, `"cert"` by default.
  """
  @operation "cert-configure"
  @spec configure(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def configure(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "cert")}/config",
      opts,
      body: [:disable_binding, :enable_identity_alias_metadata, :ocsp_cache_size]
    )
  end

  @doc ~S"""
  Manage trusted certificates used for authentication.

  `DELETE /v1/auth/cert/certs/{name}`

  ## Arguments

    * `name` — The name of the certificate

  ## Options

    * `:mount` — where the engine is mounted, `"cert"` by default.
  """
  @operation "cert-delete-certificate"
  @spec delete_certificate(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_certificate(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/#{ExBao.Operation.mount(opts, "cert")}/certs/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage Certificate Revocation Lists checked during authentication.

  `DELETE /v1/auth/cert/crls/{name}`

  ## Arguments

    * `name` — The name of the certificate

  ## Options

    * `:mount` — where the engine is mounted, `"cert"` by default.
  """
  @operation "cert-delete-crl"
  @spec delete_crl(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_crl(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/#{ExBao.Operation.mount(opts, "cert")}/crls/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage trusted certificates used for authentication.

  `GET /v1/auth/cert/certs`

  ## Options

    * `:mount` — where the engine is mounted, `"cert"` by default.
  """
  @operation "cert-list-certificates"
  @spec list_certificates(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def list_certificates(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "auth/#{ExBao.Operation.mount(opts, "cert")}/certs", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Manage Certificate Revocation Lists checked during authentication.

  `GET /v1/auth/cert/crls`

  ## Options

    * `:mount` — where the engine is mounted, `"cert"` by default.
  """
  @operation "cert-list-crls"
  @spec list_crls(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def list_crls(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "auth/#{ExBao.Operation.mount(opts, "cert")}/crls", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  `cert-login`

  `POST /v1/auth/cert/login` — needs no token

  ## Options

    * `:name` (string) — The name of the certificate role to authenticate against.
    * `:mount` — where the engine is mounted, `"cert"` by default.
  """
  @operation "cert-login"
  @spec login(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def login(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "auth/#{ExBao.Operation.mount(opts, "cert")}/login", opts,
      body: [:name]
    )
  end

  @doc ~S"""
  Manage trusted certificates used for authentication.

  `GET /v1/auth/cert/certs/{name}`

  ## Arguments

    * `name` — The name of the certificate

  ## Options

    * `:mount` — where the engine is mounted, `"cert"` by default.
  """
  @operation "cert-read-certificate"
  @spec read_certificate(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_certificate(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{ExBao.Operation.mount(opts, "cert")}/certs/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  `cert-read-configuration`

  `GET /v1/auth/cert/config`

  ## Options

    * `:mount` — where the engine is mounted, `"cert"` by default.
  """
  @operation "cert-read-configuration"
  @spec read_configuration(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def read_configuration(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{ExBao.Operation.mount(opts, "cert")}/config",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage Certificate Revocation Lists checked during authentication.

  `GET /v1/auth/cert/crls/{name}`

  ## Arguments

    * `name` — The name of the certificate

  ## Options

    * `:mount` — where the engine is mounted, `"cert"` by default.
  """
  @operation "cert-read-crl"
  @spec read_crl(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_crl(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{ExBao.Operation.mount(opts, "cert")}/crls/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage trusted certificates used for authentication.

  `POST /v1/auth/cert/certs/{name}`

  ## Arguments

    * `name` — The name of the certificate

  ## Options

    * `:allowed_common_names` (array) — A comma-separated list of names. At least one must exist in the Common Name. Supports globbing.
    * `:allowed_dns_sans` (array) — A comma-separated list of DNS names. At least one must exist in the SANs. Supports globbing.
    * `:allowed_email_sans` (array) — A comma-separated list of Email Addresses. At least one must exist in the SANs. Supports globbing.
    * `:allowed_metadata_extensions` (array) — A comma-separated string or array of oid extensions. Upon successful authentication, these extensions will be added as metadata if they are present in the certificate. The metadata key will be the string consisting of the oid numbers separated by a dash (-) instead of a dot (.) to allow usage in ACL templates.
    * `:allowed_names` (array) — A comma-separated list of names. At least one must exist in either the Common Name or SANs. Supports globbing. This parameter is deprecated, please use allowed_common_names, allowed_dns_sans, allowed_email_sans, allowed_uri_sans.
    * `:allowed_organizational_units` (array) — A comma-separated list of Organizational Units names. At least one must exist in the OU field.
    * `:allowed_uri_sans` (array) — A comma-separated list of URIs. At least one must exist in the SANs. Supports globbing.
    * `:bound_cidrs` (array, deprecated) — Use "token_bound_cidrs" instead. If this and "token_bound_cidrs" are both specified, only "token_bound_cidrs" will be used.
    * `:certificate` (string) — The public certificate that should be trusted. Must be x509 PEM encoded.
    * `:display_name` (string) — The display name to use for clients using this certificate.
    * `:lease` (integer, deprecated) — Use "token_ttl" instead. If this and "token_ttl" are both specified, only "token_ttl" will be used.
    * `:max_ttl` (seconds, deprecated) — Use "token_max_ttl" instead. If this and "token_max_ttl" are both specified, only "token_max_ttl" will be used.
    * `:ocsp_ca_certificates` (string) — Any additional CA certificates needed to communicate with OCSP servers
    * `:ocsp_enabled` (boolean) — Whether to attempt OCSP verification of certificates at login
    * `:ocsp_fail_open` (boolean) — If set to true, if an OCSP revocation cannot be made successfully, login will proceed rather than failing. If false, failing to get an OCSP status fails the request. Defaults to `false`.
    * `:ocsp_query_all_servers` (boolean) — If set to true, rather than accepting the first successful OCSP response, query all servers and consider the certificate valid only if all servers agree. Defaults to `false`.
    * `:ocsp_servers_override` (array) — A comma-separated list of OCSP server addresses. If unset, the OCSP server is determined from the AuthorityInformationAccess extension on the certificate being inspected.
    * `:period` (seconds, deprecated) — Use "token_period" instead. If this and "token_period" are both specified, only "token_period" will be used.
    * `:policies` (array, deprecated) — Use "token_policies" instead. If this and "token_policies" are both specified, only "token_policies" will be used.
    * `:required_extensions` (array) — A comma-separated string or array of extensions formatted as "oid:value". Expects the extension value to be some type of ASN1 encoded string. All values much match. Supports globbing on "value".
    * `:token_bound_cidrs` (array) — Comma separated string or JSON list of CIDR blocks. If set, specifies the blocks of IP addresses which are allowed to use the generated token.
    * `:token_explicit_max_ttl` (seconds) — If set, tokens created via this role carry an explicit maximum TTL. During renewal, the current maximum TTL values of the role and the mount are not checked for changes, and any updates to these values will have no effect on the token being renewed.
    * `:token_max_ttl` (seconds) — The maximum lifetime of the generated token
    * `:token_no_default_policy` (boolean) — If true, the 'default' policy will not automatically be added to generated tokens
    * `:token_num_uses` (integer) — The maximum number of times a token may be used, a value of zero means unlimited
    * `:token_period` (seconds) — If set, tokens created via this role will have no max lifetime; instead, their renewal period will be fixed to this value. This takes an integer number of seconds, or a string duration (e.g. "24h").
    * `:token_policies` (array) — Comma-separated list of policies
    * `:token_strictly_bind_ip` (boolean) — If true, CIDRs for the token will be strictly bound to the source IP address of the login request
    * `:token_ttl` (seconds) — The initial ttl of the token to generate
    * `:token_type` (string) — The type of token to generate, service or batch Defaults to `"default-service"`.
    * `:ttl` (seconds, deprecated) — Use "token_ttl" instead. If this and "token_ttl" are both specified, only "token_ttl" will be used.
    * `:mount` — where the engine is mounted, `"cert"` by default.
  """
  @operation "cert-write-certificate"
  @spec write_certificate(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_certificate(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "cert")}/certs/#{ExBao.Operation.escape(name)}",
      opts,
      body: [
        :allowed_common_names,
        :allowed_dns_sans,
        :allowed_email_sans,
        :allowed_metadata_extensions,
        :allowed_names,
        :allowed_organizational_units,
        :allowed_uri_sans,
        :bound_cidrs,
        :certificate,
        :display_name,
        :lease,
        :max_ttl,
        :ocsp_ca_certificates,
        :ocsp_enabled,
        :ocsp_fail_open,
        :ocsp_query_all_servers,
        :ocsp_servers_override,
        :period,
        :policies,
        :required_extensions,
        :token_bound_cidrs,
        :token_explicit_max_ttl,
        :token_max_ttl,
        :token_no_default_policy,
        :token_num_uses,
        :token_period,
        :token_policies,
        :token_strictly_bind_ip,
        :token_ttl,
        :token_type,
        :ttl
      ]
    )
  end

  @doc ~S"""
  Manage Certificate Revocation Lists checked during authentication.

  `POST /v1/auth/cert/crls/{name}`

  ## Arguments

    * `name` — The name of the certificate

  ## Options

    * `:crl` (string) — The public CRL that should be trusted to attest to certificates' validity statuses. May be DER or PEM encoded. Note: the expiration time is ignored; if the CRL is no longer valid, delete it using the same name as specified here.
    * `:url` (string) — The URL of a CRL distribution point. Only one of 'crl' or 'url' parameters should be specified.
    * `:mount` — where the engine is mounted, `"cert"` by default.
  """
  @operation "cert-write-crl"
  @spec write_crl(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_crl(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "cert")}/crls/#{ExBao.Operation.escape(name)}",
      opts,
      body: [:crl, :url]
    )
  end

  # ── end of generated ──
end
