defmodule ExBao.Auth.JWT do
  @moduledoc """
    The JWT/OIDC auth method.

    Generated from OpenBao's OpenAPI specification by `mix bao.gen`. One
    function per endpoint: path parameters are arguments, every other field
    is an option, and the answer is the server's own JSON body. An option
    the endpoint does not accept raises `ArgumentError` rather than being
    sent and ignored.
    
    Every function takes `:mount`, `"jwt"` by default.
  """

  use ExBao.Operation

  # ── generated by `mix bao.gen` from OpenBao 2.6.2 ──
  # Everything down to the closing marker is rewritten on every run. To
  # curate a function, move it above this block and keep its `@operation`:
  # the next run sees it there and stops generating it.

  @doc ~S"""
  Configure the JWT authentication backend.

  `POST /v1/auth/jwt/config`

  Configures the JWT authentication backend.

  ## Options

    * `:bound_issuer` (string) — The value against which to match the 'iss' claim in a JWT. Optional.
    * `:default_role` (lowercase) — The default role to use if none is provided during login. If not set, a role is required during login.
    * `:jwks_ca_pem` (string) — The CA certificate or chain of certificates, in PEM format, to use to validate connections to the JWKS URL. If not set, system certificates are used.
    * `:jwks_url` (string) — JWKS URL to use to authenticate signatures. Cannot be used with "oidc_discovery_url" or "jwt_validation_pubkeys".
    * `:jwt_supported_algs` (array) — A list of supported signing algorithms. Defaults to RS256.
    * `:jwt_validation_pubkeys` (array) — A list of PEM-encoded public keys to use to authenticate signatures locally. Cannot be used with "jwks_url" or "oidc_discovery_url".
    * `:namespace_in_state` (boolean) — Pass namespace in the OIDC state parameter instead of as a separate query parameter. With this setting, the allowed redirect URL(s) in OpenBao and on the provider side should not contain a namespace query parameter. This means only one redirect URL entry needs to be maintained on the provider side for all OpenBao namespaces that will be authenticating against it. Defaults to true for new configs.
    * `:oidc_client_id` (string) — The OAuth Client ID configured with your OIDC provider.
    * `:oidc_client_secret` (string) — The OAuth Client Secret configured with your OIDC provider.
    * `:oidc_discovery_ca_pem` (string) — The CA certificate or chain of certificates, in PEM format, to use to validate connections to the OIDC Discovery URL. If not set, system certificates are used.
    * `:oidc_discovery_url` (string) — The base URL of the OIDC Discovery URL without ".well-known/openid-configuration" component. Cannot be used with "jwks_url" or "jwt_validation_pubkeys".
    * `:oidc_response_mode` (string) — The response mode to be used in the OAuth2 request. Allowed values are 'query' and 'form_post'.
    * `:oidc_response_types` (array) — The response types to request. Allowed values are 'code' and 'id_token'. Defaults to 'code'.
    * `:override_allowed_server_names` (array) — A list of hostnames to accept when performing TLS validation, which applies both to OIDC and JWKS. This overrides default checks that expect the TLS subject to match the hostname specified in the connection URL
    * `:provider_config` (map) — Provider-specific configuration. Optional.
    * `:skip_jwks_validation` (boolean) — When true and oidc_discovery_url or jwks_url are specified, if the connection fails to load, a warning will be issued and status can be checked later by reading the config endpoint.
    * `:mount` — where the engine is mounted, `"jwt"` by default.
  """
  @operation "jwt-configure"
  @spec configure(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def configure(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "auth/#{ExBao.Operation.mount(opts, "jwt")}/config", opts,
      body: [
        :bound_issuer,
        :default_role,
        :jwks_ca_pem,
        :jwks_url,
        :jwt_supported_algs,
        :jwt_validation_pubkeys,
        :namespace_in_state,
        :oidc_client_id,
        :oidc_client_secret,
        :oidc_discovery_ca_pem,
        :oidc_discovery_url,
        :oidc_response_mode,
        :oidc_response_types,
        :override_allowed_server_names,
        :provider_config,
        :skip_jwks_validation
      ]
    )
  end

  @doc ~S"""
  Delete an existing role.

  `DELETE /v1/auth/jwt/role/{name}`

  Register an role with the backend.

  ## Arguments

    * `name` — Name of the role.

  ## Options

    * `:mount` — where the engine is mounted, `"jwt"` by default.
  """
  @operation "jwt-delete-role"
  @spec delete_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/#{ExBao.Operation.mount(opts, "jwt")}/role/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage the CEL roles that can be created with this backend.

  `DELETE /v1/auth/jwt/cel/role/{name}`

  ## Arguments

    * `name` — Name of the cel role

  ## Options

    * `:mount` — where the engine is mounted, `"jwt"` by default.
  """
  @operation "jwt-delete-role:cel"
  @spec delete_role_cel(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_role_cel(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/#{ExBao.Operation.mount(opts, "jwt")}/cel/role/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  List the existing CEL roles in this backend

  `GET /v1/auth/jwt/cel/role`

  ## Options

    * `:mount` — where the engine is mounted, `"jwt"` by default.
  """
  @operation "jwt-list-cel"
  @spec list_cel(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def list_cel(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{ExBao.Operation.mount(opts, "jwt")}/cel/role",
      opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Lists all the roles registered with the backend.

  `GET /v1/auth/jwt/role`

  ## Options

    * `:mount` — where the engine is mounted, `"jwt"` by default.
  """
  @operation "jwt-list-roles"
  @spec list_roles(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def list_roles(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "auth/#{ExBao.Operation.mount(opts, "jwt")}/role", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Authenticates to OpenBao using a JWT (or OIDC) token.

  `POST /v1/auth/jwt/login` — needs no token

  ## Options

    * `:jwt` (string) — The signed JWT to validate.
    * `:role` (lowercase) — The CEL role to log in against.
    * `:mount` — where the engine is mounted, `"jwt"` by default.
  """
  @operation "jwt-login"
  @spec login(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def login(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "auth/#{ExBao.Operation.mount(opts, "jwt")}/login", opts,
      body: [:jwt, :role]
    )
  end

  @doc ~S"""
  Authenticates to OpenBao using a JWT (or OIDC) token against a CEL role.

  `POST /v1/auth/jwt/cel/login` — needs no token

  ## Options

    * `:jwt` (string) — The signed JWT to validate.
    * `:role` (lowercase) — The CEL role to log in against.
    * `:mount` — where the engine is mounted, `"jwt"` by default.
  """
  @operation "jwt-login:cel"
  @spec login_cel(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def login_cel(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "jwt")}/cel/login",
      opts,
      body: [:jwt, :role]
    )
  end

  @doc ~S"""
  Callback endpoint to complete an OIDC login.

  `GET /v1/auth/jwt/oidc/callback` — needs no token

  ## Options

    * `:client_nonce` (string) —
    * `:code` (string) —
    * `:confirmation` (string) —
    * `:error` (string) —
    * `:error_description` (string) —
    * `:error_uri` (string) —
    * `:state` (string) —
    * `:mount` — where the engine is mounted, `"jwt"` by default.
  """
  @operation "jwt-oidc-callback"
  @spec oidc_callback(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def oidc_callback(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{ExBao.Operation.mount(opts, "jwt")}/oidc/callback",
      opts,
      query: [:client_nonce, :code, :confirmation, :error, :error_description, :error_uri, :state]
    )
  end

  @doc ~S"""
  Callback endpoint to handle form_posts.

  `POST /v1/auth/jwt/oidc/callback` — needs no token

  ## Options

    * `:id_token` (string) —
    * `:client_nonce` (string) —
    * `:code` (string) —
    * `:confirmation` (string) —
    * `:error` (string) —
    * `:error_description` (string) —
    * `:error_uri` (string) —
    * `:state` (string) —
    * `:mount` — where the engine is mounted, `"jwt"` by default.
  """
  @operation "jwt-oidc-callback-form-post"
  @spec oidc_callback_form_post(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def oidc_callback_form_post(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "jwt")}/oidc/callback",
      opts,
      body: [:id_token],
      query: [:client_nonce, :code, :confirmation, :error, :error_description, :error_uri, :state]
    )
  end

  @doc ~S"""
  Request an authorization URL to start an OIDC login flow.

  `POST /v1/auth/jwt/oidc/auth_url` — needs no token

  ## Options

    * `:client_nonce` (string) — Client-provided nonce that must match during callback, if present. Required only in direct callback mode.
    * `:redirect_uri` (string) — The OAuth redirect_uri to use in the authorization URL. Not needed with device flow.
    * `:role` (lowercase) — The role to issue an OIDC authorization URL against.
    * `:mount` — where the engine is mounted, `"jwt"` by default.
  """
  @operation "jwt-oidc-request-authorization-url"
  @spec oidc_request_authorization_url(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def oidc_request_authorization_url(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "jwt")}/oidc/auth_url",
      opts,
      body: [:client_nonce, :redirect_uri, :role]
    )
  end

  @doc ~S"""
  Manage the CEL roles that can be created with this backend.

  `PATCH /v1/auth/jwt/cel/role/{name}`

  ## Arguments

    * `name` — Name of the cel role

  ## Options

    * `:bound_audiences` (array) — Comma-separated list of 'aud' claims that are valid for login; any match is sufficient
    * `:cel_program` (map) — CEL variables and expression defining the program for the role. This is a map with two fields: 1. 'variables', a list of objects with two fields ('name' and 'expression') defining each variable and the exact execution order. 2. 'expression', the final statement to execute and whose result is returned. For example: cel_program = { "variables": [ { "name": "condition", "expression": "len(claims.groups) > 0" }, { "name": "result", "expression": "pb.Auth{Alias: claims.aud, Groups: claims.groups}" } ], "expression": "condition ? result : false" }
    * `:clock_skew_leeway` (seconds) — Duration in seconds of leeway when validating all claims to account for clock skew. Defaults to 60 (1 minute) if set to 0 and can be disabled if set to -1. Defaults to `60000000000`.
    * `:expiration_leeway` (seconds) — Duration in seconds of leeway when validating expiration of a token to account for clock skew. Defaults to 150 (2.5 minutes) if set to 0 and can be disabled if set to -1. Defaults to `150`.
    * `:message` (string) — Static error message if validation fails
    * `:not_before_leeway` (seconds) — Duration in seconds of leeway when validating not before values of a token to account for clock skew. Defaults to 150 (2.5 minutes) if set to 0 and can be disabled if set to -1. Defaults to `150`.
    * `:mount` — where the engine is mounted, `"jwt"` by default.
  """
  @operation "jwt-patch-role"
  @spec patch_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def patch_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :patch,
      "auth/#{ExBao.Operation.mount(opts, "jwt")}/cel/role/#{ExBao.Operation.escape(name)}",
      opts,
      body: [
        :bound_audiences,
        :cel_program,
        :clock_skew_leeway,
        :expiration_leeway,
        :message,
        :not_before_leeway
      ],
      content_type: "application/merge-patch+json"
    )
  end

  @doc ~S"""
  Read the current JWT authentication backend configuration.

  `GET /v1/auth/jwt/config`

  Configures the JWT authentication backend.

  ## Options

    * `:mount` — where the engine is mounted, `"jwt"` by default.
  """
  @operation "jwt-read-configuration"
  @spec read_configuration(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def read_configuration(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{ExBao.Operation.mount(opts, "jwt")}/config",
      opts,
      []
    )
  end

  @doc ~S"""
  Read an existing role.

  `GET /v1/auth/jwt/role/{name}`

  Register an role with the backend.

  ## Arguments

    * `name` — Name of the role.

  ## Options

    * `:mount` — where the engine is mounted, `"jwt"` by default.
  """
  @operation "jwt-read-role"
  @spec read_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{ExBao.Operation.mount(opts, "jwt")}/role/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage the CEL roles that can be created with this backend.

  `GET /v1/auth/jwt/cel/role/{name}`

  ## Arguments

    * `name` — Name of the cel role

  ## Options

    * `:mount` — where the engine is mounted, `"jwt"` by default.
  """
  @operation "jwt-read-role:cel"
  @spec read_role_cel(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_role_cel(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{ExBao.Operation.mount(opts, "jwt")}/cel/role/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Poll endpoint to complete an OIDC login.

  `POST /v1/auth/jwt/oidc/poll` — needs no token

  ## Options

    * `:client_nonce` (string) —
    * `:state` (string) —
    * `:mount` — where the engine is mounted, `"jwt"` by default.
  """
  @operation "jwt-write-oidc-poll"
  @spec write_oidc_poll(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def write_oidc_poll(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "jwt")}/oidc/poll",
      opts,
      body: [:client_nonce, :state]
    )
  end

  @doc ~S"""
  Register an role with the backend.

  `POST /v1/auth/jwt/role/{name}`

  ## Arguments

    * `name` — Name of the role.

  ## Options

    * `:bound_audiences` (array) — Comma-separated list of 'aud' claims that are valid for login; any match is sufficient
    * `:cel_program` (map) — CEL variables and expression defining the program for the role. This is a map with two fields: 1. 'variables', a list of objects with two fields ('name' and 'expression') defining each variable and the exact execution order. 2. 'expression', the final statement to execute and whose result is returned. For example: cel_program = { "variables": [ { "name": "condition", "expression": "len(claims.groups) > 0" }, { "name": "result", "expression": "pb.Auth{Alias: claims.aud, Groups: claims.groups}" } ], "expression": "condition ? result : false" }
    * `:clock_skew_leeway` (seconds) — Duration in seconds of leeway when validating all claims to account for clock skew. Defaults to 60 (1 minute) if set to 0 and can be disabled if set to -1. Defaults to `60000000000`.
    * `:expiration_leeway` (seconds) — Duration in seconds of leeway when validating expiration of a token to account for clock skew. Defaults to 150 (2.5 minutes) if set to 0 and can be disabled if set to -1. Defaults to `150`.
    * `:message` (string) — Static error message if validation fails
    * `:not_before_leeway` (seconds) — Duration in seconds of leeway when validating not before values of a token to account for clock skew. Defaults to 150 (2.5 minutes) if set to 0 and can be disabled if set to -1. Defaults to `150`.
    * `:mount` — where the engine is mounted, `"jwt"` by default.
  """
  @operation "jwt-write-role"
  @spec write_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "jwt")}/role/#{ExBao.Operation.escape(name)}",
      opts,
      body: [
        :bound_audiences,
        :cel_program,
        :clock_skew_leeway,
        :expiration_leeway,
        :message,
        :not_before_leeway
      ]
    )
  end

  @doc ~S"""
  Manage the CEL roles that can be created with this backend.

  `POST /v1/auth/jwt/cel/role/{name}`

  ## Arguments

    * `name` — Name of the cel role

  ## Options

    * `:bound_audiences` (array) — Comma-separated list of 'aud' claims that are valid for login; any match is sufficient
    * `:cel_program` (map) — CEL variables and expression defining the program for the role. This is a map with two fields: 1. 'variables', a list of objects with two fields ('name' and 'expression') defining each variable and the exact execution order. 2. 'expression', the final statement to execute and whose result is returned. For example: cel_program = { "variables": [ { "name": "condition", "expression": "len(claims.groups) > 0" }, { "name": "result", "expression": "pb.Auth{Alias: claims.aud, Groups: claims.groups}" } ], "expression": "condition ? result : false" }
    * `:clock_skew_leeway` (seconds) — Duration in seconds of leeway when validating all claims to account for clock skew. Defaults to 60 (1 minute) if set to 0 and can be disabled if set to -1. Defaults to `60000000000`.
    * `:expiration_leeway` (seconds) — Duration in seconds of leeway when validating expiration of a token to account for clock skew. Defaults to 150 (2.5 minutes) if set to 0 and can be disabled if set to -1. Defaults to `150`.
    * `:message` (string) — Static error message if validation fails
    * `:not_before_leeway` (seconds) — Duration in seconds of leeway when validating not before values of a token to account for clock skew. Defaults to 150 (2.5 minutes) if set to 0 and can be disabled if set to -1. Defaults to `150`.
    * `:mount` — where the engine is mounted, `"jwt"` by default.
  """
  @operation "jwt-write-role:cel"
  @spec write_role_cel(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_role_cel(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "jwt")}/cel/role/#{ExBao.Operation.escape(name)}",
      opts,
      body: [
        :bound_audiences,
        :cel_program,
        :clock_skew_leeway,
        :expiration_leeway,
        :message,
        :not_before_leeway
      ]
    )
  end

  # ── end of generated ──
end
