defmodule ExBao.Auth.Kubernetes do
  @moduledoc """
    The Kubernetes auth method.

    Generated from OpenBao's OpenAPI specification by `mix bao.gen`. One
    function per endpoint: path parameters are arguments, every other field
    is an option, and the answer is the server's own JSON body. An option
    the endpoint does not accept raises `ArgumentError` rather than being
    sent and ignored.
    
    Every function takes `:mount`, `"kubernetes"` by default.
  """

  use ExBao.Operation

  # ── generated by `mix bao.gen` from OpenBao 2.6.2 ──
  # Everything down to the closing marker is rewritten on every run. To
  # curate a function, move it above this block and keep its `@operation`:
  # the next run sees it there and stops generating it.

  @doc ~S"""
  Configures the JWT Public Key and Kubernetes API information.

  `POST /v1/auth/kubernetes/config`

  ## Options

    * `:disable_iss_validation` (boolean, deprecated) — Disable JWT issuer validation (Deprecated, will be removed in a future release) Defaults to `true`.
    * `:disable_local_ca_jwt` (boolean) — Disable defaulting to the local CA cert and service account JWT when running in a Kubernetes pod Defaults to `false`.
    * `:issuer` (string, deprecated) — Optional JWT issuer. If no issuer is specified, then this plugin will use kubernetes.io/serviceaccount as the default issuer. (Deprecated, will be removed in a future release)
    * `:kubernetes_ca_cert` (string) — PEM encoded CA cert for use by the TLS client used to talk with the API.
    * `:kubernetes_host` (string) — Host must be a host string, a host:port pair, or a URL to the base of the Kubernetes API server.
    * `:pem_keys` (array) — Optional list of PEM-formated public keys or certificates used to verify the signatures of kubernetes service account JWTs. If a certificate is given, its public key will be extracted. Not every installation of Kubernetes exposes these keys.
    * `:token_reviewer_jwt` (string) — A service account JWT (or other token) used as a bearer token to access the TokenReview API to validate other JWTs during login. If not set the JWT used for login will be used to access the API.
    * `:mount` — where the engine is mounted, `"kubernetes"` by default.
  """
  @operation "kubernetes-configure-auth"
  @spec configure_auth(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def configure_auth(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "kubernetes")}/config",
      opts,
      body: [
        :disable_iss_validation,
        :disable_local_ca_jwt,
        :issuer,
        :kubernetes_ca_cert,
        :kubernetes_host,
        :pem_keys,
        :token_reviewer_jwt
      ]
    )
  end

  @doc ~S"""
  Register an role with the backend.

  `DELETE /v1/auth/kubernetes/role/{name}`

  ## Arguments

    * `name` — Name of the role.

  ## Options

    * `:mount` — where the engine is mounted, `"kubernetes"` by default.
  """
  @operation "kubernetes-delete-auth-role"
  @spec delete_auth_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_auth_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/#{ExBao.Operation.mount(opts, "kubernetes")}/role/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Lists all the roles registered with the backend.

  `GET /v1/auth/kubernetes/role`

  ## Options

    * `:mount` — where the engine is mounted, `"kubernetes"` by default.
  """
  @operation "kubernetes-list-auth-roles"
  @spec list_auth_roles(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def list_auth_roles(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{ExBao.Operation.mount(opts, "kubernetes")}/role",
      opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Authenticates Kubernetes service accounts with OpenBao.

  `POST /v1/auth/kubernetes/login` — needs no token

  ## Options

    * `:jwt` (string) — A signed JWT for authenticating a service account. This field is required.
    * `:role` (string) — Name of the role against which the login is being attempted. This field is required
    * `:mount` — where the engine is mounted, `"kubernetes"` by default.
  """
  @operation "kubernetes-login"
  @spec login(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def login(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "kubernetes")}/login",
      opts,
      body: [:jwt, :role]
    )
  end

  @doc ~S"""
  Configures the JWT Public Key and Kubernetes API information.

  `GET /v1/auth/kubernetes/config`

  ## Options

    * `:mount` — where the engine is mounted, `"kubernetes"` by default.
  """
  @operation "kubernetes-read-auth-configuration"
  @spec read_auth_configuration(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def read_auth_configuration(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{ExBao.Operation.mount(opts, "kubernetes")}/config",
      opts,
      []
    )
  end

  @doc ~S"""
  Register an role with the backend.

  `GET /v1/auth/kubernetes/role/{name}`

  ## Arguments

    * `name` — Name of the role.

  ## Options

    * `:mount` — where the engine is mounted, `"kubernetes"` by default.
  """
  @operation "kubernetes-read-auth-role"
  @spec read_auth_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_auth_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{ExBao.Operation.mount(opts, "kubernetes")}/role/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Register an role with the backend.

  `POST /v1/auth/kubernetes/role/{name}`

  ## Arguments

    * `name` — Name of the role.

  ## Options

    * `:alias_name_source` (string) — Source to use when deriving the Alias name. valid choices: "serviceaccount_uid" : <token.uid> e.g. 474b11b5-0f20-4f9d-8ca5-65715ab325e0 (most secure choice) "serviceaccount_name" : <namespace>/<serviceaccount> e.g. vault/vault-agent default: "serviceaccount_uid" Defaults to `"serviceaccount_uid"`.
    * `:audience` (string) — Optional Audience claim to verify in the jwt.
    * `:bound_cidrs` (array, deprecated) — Use "token_bound_cidrs" instead. If this and "token_bound_cidrs" are both specified, only "token_bound_cidrs" will be used.
    * `:bound_service_account_names` (array) — List of service account names able to access this role. If set to "*" all names are allowed.
    * `:bound_service_account_namespace_selector` (string) — A label selector for Kubernetes namespaces which are allowed to access this role. Accepts either a JSON or YAML object. If set with bound_service_account_namespaces, the conditions are ORed.
    * `:bound_service_account_namespaces` (array) — List of namespaces allowed to access this role. If set to "*" all namespaces are allowed.
    * `:max_ttl` (seconds, deprecated) — Use "token_max_ttl" instead. If this and "token_max_ttl" are both specified, only "token_max_ttl" will be used.
    * `:num_uses` (integer, deprecated) — Use "token_num_uses" instead. If this and "token_num_uses" are both specified, only "token_num_uses" will be used.
    * `:period` (seconds, deprecated) — Use "token_period" instead. If this and "token_period" are both specified, only "token_period" will be used.
    * `:policies` (array, deprecated) — Use "token_policies" instead. If this and "token_policies" are both specified, only "token_policies" will be used.
    * `:token_bound_cidrs` (array) — Comma separated string or JSON list of CIDR blocks. If set, specifies the blocks of IP addresses which are allowed to use the generated token.
    * `:token_explicit_max_ttl` (seconds) — If set, tokens created via this role carry an explicit maximum TTL. During renewal, the current maximum TTL values of the role and the mount are not checked for changes, and any updates to these values will have no effect on the token being renewed.
    * `:token_max_ttl` (seconds) — The maximum lifetime of the generated token
    * `:token_no_default_policy` (boolean) — If true, the 'default' policy will not automatically be added to generated tokens
    * `:token_num_uses` (integer) — The maximum number of times a token may be used, a value of zero means unlimited
    * `:token_period` (seconds) — If set, tokens created via this role will have no max lifetime; instead, their renewal period will be fixed to this value. This takes an integer number of seconds, or a string duration (e.g. "24h").
    * `:token_policies` (array) — Comma-separated list of policies
    * `:token_strictly_bind_ip` (boolean) — If true, CIDRs for the token will be strictly bound to the source IP address of the login request
    * `:token_ttl` (seconds) — The initial ttl of the token to generate
    * `:token_type` (string) — The type of token to generate, service or batch Defaults to `"default-service"`.
    * `:ttl` (seconds, deprecated) — Use "token_ttl" instead. If this and "token_ttl" are both specified, only "token_ttl" will be used.
    * `:mount` — where the engine is mounted, `"kubernetes"` by default.
  """
  @operation "kubernetes-write-auth-role"
  @spec write_auth_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_auth_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "kubernetes")}/role/#{ExBao.Operation.escape(name)}",
      opts,
      body: [
        :alias_name_source,
        :audience,
        :bound_cidrs,
        :bound_service_account_names,
        :bound_service_account_namespace_selector,
        :bound_service_account_namespaces,
        :max_ttl,
        :num_uses,
        :period,
        :policies,
        :token_bound_cidrs,
        :token_explicit_max_ttl,
        :token_max_ttl,
        :token_no_default_policy,
        :token_num_uses,
        :token_period,
        :token_policies,
        :token_strictly_bind_ip,
        :token_ttl,
        :token_type,
        :ttl
      ]
    )
  end

  # ── end of generated ──
end
