defmodule ExBao.Auth.LDAP do
  @moduledoc """
    The LDAP auth method.

    Generated from OpenBao's OpenAPI specification by `mix bao.gen`. One
    function per endpoint: path parameters are arguments, every other field
    is an option, and the answer is the server's own JSON body. An option
    the endpoint does not accept raises `ArgumentError` rather than being
    sent and ignored.
    
    Every function takes `:mount`, `"ldap"` by default.
  """

  use ExBao.Operation

  # ── generated by `mix bao.gen` from OpenBao 2.6.2 ──
  # Everything down to the closing marker is rewritten on every run. To
  # curate a function, move it above this block and keep its `@operation`:
  # the next run sees it there and stops generating it.

  @doc ~S"""
  Configure the LDAP server to connect to, along with its options.

  `POST /v1/auth/ldap/config`

  ## Options

    * `:anonymous_group_search` (boolean) — Use anonymous binds when performing LDAP group searches (if true the initial credentials will still be used for the initial connection test). Defaults to `false`.
    * `:binddn` (string) — LDAP DN for searching for the user DN (optional)
    * `:bindpass` (string) — LDAP password for searching for the user DN (optional)
    * `:case_sensitive_names` (boolean) — If true, case sensitivity will be used when comparing usernames and groups for matching policies.
    * `:certificate` (string) — CA certificate to use when verifying LDAP server certificate, must be x509 PEM encoded (optional)
    * `:client_tls_cert` (string) — Client certificate to provide to the LDAP server, must be x509 PEM encoded (optional)
    * `:client_tls_key` (string) — Client certificate key to provide to the LDAP server, must be x509 PEM encoded (optional)
    * `:connection_timeout` (seconds) — Timeout, in seconds, when attempting to connect to the LDAP server before trying the next URL in the configuration. Defaults to `"30s"`.
    * `:deny_null_bind` (boolean) — Denies an unauthenticated LDAP bind request if the user's password is empty; defaults to true Defaults to `true`.
    * `:dereference_aliases` (string) — When aliases should be dereferenced on search operations. Accepted values are 'never', 'finding', 'searching', 'always'. Defaults to 'never'. Defaults to `"never"`.
    * `:discoverdn` (boolean) — Use anonymous bind to discover the bind DN of a user (optional)
    * `:groupattr` (string) — LDAP attribute to follow on objects returned by <groupfilter> in order to enumerate user group membership. Examples: "cn" or "memberOf", etc. Default: cn Defaults to `"cn"`.
    * `:groupdn` (string) — LDAP search base to use for group membership search (eg: ou=Groups,dc=example,dc=org)
    * `:groupfilter` (string) — Go template for querying group membership of user (optional) The template can access the following context variables: UserDN, Username Example: (&(objectClass=group)(member:1.2.840.113556.1.4.1941:={{.UserDN}})) Default: (|(memberUid={{.Username}})(member={{.UserDN}})(uniqueMember={{.UserDN}})) Defaults to `"(|(memberUid={{.Username}})(member={{.UserDN}})(uniqueMember={{.UserDN}}))"`.
    * `:insecure_tls` (boolean) — Skip LDAP server SSL Certificate verification - VERY insecure (optional)
    * `:max_page_size` (integer) — If set to a value greater than 0, the LDAP backend will use the LDAP server's paged search control to request pages of up to the given size. This can be used to avoid hitting the LDAP server's maximum result size limit. Otherwise, the LDAP backend will not use the paged search control. Defaults to `0`.
    * `:request_timeout` (seconds) — Timeout, in seconds, for the connection when making requests against the server before returning back an error. Defaults to `"90s"`.
    * `:starttls` (boolean) — Issue a StartTLS command after establishing unencrypted connection (optional)
    * `:tls_max_version` (string) — Maximum TLS version to use. Accepted values are 'tls10', 'tls11', 'tls12' or 'tls13'. Defaults to 'tls12' Defaults to `"tls12"`.
    * `:tls_min_version` (string) — Minimum TLS version to use. Accepted values are 'tls10', 'tls11', 'tls12' or 'tls13'. Defaults to 'tls12' Defaults to `"tls12"`.
    * `:token_bound_cidrs` (array) — Comma separated string or JSON list of CIDR blocks. If set, specifies the blocks of IP addresses which are allowed to use the generated token.
    * `:token_explicit_max_ttl` (seconds) — If set, tokens created via this role carry an explicit maximum TTL. During renewal, the current maximum TTL values of the role and the mount are not checked for changes, and any updates to these values will have no effect on the token being renewed.
    * `:token_max_ttl` (seconds) — The maximum lifetime of the generated token
    * `:token_no_default_policy` (boolean) — If true, the 'default' policy will not automatically be added to generated tokens
    * `:token_num_uses` (integer) — The maximum number of times a token may be used, a value of zero means unlimited
    * `:token_period` (seconds) — If set, tokens created via this role will have no max lifetime; instead, their renewal period will be fixed to this value. This takes an integer number of seconds, or a string duration (e.g. "24h").
    * `:token_policies` (array) — Comma-separated list of policies. This will apply to all tokens generated by this auth method, in addition to any configured for specific users/groups.
    * `:token_strictly_bind_ip` (boolean) — If true, CIDRs for the token will be strictly bound to the source IP address of the login request
    * `:token_ttl` (seconds) — The initial ttl of the token to generate
    * `:token_type` (string) — The type of token to generate, service or batch Defaults to `"default-service"`.
    * `:upndomain` (string) — Enables userPrincipalDomain login with [username]@UPNDomain (optional)
    * `:url` (string) — LDAP URL to connect to (default: ldap://127.0.0.1). Multiple URLs can be specified by concatenating them with commas; they will be tried in-order. Defaults to `"ldap://127.0.0.1"`.
    * `:use_pre111_group_cn_behavior` (boolean) — In Vault 1.1.1 (prior to OpenBao's fork), a fix for handling group CN values of different cases unfortunately introduced a regression that could cause previously defined groups to not be found due to a change in the resulting name. If set true, the pre-1.1.1 behavior for matching group CNs will be used. This is only needed in some upgrade scenarios for backwards compatibility. It is enabled by default if the config is upgraded but disabled by default on new configurations.
    * `:use_token_groups` (boolean) — If true, use the Active Directory tokenGroups constructed attribute of the user to find the group memberships. This will find all security groups including nested ones. Defaults to `false`.
    * `:userattr` (string) — Attribute used for users (default: cn) Defaults to `"cn"`.
    * `:userdn` (string) — LDAP domain to use for users (eg: ou=People,dc=example,dc=org)
    * `:userfilter` (string) — Go template for LDAP user search filer (optional) The template can access the following context variables: UserAttr, Username Default: ({{.UserAttr}}={{.Username}}) Defaults to `"({{.UserAttr}}={{.Username}})"`.
    * `:username_as_alias` (boolean) — If true, sets the alias name to the username Defaults to `false`.
    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-configure-auth"
  @spec configure_auth(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def configure_auth(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "ldap")}/config",
      opts,
      body: [
        :anonymous_group_search,
        :binddn,
        :bindpass,
        :case_sensitive_names,
        :certificate,
        :client_tls_cert,
        :client_tls_key,
        :connection_timeout,
        :deny_null_bind,
        :dereference_aliases,
        :discoverdn,
        :groupattr,
        :groupdn,
        :groupfilter,
        :insecure_tls,
        :max_page_size,
        :request_timeout,
        :starttls,
        :tls_max_version,
        :tls_min_version,
        :token_bound_cidrs,
        :token_explicit_max_ttl,
        :token_max_ttl,
        :token_no_default_policy,
        :token_num_uses,
        :token_period,
        :token_policies,
        :token_strictly_bind_ip,
        :token_ttl,
        :token_type,
        :upndomain,
        :url,
        :use_pre111_group_cn_behavior,
        :use_token_groups,
        :userattr,
        :userdn,
        :userfilter,
        :username_as_alias
      ]
    )
  end

  @doc ~S"""
  Manage additional groups for users allowed to authenticate.

  `DELETE /v1/auth/ldap/groups/{name}`

  ## Arguments

    * `name` — Name of the LDAP group.

  ## Options

    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-delete-group"
  @spec delete_group(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_group(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/#{ExBao.Operation.mount(opts, "ldap")}/groups/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage users allowed to authenticate.

  `DELETE /v1/auth/ldap/users/{name}`

  ## Arguments

    * `name` — Name of the LDAP user.

  ## Options

    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-delete-user"
  @spec delete_user(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_user(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/#{ExBao.Operation.mount(opts, "ldap")}/users/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage additional groups for users allowed to authenticate.

  `GET /v1/auth/ldap/groups`

  ## Options

    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-list-groups"
  @spec list_groups(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def list_groups(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "auth/#{ExBao.Operation.mount(opts, "ldap")}/groups", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Manage users allowed to authenticate.

  `GET /v1/auth/ldap/users`

  ## Options

    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-list-users"
  @spec list_users(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def list_users(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "auth/#{ExBao.Operation.mount(opts, "ldap")}/users", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Log in with a username and password.

  `POST /v1/auth/ldap/login/{username}` — needs no token

  ## Arguments

    * `username` — DN (distinguished name) to be used for login.

  ## Options

    * `:password` (string) — Password for this user.
    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-login"
  @spec login(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def login(server, username, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "ldap")}/login/#{ExBao.Operation.escape(username)}",
      opts,
      body: [:password]
    )
  end

  @doc ~S"""
  Configure the LDAP server to connect to, along with its options.

  `GET /v1/auth/ldap/config`

  ## Options

    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-read-auth-configuration"
  @spec read_auth_configuration(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def read_auth_configuration(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{ExBao.Operation.mount(opts, "ldap")}/config",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage additional groups for users allowed to authenticate.

  `GET /v1/auth/ldap/groups/{name}`

  ## Arguments

    * `name` — Name of the LDAP group.

  ## Options

    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-read-group"
  @spec read_group(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_group(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{ExBao.Operation.mount(opts, "ldap")}/groups/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage users allowed to authenticate.

  `GET /v1/auth/ldap/users/{name}`

  ## Arguments

    * `name` — Name of the LDAP user.

  ## Options

    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-read-user"
  @spec read_user(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_user(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{ExBao.Operation.mount(opts, "ldap")}/users/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage additional groups for users allowed to authenticate.

  `POST /v1/auth/ldap/groups/{name}`

  ## Arguments

    * `name` — Name of the LDAP group.

  ## Options

    * `:policies` (array) — Comma-separated list of policies associated to the group.
    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-write-group"
  @spec write_group(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_group(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "ldap")}/groups/#{ExBao.Operation.escape(name)}",
      opts,
      body: [:policies]
    )
  end

  @doc ~S"""
  Manage users allowed to authenticate.

  `POST /v1/auth/ldap/users/{name}`

  ## Arguments

    * `name` — Name of the LDAP user.

  ## Options

    * `:groups` (array) — Comma-separated list of additional groups associated with the user.
    * `:policies` (array) — Comma-separated list of policies associated with the user.
    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-write-user"
  @spec write_user(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_user(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "ldap")}/users/#{ExBao.Operation.escape(name)}",
      opts,
      body: [:groups, :policies]
    )
  end

  # ── end of generated ──
end
