defmodule ExBao.Auth.Radius do
  @moduledoc """
    The RADIUS auth method.

    Generated from OpenBao's OpenAPI specification by `mix bao.gen`. One
    function per endpoint: path parameters are arguments, every other field
    is an option, and the answer is the server's own JSON body. An option
    the endpoint does not accept raises `ArgumentError` rather than being
    sent and ignored.
    
    Every function takes `:mount`, `"radius"` by default.
  """

  use ExBao.Operation

  # ── generated by `mix bao.gen` from OpenBao 2.6.2 ──
  # Everything down to the closing marker is rewritten on every run. To
  # curate a function, move it above this block and keep its `@operation`:
  # the next run sees it there and stops generating it.

  @doc ~S"""
  Configure the RADIUS server to connect to, along with its options.

  `POST /v1/auth/radius/config`

  ## Options

    * `:dial_timeout` (seconds) — Number of seconds before connect times out (default: 10) Defaults to `10`.
    * `:host` (string) — RADIUS server host
    * `:nas_identifier` (string) — RADIUS NAS Identifier field (optional) Defaults to `""`.
    * `:nas_port` (integer) — RADIUS NAS port field (default: 10) Defaults to `10`.
    * `:port` (integer) — RADIUS server port (default: 1812) Defaults to `1812`.
    * `:read_timeout` (seconds) — Number of seconds before response times out (default: 10) Defaults to `10`.
    * `:secret` (string) — Secret shared with the RADIUS server
    * `:token_bound_cidrs` (array) — Comma separated string or JSON list of CIDR blocks. If set, specifies the blocks of IP addresses which are allowed to use the generated token.
    * `:token_explicit_max_ttl` (seconds) — If set, tokens created via this role carry an explicit maximum TTL. During renewal, the current maximum TTL values of the role and the mount are not checked for changes, and any updates to these values will have no effect on the token being renewed.
    * `:token_max_ttl` (seconds) — The maximum lifetime of the generated token
    * `:token_no_default_policy` (boolean) — If true, the 'default' policy will not automatically be added to generated tokens
    * `:token_num_uses` (integer) — The maximum number of times a token may be used, a value of zero means unlimited
    * `:token_period` (seconds) — If set, tokens created via this role will have no max lifetime; instead, their renewal period will be fixed to this value. This takes an integer number of seconds, or a string duration (e.g. "24h").
    * `:token_policies` (array) — Comma-separated list of policies. This will apply to all tokens generated by this auth method, in addition to any configured for specific users.
    * `:token_strictly_bind_ip` (boolean) — If true, CIDRs for the token will be strictly bound to the source IP address of the login request
    * `:token_ttl` (seconds) — The initial ttl of the token to generate
    * `:token_type` (string) — The type of token to generate, service or batch Defaults to `"default-service"`.
    * `:unregistered_user_policies` (string) — Comma-separated list of policies to grant upon successful RADIUS authentication of an unregistered user (default: empty) Defaults to `""`.
    * `:mount` — where the engine is mounted, `"radius"` by default.
  """
  @operation "radius-configure"
  @spec configure(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def configure(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "radius")}/config",
      opts,
      body: [
        :dial_timeout,
        :host,
        :nas_identifier,
        :nas_port,
        :port,
        :read_timeout,
        :secret,
        :token_bound_cidrs,
        :token_explicit_max_ttl,
        :token_max_ttl,
        :token_no_default_policy,
        :token_num_uses,
        :token_period,
        :token_policies,
        :token_strictly_bind_ip,
        :token_ttl,
        :token_type,
        :unregistered_user_policies
      ]
    )
  end

  @doc ~S"""
  Manage users allowed to authenticate.

  `DELETE /v1/auth/radius/users/{name}`

  ## Arguments

    * `name` — Name of the RADIUS user.

  ## Options

    * `:mount` — where the engine is mounted, `"radius"` by default.
  """
  @operation "radius-delete-user"
  @spec delete_user(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_user(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/#{ExBao.Operation.mount(opts, "radius")}/users/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage users allowed to authenticate.

  `GET /v1/auth/radius/users`

  ## Options

    * `:mount` — where the engine is mounted, `"radius"` by default.
  """
  @operation "radius-list-users"
  @spec list_users(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def list_users(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{ExBao.Operation.mount(opts, "radius")}/users",
      opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Log in with a username and password.

  `POST /v1/auth/radius/login` — needs no token

  ## Options

    * `:password` (string) — Password for this user.
    * `:urlusername` (string) — Username to be used for login. (URL parameter)
    * `:username` (string) — Username to be used for login. (POST request body)
    * `:mount` — where the engine is mounted, `"radius"` by default.
  """
  @operation "radius-login"
  @spec login(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def login(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "radius")}/login",
      opts,
      body: [:password, :urlusername, :username]
    )
  end

  @doc ~S"""
  Log in with a username and password.

  `POST /v1/auth/radius/login/{urlusername}` — needs no token

  ## Arguments

    * `urlusername` — Username to be used for login. (URL parameter)

  ## Options

    * `:password` (string) — Password for this user.
    * `:username` (string) — Username to be used for login. (POST request body)
    * `:mount` — where the engine is mounted, `"radius"` by default.
  """
  @operation "radius-login-with-username"
  @spec login_with_username(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def login_with_username(server, urlusername, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "radius")}/login/#{ExBao.Operation.escape(urlusername)}",
      opts,
      body: [:password, :username]
    )
  end

  @doc ~S"""
  Configure the RADIUS server to connect to, along with its options.

  `GET /v1/auth/radius/config`

  ## Options

    * `:mount` — where the engine is mounted, `"radius"` by default.
  """
  @operation "radius-read-configuration"
  @spec read_configuration(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def read_configuration(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{ExBao.Operation.mount(opts, "radius")}/config",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage users allowed to authenticate.

  `GET /v1/auth/radius/users/{name}`

  ## Arguments

    * `name` — Name of the RADIUS user.

  ## Options

    * `:mount` — where the engine is mounted, `"radius"` by default.
  """
  @operation "radius-read-user"
  @spec read_user(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_user(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{ExBao.Operation.mount(opts, "radius")}/users/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage users allowed to authenticate.

  `POST /v1/auth/radius/users/{name}`

  ## Arguments

    * `name` — Name of the RADIUS user.

  ## Options

    * `:policies` (array) — Comma-separated list of policies associated to the user.
    * `:mount` — where the engine is mounted, `"radius"` by default.
  """
  @operation "radius-write-user"
  @spec write_user(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_user(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "radius")}/users/#{ExBao.Operation.escape(name)}",
      opts,
      body: [:policies]
    )
  end

  # ── end of generated ──
end
