defmodule ExBao.Auth.Token do
  @moduledoc """
  The token auth method.

  Generated from OpenBao's OpenAPI specification by `mix bao.gen`. One
  function per endpoint: path parameters are arguments, every other field
  is an option, and the answer is the server's own JSON body. An option
  the endpoint does not accept raises `ArgumentError` rather than being
  sent and ignored.
  """

  use ExBao.Operation

  # ── generated by `mix bao.gen` from OpenBao 2.6.2 ──
  # Everything down to the closing marker is rewritten on every run. To
  # curate a function, move it above this block and keep its `@operation`:
  # the next run sees it there and stops generating it.

  @doc ~S"""
  The token create path is used to create new tokens.

  `POST /v1/auth/token/create`

  ## Options

    * `:display_name` (string) — Name to associate with this token
    * `:entity_alias` (string) — Name of the entity alias to associate with this token
    * `:explicit_max_ttl` (string) — Explicit Max TTL of this token
    * `:id` (string) — Value for the token
    * `:lease` (string, deprecated) — Use 'ttl' instead
    * `:meta` (kvpairs) — Arbitrary key=value metadata to associate with the token
    * `:no_default_policy` (boolean) — Do not include default policy for this token
    * `:no_parent` (boolean) — Create the token with no parent
    * `:num_uses` (integer) — Max number of uses for this token
    * `:period` (string) — Renew period
    * `:policies` (array) — List of policies for the token
    * `:renewable` (boolean) — Allow token to be renewed past its initial TTL up to system/mount maximum TTL Defaults to `true`.
    * `:ttl` (string) — Time to live for this token
    * `:type` (string) — Token type
  """
  @operation "token-create"
  @spec create(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def create(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "auth/token/create", opts,
      body: [
        :display_name,
        :entity_alias,
        :explicit_max_ttl,
        :id,
        :lease,
        :meta,
        :no_default_policy,
        :no_parent,
        :num_uses,
        :period,
        :policies,
        :renewable,
        :ttl,
        :type
      ]
    )
  end

  @doc ~S"""
  This token create path is used to create new tokens adhering to the given role.

  `POST /v1/auth/token/create/{role_name}`

  ## Arguments

    * `role_name` — Name of the role

  ## Options

    * `:display_name` (string) — Name to associate with this token
    * `:entity_alias` (string) — Name of the entity alias to associate with this token
    * `:explicit_max_ttl` (string) — Explicit Max TTL of this token
    * `:id` (string) — Value for the token
    * `:lease` (string, deprecated) — Use 'ttl' instead
    * `:meta` (kvpairs) — Arbitrary key=value metadata to associate with the token
    * `:no_default_policy` (boolean) — Do not include default policy for this token
    * `:no_parent` (boolean) — Create the token with no parent
    * `:num_uses` (integer) — Max number of uses for this token
    * `:period` (string) — Renew period
    * `:policies` (array) — List of policies for the token
    * `:renewable` (boolean) — Allow token to be renewed past its initial TTL up to system/mount maximum TTL Defaults to `true`.
    * `:ttl` (string) — Time to live for this token
    * `:type` (string) — Token type
  """
  @operation "token-create-against-role"
  @spec create_against_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def create_against_role(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/token/create/#{ExBao.Operation.escape(role_name)}",
      opts,
      body: [
        :display_name,
        :entity_alias,
        :explicit_max_ttl,
        :id,
        :lease,
        :meta,
        :no_default_policy,
        :no_parent,
        :num_uses,
        :period,
        :policies,
        :renewable,
        :ttl,
        :type
      ]
    )
  end

  @doc ~S"""
  The token create path is used to create new orphan tokens.

  `POST /v1/auth/token/create-orphan`

  ## Options

    * `:display_name` (string) — Name to associate with this token
    * `:entity_alias` (string) — Name of the entity alias to associate with this token
    * `:explicit_max_ttl` (string) — Explicit Max TTL of this token
    * `:id` (string) — Value for the token
    * `:lease` (string, deprecated) — Use 'ttl' instead
    * `:meta` (kvpairs) — Arbitrary key=value metadata to associate with the token
    * `:no_default_policy` (boolean) — Do not include default policy for this token
    * `:no_parent` (boolean) — Create the token with no parent
    * `:num_uses` (integer) — Max number of uses for this token
    * `:period` (string) — Renew period
    * `:policies` (array) — List of policies for the token
    * `:renewable` (boolean) — Allow token to be renewed past its initial TTL up to system/mount maximum TTL Defaults to `true`.
    * `:ttl` (string) — Time to live for this token
    * `:type` (string) — Token type
  """
  @operation "token-create-orphan"
  @spec create_orphan(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def create_orphan(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "auth/token/create-orphan", opts,
      body: [
        :display_name,
        :entity_alias,
        :explicit_max_ttl,
        :id,
        :lease,
        :meta,
        :no_default_policy,
        :no_parent,
        :num_uses,
        :period,
        :policies,
        :renewable,
        :ttl,
        :type
      ]
    )
  end

  @doc ~S"""
  `token-delete-role`

  `DELETE /v1/auth/token/roles/{role_name}`

  ## Arguments

    * `role_name` — Name of the role
  """
  @operation "token-delete-role"
  @spec delete_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_role(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/token/roles/#{ExBao.Operation.escape(role_name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  List token accessors, which can then be be used to iterate and discover their properties or revoke them. Because this can be used to cause a denial of service, this endpoint requires 'sudo' capability in addition to 'list'.

  `GET /v1/auth/token/accessors` — needs `sudo`
  """
  @operation "token-list-accessors"
  @spec list_accessors(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def list_accessors(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "auth/token/accessors", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  This endpoint lists configured roles.

  `GET /v1/auth/token/roles`
  """
  @operation "token-list-roles"
  @spec list_roles(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def list_roles(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "auth/token/roles", opts, fixed_query: %{"list" => "true"})
  end

  @doc ~S"""
  This endpoint will lookup a token associated with the given accessor and its properties. Response will not contain the token ID.

  `POST /v1/auth/token/lookup-accessor`

  ## Options

    * `:accessor` (string) — Accessor of the token to look up (request body)
  """
  @operation "token-look-up-by-accessor"
  @spec look_up_by_accessor(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def look_up_by_accessor(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "auth/token/lookup-accessor", opts, body: [:accessor])
  end

  @doc ~S"""
  This endpoint will lookup a token and its properties.

  `GET /v1/auth/token/lookup`
  """
  @operation "token-look-up-get"
  @spec look_up_get(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def look_up_get(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "auth/token/lookup", opts, [])
  end

  @doc ~S"""
  This endpoint will lookup a token and its properties.

  `GET /v1/auth/token/lookup-self`
  """
  @operation "token-look-up-self-get"
  @spec look_up_self_get(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def look_up_self_get(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "auth/token/lookup-self", opts, [])
  end

  @doc ~S"""
  This endpoint will lookup a token and its properties.

  `POST /v1/auth/token/lookup-self`

  ## Options

    * `:token` (string) — Token to look up (unused, does not need to be set)
  """
  @operation "token-look-up-self-update"
  @spec look_up_self_update(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def look_up_self_update(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "auth/token/lookup-self", opts, body: [:token])
  end

  @doc ~S"""
  This endpoint will lookup a token and its properties.

  `POST /v1/auth/token/lookup`

  ## Options

    * `:token` (string) — Token to lookup (POST request body)
  """
  @operation "token-look-up-update"
  @spec look_up_update(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def look_up_update(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "auth/token/lookup", opts, body: [:token])
  end

  @doc ~S"""
  `token-read-role`

  `GET /v1/auth/token/roles/{role_name}`

  ## Arguments

    * `role_name` — Name of the role
  """
  @operation "token-read-role"
  @spec read_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_role(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/token/roles/#{ExBao.Operation.escape(role_name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  This endpoint will renew the given token and prevent expiration.

  `POST /v1/auth/token/renew`

  ## Options

    * `:increment` (seconds) — The desired increment in seconds to the token expiration Defaults to `0`.
    * `:token` (string) — Token to renew (request body)
  """
  @operation "token-renew"
  @spec renew(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def renew(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "auth/token/renew", opts, body: [:increment, :token])
  end

  @doc ~S"""
  This endpoint will renew a token associated with the given accessor and its properties. Response will not contain the token ID.

  `POST /v1/auth/token/renew-accessor`

  ## Options

    * `:accessor` (string) — Accessor of the token to renew (request body)
    * `:increment` (seconds) — The desired increment in seconds to the token expiration Defaults to `0`.
  """
  @operation "token-renew-accessor"
  @spec renew_accessor(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def renew_accessor(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "auth/token/renew-accessor", opts,
      body: [:accessor, :increment]
    )
  end

  @doc ~S"""
  This endpoint will renew the token used to call it and prevent expiration.

  `POST /v1/auth/token/renew-self`

  ## Options

    * `:increment` (seconds) — The desired increment in seconds to the token expiration Defaults to `0`.
    * `:token` (string) — Token to renew (unused, does not need to be set)
  """
  @operation "token-renew-self"
  @spec renew_self(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def renew_self(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "auth/token/renew-self", opts, body: [:increment, :token])
  end

  @doc ~S"""
  This endpoint will delete the given token and all of its child tokens.

  `POST /v1/auth/token/revoke`

  ## Options

    * `:token` (string) — Token to revoke (request body)
  """
  @operation "token-revoke"
  @spec revoke(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def revoke(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "auth/token/revoke", opts, body: [:token])
  end

  @doc ~S"""
  This endpoint will delete the token associated with the accessor and all of its child tokens.

  `POST /v1/auth/token/revoke-accessor`

  ## Options

    * `:accessor` (string) — Accessor of the token (request body)
  """
  @operation "token-revoke-accessor"
  @spec revoke_accessor(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def revoke_accessor(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "auth/token/revoke-accessor", opts, body: [:accessor])
  end

  @doc ~S"""
  This endpoint will delete the token and orphan its child tokens.

  `POST /v1/auth/token/revoke-orphan`

  ## Options

    * `:token` (string) — Token to revoke (request body)
  """
  @operation "token-revoke-orphan"
  @spec revoke_orphan(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def revoke_orphan(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "auth/token/revoke-orphan", opts, body: [:token])
  end

  @doc ~S"""
  This endpoint will delete the token used to call it and all of its child tokens.

  `POST /v1/auth/token/revoke-self`
  """
  @operation "token-revoke-self"
  @spec revoke_self(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def revoke_self(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "auth/token/revoke-self", opts, [])
  end

  @doc ~S"""
  This endpoint performs cleanup tasks that can be run if certain error conditions have occurred.

  `POST /v1/auth/token/tidy`
  """
  @operation "token-tidy"
  @spec tidy(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def tidy(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "auth/token/tidy", opts, [])
  end

  @doc ~S"""
  `token-write-role`

  `POST /v1/auth/token/roles/{role_name}`

  ## Arguments

    * `role_name` — Name of the role

  ## Options

    * `:allowed_entity_aliases` (array) — String or JSON list of allowed entity aliases. If set, specifies the entity aliases which are allowed to be used during token generation. This field supports globbing.
    * `:allowed_policies` (array) — If set, tokens can be created with any subset of the policies in this list, rather than the normal semantics of tokens being a subset of the calling token's policies. The parameter is a comma-delimited string of policy names.
    * `:allowed_policies_glob` (array) — If set, tokens can be created with any subset of glob matched policies in this list, rather than the normal semantics of tokens being a subset of the calling token's policies. The parameter is a comma-delimited string of policy name globs.
    * `:bound_cidrs` (array, deprecated) — Use 'token_bound_cidrs' instead.
    * `:disallowed_policies` (array) — If set, successful token creation via this role will require that no policies in the given list are requested. The parameter is a comma-delimited string of policy names.
    * `:disallowed_policies_glob` (array) — If set, successful token creation via this role will require that no requested policies glob match any of policies in this list. The parameter is a comma-delimited string of policy name globs.
    * `:explicit_max_ttl` (seconds, deprecated) — Use 'token_explicit_max_ttl' instead.
    * `:orphan` (boolean) — If true, tokens created via this role will be orphan tokens (have no parent)
    * `:path_suffix` (string) — If set, tokens created via this role will contain the given suffix as a part of their path. This can be used to assist use of the 'revoke-prefix' endpoint later on. The given suffix must match the regular expression.\w[\w-.]+\w
    * `:period` (seconds, deprecated) — Use 'token_period' instead.
    * `:renewable` (boolean) — Tokens created via this role will be renewable or not according to this value. Defaults to "true". Defaults to `true`.
    * `:token_bound_cidrs` (array) — Comma separated string or JSON list of CIDR blocks. If set, specifies the blocks of IP addresses which are allowed to use the generated token.
    * `:token_explicit_max_ttl` (seconds) — If set, tokens created via this role carry an explicit maximum TTL. During renewal, the current maximum TTL values of the role and the mount are not checked for changes, and any updates to these values will have no effect on the token being renewed.
    * `:token_no_default_policy` (boolean) — If true, the 'default' policy will not automatically be added to generated tokens
    * `:token_num_uses` (integer) — The maximum number of times a token may be used, a value of zero means unlimited
    * `:token_period` (seconds) — If set, tokens created via this role will have no max lifetime; instead, their renewal period will be fixed to this value. This takes an integer number of seconds, or a string duration (e.g. "24h").
    * `:token_type` (string) — The type of token to generate, service or batch Defaults to `"default-service"`.
  """
  @operation "token-write-role"
  @spec write_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_role(server, role_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/token/roles/#{ExBao.Operation.escape(role_name)}",
      opts,
      body: [
        :allowed_entity_aliases,
        :allowed_policies,
        :allowed_policies_glob,
        :bound_cidrs,
        :disallowed_policies,
        :disallowed_policies_glob,
        :explicit_max_ttl,
        :orphan,
        :path_suffix,
        :period,
        :renewable,
        :token_bound_cidrs,
        :token_explicit_max_ttl,
        :token_no_default_policy,
        :token_num_uses,
        :token_period,
        :token_type
      ]
    )
  end

  # ── end of generated ──
end
