defmodule ExBao.Auth.Userpass do
  @moduledoc """
    The username and password auth method.

    Generated from OpenBao's OpenAPI specification by `mix bao.gen`. One
    function per endpoint: path parameters are arguments, every other field
    is an option, and the answer is the server's own JSON body. An option
    the endpoint does not accept raises `ArgumentError` rather than being
    sent and ignored.
    
    Every function takes `:mount`, `"userpass"` by default.
  """

  use ExBao.Operation

  # ── generated by `mix bao.gen` from OpenBao 2.6.2 ──
  # Everything down to the closing marker is rewritten on every run. To
  # curate a function, move it above this block and keep its `@operation`:
  # the next run sees it there and stops generating it.

  @doc ~S"""
  Manage users allowed to authenticate.

  `DELETE /v1/auth/userpass/users/{username}`

  ## Arguments

    * `username` — Username for this user.

  ## Options

    * `:mount` — where the engine is mounted, `"userpass"` by default.
  """
  @operation "userpass-delete-user"
  @spec delete_user(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_user(server, username, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "auth/#{ExBao.Operation.mount(opts, "userpass")}/users/#{ExBao.Operation.escape(username)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage users allowed to authenticate.

  `GET /v1/auth/userpass/users`

  ## Options

    * `:mount` — where the engine is mounted, `"userpass"` by default.
  """
  @operation "userpass-list-users"
  @spec list_users(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def list_users(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{ExBao.Operation.mount(opts, "userpass")}/users",
      opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Log in with a username and password.

  `POST /v1/auth/userpass/login/{username}` — needs no token

  ## Arguments

    * `username` — Username of the user.

  ## Options

    * `:password` (string) — Password for this user.
    * `:mount` — where the engine is mounted, `"userpass"` by default.
  """
  @operation "userpass-login"
  @spec login(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def login(server, username, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "userpass")}/login/#{ExBao.Operation.escape(username)}",
      opts,
      body: [:password]
    )
  end

  @doc ~S"""
  Manage users allowed to authenticate.

  `GET /v1/auth/userpass/users/{username}`

  ## Arguments

    * `username` — Username for this user.

  ## Options

    * `:mount` — where the engine is mounted, `"userpass"` by default.
  """
  @operation "userpass-read-user"
  @spec read_user(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_user(server, username, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "auth/#{ExBao.Operation.mount(opts, "userpass")}/users/#{ExBao.Operation.escape(username)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Reset user's password.

  `POST /v1/auth/userpass/users/{username}/password`

  ## Arguments

    * `username` — Username for this user.

  ## Options

    * `:password` (string) — Password for this user.
    * `:password_hash` (string) — Pre-hashed bcrypt password for this user. Mutually exclusive with password.
    * `:mount` — where the engine is mounted, `"userpass"` by default.
  """
  @operation "userpass-reset-password"
  @spec reset_password(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def reset_password(server, username, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "userpass")}/users/#{ExBao.Operation.escape(username)}/password",
      opts,
      body: [:password, :password_hash]
    )
  end

  @doc ~S"""
  Update the policies associated with the username.

  `POST /v1/auth/userpass/users/{username}/policies`

  ## Arguments

    * `username` — Username for this user.

  ## Options

    * `:policies` (array, deprecated) — Use "token_policies" instead. If this and "token_policies" are both specified, only "token_policies" will be used.
    * `:token_policies` (array) — Comma-separated list of policies
    * `:mount` — where the engine is mounted, `"userpass"` by default.
  """
  @operation "userpass-update-policies"
  @spec update_policies(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def update_policies(server, username, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "userpass")}/users/#{ExBao.Operation.escape(username)}/policies",
      opts,
      body: [:policies, :token_policies]
    )
  end

  @doc ~S"""
  Manage users allowed to authenticate.

  `POST /v1/auth/userpass/users/{username}`

  ## Arguments

    * `username` — Username for this user.

  ## Options

    * `:bound_cidrs` (array, deprecated) — Use "token_bound_cidrs" instead. If this and "token_bound_cidrs" are both specified, only "token_bound_cidrs" will be used.
    * `:max_ttl` (seconds, deprecated) — Use "token_max_ttl" instead. If this and "token_max_ttl" are both specified, only "token_max_ttl" will be used.
    * `:password` (string) — Password for this user.
    * `:password_hash` (string) — Pre-hashed bcrypt password for this user. Mutually exclusive with password.
    * `:policies` (array, deprecated) — Use "token_policies" instead. If this and "token_policies" are both specified, only "token_policies" will be used.
    * `:token_bound_cidrs` (array) — Comma separated string or JSON list of CIDR blocks. If set, specifies the blocks of IP addresses which are allowed to use the generated token.
    * `:token_explicit_max_ttl` (seconds) — If set, tokens created via this role carry an explicit maximum TTL. During renewal, the current maximum TTL values of the role and the mount are not checked for changes, and any updates to these values will have no effect on the token being renewed.
    * `:token_max_ttl` (seconds) — The maximum lifetime of the generated token
    * `:token_no_default_policy` (boolean) — If true, the 'default' policy will not automatically be added to generated tokens
    * `:token_num_uses` (integer) — The maximum number of times a token may be used, a value of zero means unlimited
    * `:token_period` (seconds) — If set, tokens created via this role will have no max lifetime; instead, their renewal period will be fixed to this value. This takes an integer number of seconds, or a string duration (e.g. "24h").
    * `:token_policies` (array) — Comma-separated list of policies
    * `:token_strictly_bind_ip` (boolean) — If true, CIDRs for the token will be strictly bound to the source IP address of the login request
    * `:token_ttl` (seconds) — The initial ttl of the token to generate
    * `:token_type` (string) — The type of token to generate, service or batch Defaults to `"default-service"`.
    * `:ttl` (seconds, deprecated) — Use "token_ttl" instead. If this and "token_ttl" are both specified, only "token_ttl" will be used.
    * `:mount` — where the engine is mounted, `"userpass"` by default.
  """
  @operation "userpass-write-user"
  @spec write_user(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_user(server, username, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "auth/#{ExBao.Operation.mount(opts, "userpass")}/users/#{ExBao.Operation.escape(username)}",
      opts,
      body: [
        :bound_cidrs,
        :max_ttl,
        :password,
        :password_hash,
        :policies,
        :token_bound_cidrs,
        :token_explicit_max_ttl,
        :token_max_ttl,
        :token_no_default_policy,
        :token_num_uses,
        :token_period,
        :token_policies,
        :token_strictly_bind_ip,
        :token_ttl,
        :token_type,
        :ttl
      ]
    )
  end

  # ── end of generated ──
end
