defmodule ExBao.Cubbyhole do
  @moduledoc """
  The cubbyhole engine: storage private to one token.

  Generated from OpenBao's OpenAPI specification by `mix bao.gen`. One
  function per endpoint: path parameters are arguments, every other field
  is an option, and the answer is the server's own JSON body. An option
  the endpoint does not accept raises `ArgumentError` rather than being
  sent and ignored.
  """

  use ExBao.Operation

  # ── generated by `mix bao.gen` from OpenBao 2.6.2 ──
  # Everything down to the closing marker is rewritten on every run. To
  # curate a function, move it above this block and keep its `@operation`:
  # the next run sees it there and stops generating it.

  @doc ~S"""
  Deletes the secret at the specified location.

  `DELETE /v1/cubbyhole/{path}`

  Pass-through secret storage to a token-specific cubbyhole in the storage backend, allowing you to read/write arbitrary data into secret storage.

  ## Arguments

    * `path` — Specifies the path of the secret.
  """
  @operation "cubbyhole-delete"
  @spec delete(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete(server, path, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "cubbyhole/#{ExBao.Operation.escape_path(path)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Retrieve the secret at the specified location.

  `GET /v1/cubbyhole/{path}`

  Pass-through secret storage to a token-specific cubbyhole in the storage backend, allowing you to read/write arbitrary data into secret storage.

  ## Arguments

    * `path` — Specifies the path of the secret.

  ## Options

    * `:list` (string) — Return a list if `true`
  """
  @operation "cubbyhole-read"
  @spec read(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read(server, path, opts \\ []) do
    ExBao.Operation.call(server, :get, "cubbyhole/#{ExBao.Operation.escape_path(path)}", opts,
      query: [:list]
    )
  end

  @doc ~S"""
  Store a secret at the specified location.

  `POST /v1/cubbyhole/{path}`

  Pass-through secret storage to a token-specific cubbyhole in the storage backend, allowing you to read/write arbitrary data into secret storage.

  ## Arguments

    * `path` — Specifies the path of the secret.
  """
  @operation "cubbyhole-write"
  @spec write(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write(server, path, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "cubbyhole/#{ExBao.Operation.escape_path(path)}",
      opts,
      []
    )
  end

  # ── end of generated ──
end
