defmodule ExBao.Database do
  @moduledoc """
    The database secrets engine: dynamic and static credentials.

    Generated from OpenBao's OpenAPI specification by `mix bao.gen`. One
    function per endpoint: path parameters are arguments, every other field
    is an option, and the answer is the server's own JSON body. An option
    the endpoint does not accept raises `ArgumentError` rather than being
    sent and ignored.
    
    Every function takes `:mount`, `"database"` by default.
  """

  use ExBao.Operation

  # ── generated by `mix bao.gen` from OpenBao 2.6.2 ──
  # Everything down to the closing marker is rewritten on every run. To
  # curate a function, move it above this block and keep its `@operation`:
  # the next run sees it there and stops generating it.

  @doc ~S"""
  Configure connection details to a database plugin.

  `POST /v1/database/config/{name}`

  ## Arguments

    * `name` — Name of this database connection

  ## Options

    * `:allowed_roles` (array) — Comma separated string or array of the role names allowed to get creds from this database connection. If empty no roles are allowed. If "*" all roles are allowed.
    * `:password_policy` (string) — Password policy to use when generating passwords.
    * `:plugin_name` (string) — The name of a builtin or previously registered plugin known to OpenBao. This endpoint will create an instance of that plugin type.
    * `:plugin_version` (string) — The version of the plugin to use.
    * `:root_rotation_statements` (array) — Specifies the database statements to be executed to rotate the root user's credentials. See the plugin's API page for more information on support and formatting for this parameter.
    * `:verify_connection` (boolean) — If true, the connection details are verified by actually connecting to the database. Defaults to true. Defaults to `true`.
    * `:mount` — where the engine is mounted, `"database"` by default.
  """
  @operation "database-configure-connection"
  @spec configure_connection(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def configure_connection(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "database")}/config/#{ExBao.Operation.escape(name)}",
      opts,
      body: [
        :allowed_roles,
        :password_policy,
        :plugin_name,
        :plugin_version,
        :root_rotation_statements,
        :verify_connection
      ]
    )
  end

  @doc ~S"""
  Configure connection details to a database plugin.

  `DELETE /v1/database/config/{name}`

  ## Arguments

    * `name` — Name of this database connection

  ## Options

    * `:mount` — where the engine is mounted, `"database"` by default.
  """
  @operation "database-delete-connection-configuration"
  @spec delete_connection_configuration(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_connection_configuration(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "#{ExBao.Operation.mount(opts, "database")}/config/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage the roles that can be created with this backend.

  `DELETE /v1/database/roles/{name}`

  ## Arguments

    * `name` — Name of the role.

  ## Options

    * `:mount` — where the engine is mounted, `"database"` by default.
  """
  @operation "database-delete-role"
  @spec delete_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "#{ExBao.Operation.mount(opts, "database")}/roles/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage the static roles that can be created with this backend.

  `DELETE /v1/database/static-roles/{name}`

  ## Arguments

    * `name` — Name of the role.

  ## Options

    * `:mount` — where the engine is mounted, `"database"` by default.
  """
  @operation "database-delete-static-role"
  @spec delete_static_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_static_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "#{ExBao.Operation.mount(opts, "database")}/static-roles/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Request database credentials for a certain role.

  `GET /v1/database/creds/{name}`

  ## Arguments

    * `name` — Name of the role.

  ## Options

    * `:mount` — where the engine is mounted, `"database"` by default.
  """
  @operation "database-generate-credentials"
  @spec generate_credentials(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def generate_credentials(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "database")}/creds/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Configure connection details to a database plugin.

  `GET /v1/database/config`

  ## Options

    * `:mount` — where the engine is mounted, `"database"` by default.
  """
  @operation "database-list-connections"
  @spec list_connections(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def list_connections(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "#{ExBao.Operation.mount(opts, "database")}/config", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Manage the roles that can be created with this backend.

  `GET /v1/database/roles`

  ## Options

    * `:mount` — where the engine is mounted, `"database"` by default.
  """
  @operation "database-list-roles"
  @spec list_roles(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def list_roles(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "#{ExBao.Operation.mount(opts, "database")}/roles", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Manage the static roles that can be created with this backend.

  `GET /v1/database/static-roles`

  ## Options

    * `:mount` — where the engine is mounted, `"database"` by default.
  """
  @operation "database-list-static-roles"
  @spec list_static_roles(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def list_static_roles(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "database")}/static-roles",
      opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Configure connection details to a database plugin.

  `GET /v1/database/config/{name}`

  ## Arguments

    * `name` — Name of this database connection

  ## Options

    * `:mount` — where the engine is mounted, `"database"` by default.
  """
  @operation "database-read-connection-configuration"
  @spec read_connection_configuration(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_connection_configuration(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "database")}/config/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage the roles that can be created with this backend.

  `GET /v1/database/roles/{name}`

  ## Arguments

    * `name` — Name of the role.

  ## Options

    * `:mount` — where the engine is mounted, `"database"` by default.
  """
  @operation "database-read-role"
  @spec read_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "database")}/roles/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage the static roles that can be created with this backend.

  `GET /v1/database/static-roles/{name}`

  ## Arguments

    * `name` — Name of the role.

  ## Options

    * `:mount` — where the engine is mounted, `"database"` by default.
  """
  @operation "database-read-static-role"
  @spec read_static_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_static_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "database")}/static-roles/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Request database credentials for a certain static role. These credentials are rotated periodically.

  `GET /v1/database/static-creds/{name}`

  ## Arguments

    * `name` — Name of the static role.

  ## Options

    * `:mount` — where the engine is mounted, `"database"` by default.
  """
  @operation "database-read-static-role-credentials"
  @spec read_static_role_credentials(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_static_role_credentials(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "database")}/static-creds/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Resets a database plugin.

  `POST /v1/database/reset/{name}`

  ## Arguments

    * `name` — Name of this database connection

  ## Options

    * `:mount` — where the engine is mounted, `"database"` by default.
  """
  @operation "database-reset-connection"
  @spec reset_connection(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def reset_connection(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "database")}/reset/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Request to rotate the root credentials for a certain database connection.

  `POST /v1/database/rotate-root/{name}`

  ## Arguments

    * `name` — Name of this database connection

  ## Options

    * `:mount` — where the engine is mounted, `"database"` by default.
  """
  @operation "database-rotate-root-credentials"
  @spec rotate_root_credentials(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def rotate_root_credentials(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "database")}/rotate-root/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Request to rotate the credentials for a static user account.

  `POST /v1/database/rotate-role/{name}`

  ## Arguments

    * `name` — Name of the static role

  ## Options

    * `:mount` — where the engine is mounted, `"database"` by default.
  """
  @operation "database-rotate-static-role-credentials"
  @spec rotate_static_role_credentials(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def rotate_static_role_credentials(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "database")}/rotate-role/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage the roles that can be created with this backend.

  `POST /v1/database/roles/{name}`

  ## Arguments

    * `name` — Name of the role.

  ## Options

    * `:creation_statements` (array) — Specifies the database statements executed to create and configure a user. See the plugin's API page for more information on support and formatting for this parameter.
    * `:credential_config` (kvpairs) — The configuration for the given credential_type.
    * `:credential_type` (string) — The type of credential to manage. Options include: 'password', 'rsa_private_key'. Defaults to 'password'. Defaults to `"password"`.
    * `:db_name` (string) — Name of the database this role acts on.
    * `:default_ttl` (seconds) — Default ttl for role.
    * `:max_ttl` (seconds) — Maximum time a credential is valid for
    * `:renew_statements` (array) — Specifies the database statements to be executed to renew a user. Not every plugin type will support this functionality. See the plugin's API page for more information on support and formatting for this parameter.
    * `:revocation_statements` (array) — Specifies the database statements to be executed to revoke a user. See the plugin's API page for more information on support and formatting for this parameter.
    * `:rollback_statements` (array) — Specifies the database statements to be executed rollback a create operation in the event of an error. Not every plugin type will support this functionality. See the plugin's API page for more information on support and formatting for this parameter.
    * `:mount` — where the engine is mounted, `"database"` by default.
  """
  @operation "database-write-role"
  @spec write_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "database")}/roles/#{ExBao.Operation.escape(name)}",
      opts,
      body: [
        :creation_statements,
        :credential_config,
        :credential_type,
        :db_name,
        :default_ttl,
        :max_ttl,
        :renew_statements,
        :revocation_statements,
        :rollback_statements
      ]
    )
  end

  @doc ~S"""
  Manage the static roles that can be created with this backend.

  `POST /v1/database/static-roles/{name}`

  ## Arguments

    * `name` — Name of the role.

  ## Options

    * `:credential_config` (kvpairs) — The configuration for the given credential_type.
    * `:credential_type` (string) — The type of credential to manage. Options include: 'password', 'rsa_private_key'. Defaults to 'password'. Defaults to `"password"`.
    * `:db_name` (string) — Name of the database this role acts on.
    * `:rotation_period` (seconds) — Period for automatic credential rotation of the given username. Not valid unless used with "username".
    * `:rotation_statements` (array) — Specifies the database statements to be executed to rotate the accounts credentials. Not every plugin type will support this functionality. See the plugin's API page for more information on support and formatting for this parameter.
    * `:username` (string) — Name of the static user account for OpenBao to manage. Requires "rotation_period" to be specified
    * `:mount` — where the engine is mounted, `"database"` by default.
  """
  @operation "database-write-static-role"
  @spec write_static_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_static_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "database")}/static-roles/#{ExBao.Operation.escape(name)}",
      opts,
      body: [
        :credential_config,
        :credential_type,
        :db_name,
        :rotation_period,
        :rotation_statements,
        :username
      ]
    )
  end

  # ── end of generated ──
end
