defmodule ExBao.Identity do
  @moduledoc """
  The identity store: entities, groups, aliases, OIDC.

  Generated from OpenBao's OpenAPI specification by `mix bao.gen`. One
  function per endpoint: path parameters are arguments, every other field
  is an option, and the answer is the server's own JSON body. An option
  the endpoint does not accept raises `ArgumentError` rather than being
  sent and ignored.
  """

  use ExBao.Operation

  # ── generated by `mix bao.gen` from OpenBao 2.6.2 ──
  # Everything down to the closing marker is rewritten on every run. To
  # curate a function, move it above this block and keep its `@operation`:
  # the next run sees it there and stops generating it.

  @doc ~S"""
  Create a new alias.

  `POST /v1/identity/alias`

  ## Options

    * `:canonical_id` (string) — Entity ID to which this alias belongs to
    * `:entity_id` (string) — Entity ID to which this alias belongs to. This field is deprecated in favor of 'canonical_id'.
    * `:id` (string) — ID of the alias
    * `:mount_accessor` (string) — Mount accessor to which this alias belongs to
    * `:name` (string) — Name of the alias
  """
  @operation "alias-create"
  @spec alias_create(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def alias_create(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "identity/alias", opts,
      body: [:canonical_id, :entity_id, :id, :mount_accessor, :name]
    )
  end

  @doc ~S"""
  Update, read or delete an alias ID.

  `DELETE /v1/identity/alias/id/{id}`

  ## Arguments

    * `id` — ID of the alias
  """
  @operation "alias-delete-by-id"
  @spec alias_delete_by_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def alias_delete_by_id(server, id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "identity/alias/id/#{ExBao.Operation.escape(id)}",
      opts,
      []
    )
  end

  @doc ~S"""
  List all the alias IDs.

  `GET /v1/identity/alias/id`
  """
  @operation "alias-list-by-id"
  @spec alias_list_by_id(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def alias_list_by_id(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "identity/alias/id", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Update, read or delete an alias ID.

  `GET /v1/identity/alias/id/{id}`

  ## Arguments

    * `id` — ID of the alias
  """
  @operation "alias-read-by-id"
  @spec alias_read_by_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def alias_read_by_id(server, id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/alias/id/#{ExBao.Operation.escape(id)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Update, read or delete an alias ID.

  `POST /v1/identity/alias/id/{id}`

  ## Arguments

    * `id` — ID of the alias

  ## Options

    * `:canonical_id` (string) — Entity ID to which this alias should be tied to
    * `:entity_id` (string) — Entity ID to which this alias should be tied to. This field is deprecated in favor of 'canonical_id'.
    * `:mount_accessor` (string) — Mount accessor to which this alias belongs to
    * `:name` (string) — Name of the alias
  """
  @operation "alias-update-by-id"
  @spec alias_update_by_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def alias_update_by_id(server, id, opts \\ []) do
    ExBao.Operation.call(server, :post, "identity/alias/id/#{ExBao.Operation.escape(id)}", opts,
      body: [:canonical_id, :entity_id, :mount_accessor, :name]
    )
  end

  @doc ~S"""
  Delete all of the entities provided

  `POST /v1/identity/entity/batch-delete`

  ## Options

    * `:entity_ids` (array) — Entity IDs to delete
  """
  @operation "entity-batch-delete"
  @spec entity_batch_delete(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def entity_batch_delete(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "identity/entity/batch-delete", opts, body: [:entity_ids])
  end

  @doc ~S"""
  Create a new entity

  `POST /v1/identity/entity`

  ## Options

    * `:disabled` (boolean) — If set true, tokens tied to this identity will not be able to be used (but will not be revoked).
    * `:id` (string) — ID of the entity. If set, updates the corresponding existing entity.
    * `:metadata` (kvpairs) — Metadata to be associated with the entity. In CLI, this parameter can be repeated multiple times, and it all gets merged together. For example: bao <command> <path> metadata=key1=value1 metadata=key2=value2
    * `:name` (string) — Name of the entity
    * `:policies` (array) — Policies to be tied to the entity.
  """
  @operation "entity-create"
  @spec entity_create(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def entity_create(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "identity/entity", opts,
      body: [:disabled, :id, :metadata, :name, :policies]
    )
  end

  @doc ~S"""
  Create a new alias.

  `POST /v1/identity/entity-alias`

  ## Options

    * `:canonical_id` (string) — Entity ID to which this alias belongs
    * `:custom_metadata` (kvpairs) — User provided key-value pairs
    * `:entity_id` (string) — Entity ID to which this alias belongs. This field is deprecated, use canonical_id.
    * `:id` (string) — ID of the entity alias. If set, updates the corresponding entity alias.
    * `:mount_accessor` (string) — Mount accessor to which this alias belongs to; unused for a modify
    * `:name` (string) — Name of the alias; unused for a modify
  """
  @operation "entity-create-alias"
  @spec entity_create_alias(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def entity_create_alias(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "identity/entity-alias", opts,
      body: [:canonical_id, :custom_metadata, :entity_id, :id, :mount_accessor, :name]
    )
  end

  @doc ~S"""
  Update, read or delete an alias ID.

  `DELETE /v1/identity/entity-alias/id/{id}`

  ## Arguments

    * `id` — ID of the alias
  """
  @operation "entity-delete-alias-by-id"
  @spec entity_delete_alias_by_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def entity_delete_alias_by_id(server, id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "identity/entity-alias/id/#{ExBao.Operation.escape(id)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Update, read or delete an entity using entity ID

  `DELETE /v1/identity/entity/id/{id}`

  ## Arguments

    * `id` — ID of the entity. If set, updates the corresponding existing entity.
  """
  @operation "entity-delete-by-id"
  @spec entity_delete_by_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def entity_delete_by_id(server, id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "identity/entity/id/#{ExBao.Operation.escape(id)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Update, read or delete an entity using entity name

  `DELETE /v1/identity/entity/name/{name}`

  ## Arguments

    * `name` — Name of the entity
  """
  @operation "entity-delete-by-name"
  @spec entity_delete_by_name(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def entity_delete_by_name(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "identity/entity/name/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  List all the alias IDs.

  `GET /v1/identity/entity-alias/id`
  """
  @operation "entity-list-aliases-by-id"
  @spec entity_list_aliases_by_id(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def entity_list_aliases_by_id(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "identity/entity-alias/id", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  List all the entity IDs

  `GET /v1/identity/entity/id`
  """
  @operation "entity-list-by-id"
  @spec entity_list_by_id(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def entity_list_by_id(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "identity/entity/id", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  List all the entity names

  `GET /v1/identity/entity/name`
  """
  @operation "entity-list-by-name"
  @spec entity_list_by_name(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def entity_list_by_name(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "identity/entity/name", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Query entities based on various properties.

  `POST /v1/identity/lookup/entity`

  ## Options

    * `:alias_id` (string) — ID of the alias.
    * `:alias_mount_accessor` (string) — Accessor of the mount to which the alias belongs to. This should be supplied in conjunction with 'alias_name'.
    * `:alias_name` (string) — Name of the alias. This should be supplied in conjunction with 'alias_mount_accessor'.
    * `:id` (string) — ID of the entity.
    * `:name` (string) — Name of the entity.
  """
  @operation "entity-look-up"
  @spec entity_look_up(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def entity_look_up(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "identity/lookup/entity", opts,
      body: [:alias_id, :alias_mount_accessor, :alias_name, :id, :name]
    )
  end

  @doc ~S"""
  Merge two or more entities together

  `POST /v1/identity/entity/merge`

  ## Options

    * `:conflicting_alias_ids_to_keep` (array) — Alias IDs to keep in case of conflicting aliases. Ignored if no conflicting aliases found
    * `:force` (boolean) — Setting this will follow the 'mine' strategy for merging MFA secrets. If there are secrets of the same type both in entities that are merged from and in entity into which all others are getting merged, secrets in the destination will be unaltered. If not set, this API will throw an error containing all the conflicts.
    * `:from_entity_ids` (array) — Entity IDs which need to get merged
    * `:to_entity_id` (string) — Entity ID into which all the other entities need to get merged
  """
  @operation "entity-merge"
  @spec entity_merge(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def entity_merge(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "identity/entity/merge", opts,
      body: [:conflicting_alias_ids_to_keep, :force, :from_entity_ids, :to_entity_id]
    )
  end

  @doc ~S"""
  Update, read or delete an alias ID.

  `GET /v1/identity/entity-alias/id/{id}`

  ## Arguments

    * `id` — ID of the alias
  """
  @operation "entity-read-alias-by-id"
  @spec entity_read_alias_by_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def entity_read_alias_by_id(server, id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/entity-alias/id/#{ExBao.Operation.escape(id)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Update, read or delete an entity using entity ID

  `GET /v1/identity/entity/id/{id}`

  ## Arguments

    * `id` — ID of the entity. If set, updates the corresponding existing entity.
  """
  @operation "entity-read-by-id"
  @spec entity_read_by_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def entity_read_by_id(server, id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/entity/id/#{ExBao.Operation.escape(id)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Update, read or delete an entity using entity name

  `GET /v1/identity/entity/name/{name}`

  ## Arguments

    * `name` — Name of the entity
  """
  @operation "entity-read-by-name"
  @spec entity_read_by_name(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def entity_read_by_name(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/entity/name/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Update, read or delete an alias ID.

  `POST /v1/identity/entity-alias/id/{id}`

  ## Arguments

    * `id` — ID of the alias

  ## Options

    * `:canonical_id` (string) — Entity ID to which this alias should be tied to
    * `:custom_metadata` (kvpairs) — User provided key-value pairs
    * `:entity_id` (string) — Entity ID to which this alias belongs to. This field is deprecated, use canonical_id.
    * `:mount_accessor` (string) — (Unused)
    * `:name` (string) — (Unused)
  """
  @operation "entity-update-alias-by-id"
  @spec entity_update_alias_by_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def entity_update_alias_by_id(server, id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "identity/entity-alias/id/#{ExBao.Operation.escape(id)}",
      opts,
      body: [:canonical_id, :custom_metadata, :entity_id, :mount_accessor, :name]
    )
  end

  @doc ~S"""
  Update, read or delete an entity using entity ID

  `POST /v1/identity/entity/id/{id}`

  ## Arguments

    * `id` — ID of the entity. If set, updates the corresponding existing entity.

  ## Options

    * `:disabled` (boolean) — If set true, tokens tied to this identity will not be able to be used (but will not be revoked).
    * `:metadata` (kvpairs) — Metadata to be associated with the entity. In CLI, this parameter can be repeated multiple times, and it all gets merged together. For example: bao <command> <path> metadata=key1=value1 metadata=key2=value2
    * `:name` (string) — Name of the entity
    * `:policies` (array) — Policies to be tied to the entity.
  """
  @operation "entity-update-by-id"
  @spec entity_update_by_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def entity_update_by_id(server, id, opts \\ []) do
    ExBao.Operation.call(server, :post, "identity/entity/id/#{ExBao.Operation.escape(id)}", opts,
      body: [:disabled, :metadata, :name, :policies]
    )
  end

  @doc ~S"""
  Update, read or delete an entity using entity name

  `POST /v1/identity/entity/name/{name}`

  ## Arguments

    * `name` — Name of the entity

  ## Options

    * `:disabled` (boolean) — If set true, tokens tied to this identity will not be able to be used (but will not be revoked).
    * `:id` (string) — ID of the entity. If set, updates the corresponding existing entity.
    * `:metadata` (kvpairs) — Metadata to be associated with the entity. In CLI, this parameter can be repeated multiple times, and it all gets merged together. For example: bao <command> <path> metadata=key1=value1 metadata=key2=value2
    * `:policies` (array) — Policies to be tied to the entity.
  """
  @operation "entity-update-by-name"
  @spec entity_update_by_name(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def entity_update_by_name(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "identity/entity/name/#{ExBao.Operation.escape(name)}",
      opts,
      body: [:disabled, :id, :metadata, :policies]
    )
  end

  @doc ~S"""
  Create a new group.

  `POST /v1/identity/group`

  ## Options

    * `:id` (string) — ID of the group. If set, updates the corresponding existing group.
    * `:member_entity_ids` (array) — Entity IDs to be assigned as group members.
    * `:member_group_ids` (array) — Group IDs to be assigned as group members.
    * `:metadata` (kvpairs) — Metadata to be associated with the group. In CLI, this parameter can be repeated multiple times, and it all gets merged together. For example: bao <command> <path> metadata=key1=value1 metadata=key2=value2
    * `:name` (string) — Name of the group.
    * `:policies` (array) — Policies to be tied to the group.
    * `:type` (string) — Type of the group, 'internal' or 'external'. Defaults to 'internal'
  """
  @operation "group-create"
  @spec group_create(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def group_create(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "identity/group", opts,
      body: [:id, :member_entity_ids, :member_group_ids, :metadata, :name, :policies, :type]
    )
  end

  @doc ~S"""
  Creates a new group alias, or updates an existing one.

  `POST /v1/identity/group-alias`

  ## Options

    * `:canonical_id` (string) — ID of the group to which this is an alias.
    * `:id` (string) — ID of the group alias.
    * `:mount_accessor` (string) — Mount accessor to which this alias belongs to.
    * `:name` (string) — Alias of the group.
  """
  @operation "group-create-alias"
  @spec group_create_alias(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def group_create_alias(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "identity/group-alias", opts,
      body: [:canonical_id, :id, :mount_accessor, :name]
    )
  end

  @doc ~S"""
  `group-delete-alias-by-id`

  `DELETE /v1/identity/group-alias/id/{id}`

  ## Arguments

    * `id` — ID of the group alias.
  """
  @operation "group-delete-alias-by-id"
  @spec group_delete_alias_by_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def group_delete_alias_by_id(server, id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "identity/group-alias/id/#{ExBao.Operation.escape(id)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Update or delete an existing group using its ID.

  `DELETE /v1/identity/group/id/{id}`

  ## Arguments

    * `id` — ID of the group. If set, updates the corresponding existing group.
  """
  @operation "group-delete-by-id"
  @spec group_delete_by_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def group_delete_by_id(server, id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "identity/group/id/#{ExBao.Operation.escape(id)}",
      opts,
      []
    )
  end

  @doc ~S"""
  `group-delete-by-name`

  `DELETE /v1/identity/group/name/{name}`

  ## Arguments

    * `name` — Name of the group.
  """
  @operation "group-delete-by-name"
  @spec group_delete_by_name(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def group_delete_by_name(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "identity/group/name/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  List all the group alias IDs.

  `GET /v1/identity/group-alias/id`
  """
  @operation "group-list-aliases-by-id"
  @spec group_list_aliases_by_id(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def group_list_aliases_by_id(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "identity/group-alias/id", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  List all the group IDs.

  `GET /v1/identity/group/id`
  """
  @operation "group-list-by-id"
  @spec group_list_by_id(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def group_list_by_id(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "identity/group/id", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  `group-list-by-name`

  `GET /v1/identity/group/name`
  """
  @operation "group-list-by-name"
  @spec group_list_by_name(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def group_list_by_name(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "identity/group/name", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Query groups based on various properties.

  `POST /v1/identity/lookup/group`

  ## Options

    * `:alias_id` (string) — ID of the alias.
    * `:alias_mount_accessor` (string) — Accessor of the mount to which the alias belongs to. This should be supplied in conjunction with 'alias_name'.
    * `:alias_name` (string) — Name of the alias. This should be supplied in conjunction with 'alias_mount_accessor'.
    * `:id` (string) — ID of the group.
    * `:name` (string) — Name of the group.
  """
  @operation "group-look-up"
  @spec group_look_up(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def group_look_up(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "identity/lookup/group", opts,
      body: [:alias_id, :alias_mount_accessor, :alias_name, :id, :name]
    )
  end

  @doc ~S"""
  `group-read-alias-by-id`

  `GET /v1/identity/group-alias/id/{id}`

  ## Arguments

    * `id` — ID of the group alias.
  """
  @operation "group-read-alias-by-id"
  @spec group_read_alias_by_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def group_read_alias_by_id(server, id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/group-alias/id/#{ExBao.Operation.escape(id)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Update or delete an existing group using its ID.

  `GET /v1/identity/group/id/{id}`

  ## Arguments

    * `id` — ID of the group. If set, updates the corresponding existing group.
  """
  @operation "group-read-by-id"
  @spec group_read_by_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def group_read_by_id(server, id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/group/id/#{ExBao.Operation.escape(id)}",
      opts,
      []
    )
  end

  @doc ~S"""
  `group-read-by-name`

  `GET /v1/identity/group/name/{name}`

  ## Arguments

    * `name` — Name of the group.
  """
  @operation "group-read-by-name"
  @spec group_read_by_name(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def group_read_by_name(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/group/name/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  `group-update-alias-by-id`

  `POST /v1/identity/group-alias/id/{id}`

  ## Arguments

    * `id` — ID of the group alias.

  ## Options

    * `:canonical_id` (string) — ID of the group to which this is an alias.
    * `:mount_accessor` (string) — Mount accessor to which this alias belongs to.
    * `:name` (string) — Alias of the group.
  """
  @operation "group-update-alias-by-id"
  @spec group_update_alias_by_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def group_update_alias_by_id(server, id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "identity/group-alias/id/#{ExBao.Operation.escape(id)}",
      opts,
      body: [:canonical_id, :mount_accessor, :name]
    )
  end

  @doc ~S"""
  Update or delete an existing group using its ID.

  `POST /v1/identity/group/id/{id}`

  ## Arguments

    * `id` — ID of the group. If set, updates the corresponding existing group.

  ## Options

    * `:member_entity_ids` (array) — Entity IDs to be assigned as group members.
    * `:member_group_ids` (array) — Group IDs to be assigned as group members.
    * `:metadata` (kvpairs) — Metadata to be associated with the group. In CLI, this parameter can be repeated multiple times, and it all gets merged together. For example: bao <command> <path> metadata=key1=value1 metadata=key2=value2
    * `:name` (string) — Name of the group.
    * `:policies` (array) — Policies to be tied to the group.
    * `:type` (string) — Type of the group, 'internal' or 'external'. Defaults to 'internal'
  """
  @operation "group-update-by-id"
  @spec group_update_by_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def group_update_by_id(server, id, opts \\ []) do
    ExBao.Operation.call(server, :post, "identity/group/id/#{ExBao.Operation.escape(id)}", opts,
      body: [:member_entity_ids, :member_group_ids, :metadata, :name, :policies, :type]
    )
  end

  @doc ~S"""
  `group-update-by-name`

  `POST /v1/identity/group/name/{name}`

  ## Arguments

    * `name` — Name of the group.

  ## Options

    * `:id` (string) — ID of the group. If set, updates the corresponding existing group.
    * `:member_entity_ids` (array) — Entity IDs to be assigned as group members.
    * `:member_group_ids` (array) — Group IDs to be assigned as group members.
    * `:metadata` (kvpairs) — Metadata to be associated with the group. In CLI, this parameter can be repeated multiple times, and it all gets merged together. For example: bao <command> <path> metadata=key1=value1 metadata=key2=value2
    * `:policies` (array) — Policies to be tied to the group.
    * `:type` (string) — Type of the group, 'internal' or 'external'. Defaults to 'internal'
  """
  @operation "group-update-by-name"
  @spec group_update_by_name(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def group_update_by_name(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "identity/group/name/#{ExBao.Operation.escape(name)}",
      opts,
      body: [:id, :member_entity_ids, :member_group_ids, :metadata, :policies, :type]
    )
  end

  @doc ~S"""
  Destroys a TOTP secret for the given MFA method ID on the given entity

  `POST /v1/identity/mfa/method/totp/admin-destroy`

  ## Options

    * `:entity_id` (string, required) — Identifier of the entity from which the MFA method secret needs to be removed.
    * `:method_id` (string, required) — The unique identifier for this MFA method.
  """
  @operation "mfa-admin-destroy-totp-secret"
  @spec mfa_admin_destroy_totp_secret(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def mfa_admin_destroy_totp_secret(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "identity/mfa/method/totp/admin-destroy", opts,
      body: [:entity_id, :method_id],
      required: [:entity_id, :method_id]
    )
  end

  @doc ~S"""
  Update or create TOTP secret for the given method ID on the given entity.

  `POST /v1/identity/mfa/method/totp/admin-generate`

  ## Options

    * `:entity_id` (string, required) — Entity ID on which the generated secret needs to get stored.
    * `:method_id` (string, required) — The unique identifier for this MFA method.
  """
  @operation "mfa-admin-generate-totp-secret"
  @spec mfa_admin_generate_totp_secret(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def mfa_admin_generate_totp_secret(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "identity/mfa/method/totp/admin-generate", opts,
      body: [:entity_id, :method_id],
      required: [:entity_id, :method_id]
    )
  end

  @doc ~S"""
  Update or create a configuration for the given MFA method

  `POST /v1/identity/mfa/method/duo/{method_id}`

  ## Arguments

    * `method_id` — The unique identifier for this MFA method.

  ## Options

    * `:api_hostname` (string) — API host name for Duo.
    * `:integration_key` (string) — Integration key for Duo.
    * `:method_name` (string) — The unique name identifier for this MFA method.
    * `:push_info` (string) — Push information for Duo.
    * `:secret_key` (string) — Secret key for Duo.
    * `:use_passcode` (boolean) — If true, the user is reminded to use the passcode upon MFA validation. This option does not enforce using the passcode. Defaults to false.
    * `:username_format` (string) — A template string for mapping Identity names to MFA method names. Values to subtitute should be placed in {{}}. For example, "{{alias.name}}@example.com". Currently-supported mappings: alias.name: The name returned by the mount configured via the mount_accessor parameter If blank, the Alias's name field will be used as-is.
  """
  @operation "mfa-configure-duo-method"
  @spec mfa_configure_duo_method(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def mfa_configure_duo_method(server, method_id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "identity/mfa/method/duo/#{ExBao.Operation.escape(method_id)}",
      opts,
      body: [
        :api_hostname,
        :integration_key,
        :method_name,
        :push_info,
        :secret_key,
        :use_passcode,
        :username_format
      ]
    )
  end

  @doc ~S"""
  Update or create a configuration for the given MFA method

  `POST /v1/identity/mfa/method/okta/{method_id}`

  ## Arguments

    * `method_id` — The unique identifier for this MFA method.

  ## Options

    * `:api_token` (string) — Okta API key.
    * `:base_url` (string) — The base domain to use for the Okta API. When not specified in the configuration, "okta.com" is used.
    * `:method_name` (string) — The unique name identifier for this MFA method.
    * `:org_name` (string) — Name of the organization to be used in the Okta API.
    * `:primary_email` (boolean) — If true, the username will only match the primary email for the account. Defaults to false.
    * `:production` (boolean) — (DEPRECATED) Use base_url instead.
    * `:username_format` (string) — A template string for mapping Identity names to MFA method names. Values to substitute should be placed in {{}}. For example, "{{entity.name}}@example.com". If blank, the Entity's name field will be used as-is.
  """
  @operation "mfa-configure-okta-method"
  @spec mfa_configure_okta_method(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def mfa_configure_okta_method(server, method_id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "identity/mfa/method/okta/#{ExBao.Operation.escape(method_id)}",
      opts,
      body: [
        :api_token,
        :base_url,
        :method_name,
        :org_name,
        :primary_email,
        :production,
        :username_format
      ]
    )
  end

  @doc ~S"""
  Update or create a configuration for the given MFA method

  `POST /v1/identity/mfa/method/pingid/{method_id}`

  ## Arguments

    * `method_id` — The unique identifier for this MFA method.

  ## Options

    * `:method_name` (string) — The unique name identifier for this MFA method.
    * `:settings_file_base64` (string) — The settings file provided by Ping, Base64-encoded. This must be a settings file suitable for third-party clients, not the PingID SDK or PingFederate.
    * `:username_format` (string) — A template string for mapping Identity names to MFA method names. Values to subtitute should be placed in {{}}. For example, "{{alias.name}}@example.com". Currently-supported mappings: alias.name: The name returned by the mount configured via the mount_accessor parameter If blank, the Alias's name field will be used as-is.
  """
  @operation "mfa-configure-ping-id-method"
  @spec mfa_configure_ping_id_method(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def mfa_configure_ping_id_method(server, method_id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "identity/mfa/method/pingid/#{ExBao.Operation.escape(method_id)}",
      opts,
      body: [:method_name, :settings_file_base64, :username_format]
    )
  end

  @doc ~S"""
  Update or create a configuration for the given MFA method

  `POST /v1/identity/mfa/method/totp/{method_id}`

  ## Arguments

    * `method_id` — The unique identifier for this MFA method.

  ## Options

    * `:algorithm` (string) — The hashing algorithm used to generate the TOTP token. Options include SHA1, SHA256 and SHA512. Defaults to `"SHA1"`.
    * `:digits` (integer) — The number of digits in the generated TOTP token. This value can either be 6 or 8. Defaults to `6`.
    * `:issuer` (string) — The name of the key's issuing organization.
    * `:key_size` (integer) — Determines the size in bytes of the generated key. Defaults to `20`.
    * `:max_validation_attempts` (integer) — Max number of allowed validation attempts.
    * `:method_name` (string) — The unique name identifier for this MFA method.
    * `:period` (seconds) — The length of time used to generate a counter for the TOTP token calculation. Defaults to `30`.
    * `:qr_size` (integer) — The pixel size of the generated square QR code. Defaults to `200`.
    * `:skew` (integer) — The number of delay periods that are allowed when validating a TOTP token. This value can either be 0 or 1. Defaults to `1`.
  """
  @operation "mfa-configure-totp-method"
  @spec mfa_configure_totp_method(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def mfa_configure_totp_method(server, method_id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "identity/mfa/method/totp/#{ExBao.Operation.escape(method_id)}",
      opts,
      body: [
        :algorithm,
        :digits,
        :issuer,
        :key_size,
        :max_validation_attempts,
        :method_name,
        :period,
        :qr_size,
        :skew
      ]
    )
  end

  @doc ~S"""
  Delete a configuration for the given MFA method

  `DELETE /v1/identity/mfa/method/duo/{method_id}`

  ## Arguments

    * `method_id` — The unique identifier for this MFA method.
  """
  @operation "mfa-delete-duo-method"
  @spec mfa_delete_duo_method(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def mfa_delete_duo_method(server, method_id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "identity/mfa/method/duo/#{ExBao.Operation.escape(method_id)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Delete a login enforcement

  `DELETE /v1/identity/mfa/login-enforcement/{name}`

  ## Arguments

    * `name` — Name for this login enforcement configuration
  """
  @operation "mfa-delete-login-enforcement"
  @spec mfa_delete_login_enforcement(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def mfa_delete_login_enforcement(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "identity/mfa/login-enforcement/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Delete a configuration for the given MFA method

  `DELETE /v1/identity/mfa/method/okta/{method_id}`

  ## Arguments

    * `method_id` — The unique identifier for this MFA method.
  """
  @operation "mfa-delete-okta-method"
  @spec mfa_delete_okta_method(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def mfa_delete_okta_method(server, method_id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "identity/mfa/method/okta/#{ExBao.Operation.escape(method_id)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Delete a configuration for the given MFA method

  `DELETE /v1/identity/mfa/method/pingid/{method_id}`

  ## Arguments

    * `method_id` — The unique identifier for this MFA method.
  """
  @operation "mfa-delete-ping-id-method"
  @spec mfa_delete_ping_id_method(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def mfa_delete_ping_id_method(server, method_id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "identity/mfa/method/pingid/#{ExBao.Operation.escape(method_id)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Delete a configuration for the given MFA method

  `DELETE /v1/identity/mfa/method/totp/{method_id}`

  ## Arguments

    * `method_id` — The unique identifier for this MFA method.
  """
  @operation "mfa-delete-totp-method"
  @spec mfa_delete_totp_method(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def mfa_delete_totp_method(server, method_id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "identity/mfa/method/totp/#{ExBao.Operation.escape(method_id)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Update or create TOTP secret for the given method ID on the given entity.

  `POST /v1/identity/mfa/method/totp/generate`

  ## Options

    * `:method_id` (string, required) — The unique identifier for this MFA method.
  """
  @operation "mfa-generate-totp-secret"
  @spec mfa_generate_totp_secret(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def mfa_generate_totp_secret(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "identity/mfa/method/totp/generate", opts,
      body: [:method_id],
      required: [:method_id]
    )
  end

  @doc ~S"""
  List MFA method configurations for the given MFA method

  `GET /v1/identity/mfa/method/duo`
  """
  @operation "mfa-list-duo-methods"
  @spec mfa_list_duo_methods(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def mfa_list_duo_methods(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "identity/mfa/method/duo", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  List login enforcements

  `GET /v1/identity/mfa/login-enforcement`
  """
  @operation "mfa-list-login-enforcements"
  @spec mfa_list_login_enforcements(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def mfa_list_login_enforcements(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "identity/mfa/login-enforcement", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  List MFA method configurations for all MFA methods

  `GET /v1/identity/mfa/method`
  """
  @operation "mfa-list-methods"
  @spec mfa_list_methods(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def mfa_list_methods(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "identity/mfa/method", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  List MFA method configurations for the given MFA method

  `GET /v1/identity/mfa/method/okta`
  """
  @operation "mfa-list-okta-methods"
  @spec mfa_list_okta_methods(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def mfa_list_okta_methods(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "identity/mfa/method/okta", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  List MFA method configurations for the given MFA method

  `GET /v1/identity/mfa/method/pingid`
  """
  @operation "mfa-list-ping-id-methods"
  @spec mfa_list_ping_id_methods(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def mfa_list_ping_id_methods(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "identity/mfa/method/pingid", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  List MFA method configurations for the given MFA method

  `GET /v1/identity/mfa/method/totp`
  """
  @operation "mfa-list-totp-methods"
  @spec mfa_list_totp_methods(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def mfa_list_totp_methods(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "identity/mfa/method/totp", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Read the current configuration for the given MFA method

  `GET /v1/identity/mfa/method/duo/{method_id}`

  ## Arguments

    * `method_id` — The unique identifier for this MFA method.
  """
  @operation "mfa-read-duo-method-configuration"
  @spec mfa_read_duo_method_configuration(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def mfa_read_duo_method_configuration(server, method_id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/mfa/method/duo/#{ExBao.Operation.escape(method_id)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Read the current login enforcement

  `GET /v1/identity/mfa/login-enforcement/{name}`

  ## Arguments

    * `name` — Name for this login enforcement configuration
  """
  @operation "mfa-read-login-enforcement"
  @spec mfa_read_login_enforcement(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def mfa_read_login_enforcement(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/mfa/login-enforcement/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Read the current configuration for the given ID regardless of the MFA method type

  `GET /v1/identity/mfa/method/{method_id}`

  ## Arguments

    * `method_id` — The unique identifier for this MFA method.
  """
  @operation "mfa-read-method-configuration"
  @spec mfa_read_method_configuration(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def mfa_read_method_configuration(server, method_id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/mfa/method/#{ExBao.Operation.escape(method_id)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Read the current configuration for the given MFA method

  `GET /v1/identity/mfa/method/okta/{method_id}`

  ## Arguments

    * `method_id` — The unique identifier for this MFA method.
  """
  @operation "mfa-read-okta-method-configuration"
  @spec mfa_read_okta_method_configuration(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def mfa_read_okta_method_configuration(server, method_id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/mfa/method/okta/#{ExBao.Operation.escape(method_id)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Read the current configuration for the given MFA method

  `GET /v1/identity/mfa/method/pingid/{method_id}`

  ## Arguments

    * `method_id` — The unique identifier for this MFA method.
  """
  @operation "mfa-read-ping-id-method-configuration"
  @spec mfa_read_ping_id_method_configuration(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def mfa_read_ping_id_method_configuration(server, method_id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/mfa/method/pingid/#{ExBao.Operation.escape(method_id)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Read the current configuration for the given MFA method

  `GET /v1/identity/mfa/method/totp/{method_id}`

  ## Arguments

    * `method_id` — The unique identifier for this MFA method.
  """
  @operation "mfa-read-totp-method-configuration"
  @spec mfa_read_totp_method_configuration(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def mfa_read_totp_method_configuration(server, method_id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/mfa/method/totp/#{ExBao.Operation.escape(method_id)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Create or update a login enforcement

  `POST /v1/identity/mfa/login-enforcement/{name}`

  ## Arguments

    * `name` — Name for this login enforcement configuration

  ## Options

    * `:auth_method_accessors` (array) — Array of auth mount accessor IDs
    * `:auth_method_types` (array) — Array of auth mount types
    * `:identity_entity_ids` (array) — Array of identity entity IDs
    * `:identity_group_ids` (array) — Array of identity group IDs
    * `:mfa_method_ids` (array, required) — Array of Method IDs that determine what methods will be enforced
  """
  @operation "mfa-write-login-enforcement"
  @spec mfa_write_login_enforcement(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def mfa_write_login_enforcement(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "identity/mfa/login-enforcement/#{ExBao.Operation.escape(name)}",
      opts,
      body: [
        :auth_method_accessors,
        :auth_method_types,
        :identity_entity_ids,
        :identity_group_ids,
        :mfa_method_ids
      ],
      required: [:mfa_method_ids]
    )
  end

  @doc ~S"""
  OIDC configuration

  `POST /v1/identity/oidc/config`

  ## Options

    * `:issuer` (string) — Issuer URL to be used in the iss claim of the token. If not set, OpenBao's app_addr will be used.
  """
  @operation "oidc-configure"
  @spec oidc_configure(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def oidc_configure(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "identity/oidc/config", opts, body: [:issuer])
  end

  @doc ~S"""
  CRUD operations for OIDC assignments.

  `DELETE /v1/identity/oidc/assignment/{name}`

  ## Arguments

    * `name` — Name of the assignment
  """
  @operation "oidc-delete-assignment"
  @spec oidc_delete_assignment(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_delete_assignment(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "identity/oidc/assignment/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  CRUD operations for OIDC clients.

  `DELETE /v1/identity/oidc/client/{name}`

  ## Arguments

    * `name` — Name of the client.
  """
  @operation "oidc-delete-client"
  @spec oidc_delete_client(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_delete_client(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "identity/oidc/client/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  CRUD operations for OIDC keys.

  `DELETE /v1/identity/oidc/key/{name}`

  ## Arguments

    * `name` — Name of the key
  """
  @operation "oidc-delete-key"
  @spec oidc_delete_key(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_delete_key(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "identity/oidc/key/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  CRUD operations for OIDC providers.

  `DELETE /v1/identity/oidc/provider/{name}`

  ## Arguments

    * `name` — Name of the provider
  """
  @operation "oidc-delete-provider"
  @spec oidc_delete_provider(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_delete_provider(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "identity/oidc/provider/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  CRUD operations on OIDC Roles

  `DELETE /v1/identity/oidc/role/{name}`

  ## Arguments

    * `name` — Name of the role
  """
  @operation "oidc-delete-role"
  @spec oidc_delete_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_delete_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "identity/oidc/role/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  CRUD operations for OIDC scopes.

  `DELETE /v1/identity/oidc/scope/{name}`

  ## Arguments

    * `name` — Name of the scope
  """
  @operation "oidc-delete-scope"
  @spec oidc_delete_scope(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_delete_scope(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "identity/oidc/scope/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Generate an OIDC token

  `GET /v1/identity/oidc/token/{name}`

  ## Arguments

    * `name` — Name of the role
  """
  @operation "oidc-generate-token"
  @spec oidc_generate_token(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_generate_token(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/oidc/token/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Verify the authenticity of an OIDC token

  `POST /v1/identity/oidc/introspect`

  ## Options

    * `:client_id` (string) — Optional client_id to verify
    * `:token` (string) — Token to verify
  """
  @operation "oidc-introspect"
  @spec oidc_introspect(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def oidc_introspect(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "identity/oidc/introspect", opts,
      body: [:client_id, :token]
    )
  end

  @doc ~S"""
  List OIDC assignments

  `GET /v1/identity/oidc/assignment`
  """
  @operation "oidc-list-assignments"
  @spec oidc_list_assignments(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def oidc_list_assignments(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "identity/oidc/assignment", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  List OIDC clients

  `GET /v1/identity/oidc/client`
  """
  @operation "oidc-list-clients"
  @spec oidc_list_clients(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def oidc_list_clients(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "identity/oidc/client", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  List OIDC keys

  `GET /v1/identity/oidc/key`
  """
  @operation "oidc-list-keys"
  @spec oidc_list_keys(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def oidc_list_keys(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "identity/oidc/key", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  List OIDC providers

  `GET /v1/identity/oidc/provider`

  ## Options

    * `:allowed_client_id` (string) — Filters the list of OIDC providers to those that allow the given client ID in their set of allowed_client_ids. Defaults to `""`.
  """
  @operation "oidc-list-providers"
  @spec oidc_list_providers(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def oidc_list_providers(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "identity/oidc/provider", opts,
      query: [:allowed_client_id],
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  List configured OIDC roles

  `GET /v1/identity/oidc/role`
  """
  @operation "oidc-list-roles"
  @spec oidc_list_roles(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def oidc_list_roles(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "identity/oidc/role", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  List OIDC scopes

  `GET /v1/identity/oidc/scope`
  """
  @operation "oidc-list-scopes"
  @spec oidc_list_scopes(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def oidc_list_scopes(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "identity/oidc/scope", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Provides the OIDC Authorization Endpoint.

  `GET /v1/identity/oidc/provider/{name}/authorize`

  ## Arguments

    * `name` — Name of the provider
  """
  @operation "oidc-provider-authorize"
  @spec oidc_provider_authorize(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_provider_authorize(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/oidc/provider/#{ExBao.Operation.escape(name)}/authorize",
      opts,
      []
    )
  end

  @doc ~S"""
  Provides the OIDC Authorization Endpoint.

  `POST /v1/identity/oidc/provider/{name}/authorize`

  ## Arguments

    * `name` — Name of the provider

  ## Options

    * `:client_id` (string, required) — The ID of the requesting client.
    * `:code_challenge` (string) — The code challenge derived from the code verifier.
    * `:code_challenge_method` (string) — The method that was used to derive the code challenge. The following methods are supported: 'S256', 'plain'. Defaults to 'plain'. Defaults to `"plain"`.
    * `:max_age` (integer) — The allowable elapsed time in seconds since the last time the end-user was actively authenticated.
    * `:nonce` (string) — The value that will be returned in the ID token nonce claim after a token exchange.
    * `:redirect_uri` (string, required) — The redirection URI to which the response will be sent.
    * `:response_type` (string, required) — The OIDC authentication flow to be used. The following response types are supported: 'code'
    * `:scope` (string, required) — A space-delimited, case-sensitive list of scopes to be requested. The 'openid' scope is required.
    * `:state` (string) — The value used to maintain state between the authentication request and client.
  """
  @operation "oidc-provider-authorize-with-parameters"
  @spec oidc_provider_authorize_with_parameters(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_provider_authorize_with_parameters(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "identity/oidc/provider/#{ExBao.Operation.escape(name)}/authorize",
      opts,
      body: [
        :client_id,
        :code_challenge,
        :code_challenge_method,
        :max_age,
        :nonce,
        :redirect_uri,
        :response_type,
        :scope,
        :state
      ],
      required: [:client_id, :redirect_uri, :response_type, :scope]
    )
  end

  @doc ~S"""
  Provides the OIDC Token Endpoint.

  `POST /v1/identity/oidc/provider/{name}/token` — needs no token

  ## Arguments

    * `name` — Name of the provider

  ## Options

    * `:client_id` (string) — The ID of the requesting client.
    * `:client_secret` (string) — The secret of the requesting client.
    * `:code` (string, required) — The authorization code received from the provider's authorization endpoint.
    * `:code_verifier` (string) — The code verifier associated with the authorization code.
    * `:grant_type` (string, required) — The authorization grant type. The following grant types are supported: 'authorization_code','client_credentials'.
    * `:redirect_uri` (string, required) — The callback location where the authentication response was sent.
    * `:scope` (string, required) — A space-delimited, case-sensitive list of scopes to be requested. The 'openid' scope is required. This is used when using in with 'client_credentials' flow
  """
  @operation "oidc-provider-token"
  @spec oidc_provider_token(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_provider_token(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "identity/oidc/provider/#{ExBao.Operation.escape(name)}/token",
      opts,
      body: [
        :client_id,
        :client_secret,
        :code,
        :code_verifier,
        :grant_type,
        :redirect_uri,
        :scope
      ],
      required: [:code, :grant_type, :redirect_uri, :scope]
    )
  end

  @doc ~S"""
  Provides the OIDC UserInfo Endpoint.

  `GET /v1/identity/oidc/provider/{name}/userinfo`

  ## Arguments

    * `name` — Name of the provider
  """
  @operation "oidc-provider-user-info"
  @spec oidc_provider_user_info(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_provider_user_info(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/oidc/provider/#{ExBao.Operation.escape(name)}/userinfo",
      opts,
      []
    )
  end

  @doc ~S"""
  Provides the OIDC UserInfo Endpoint.

  `POST /v1/identity/oidc/provider/{name}/userinfo`

  ## Arguments

    * `name` — Name of the provider
  """
  @operation "oidc-provider-user-info2"
  @spec oidc_provider_user_info2(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_provider_user_info2(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "identity/oidc/provider/#{ExBao.Operation.escape(name)}/userinfo",
      opts,
      []
    )
  end

  @doc ~S"""
  CRUD operations for OIDC assignments.

  `GET /v1/identity/oidc/assignment/{name}`

  ## Arguments

    * `name` — Name of the assignment
  """
  @operation "oidc-read-assignment"
  @spec oidc_read_assignment(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_read_assignment(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/oidc/assignment/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  CRUD operations for OIDC clients.

  `GET /v1/identity/oidc/client/{name}`

  ## Arguments

    * `name` — Name of the client.
  """
  @operation "oidc-read-client"
  @spec oidc_read_client(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_read_client(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/oidc/client/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  OIDC configuration

  `GET /v1/identity/oidc/config`
  """
  @operation "oidc-read-configuration"
  @spec oidc_read_configuration(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def oidc_read_configuration(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "identity/oidc/config", opts, [])
  end

  @doc ~S"""
  CRUD operations for OIDC keys.

  `GET /v1/identity/oidc/key/{name}`

  ## Arguments

    * `name` — Name of the key
  """
  @operation "oidc-read-key"
  @spec oidc_read_key(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_read_key(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/oidc/key/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Query OIDC configurations

  `GET /v1/identity/oidc/.well-known/openid-configuration` — needs no token
  """
  @operation "oidc-read-open-id-configuration"
  @spec oidc_read_open_id_configuration(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def oidc_read_open_id_configuration(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "identity/oidc/.well-known/openid-configuration", opts, [])
  end

  @doc ~S"""
  CRUD operations for OIDC providers.

  `GET /v1/identity/oidc/provider/{name}`

  ## Arguments

    * `name` — Name of the provider
  """
  @operation "oidc-read-provider"
  @spec oidc_read_provider(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_read_provider(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/oidc/provider/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Query OIDC configurations

  `GET /v1/identity/oidc/provider/{name}/.well-known/openid-configuration` — needs no token

  ## Arguments

    * `name` — Name of the provider
  """
  @operation "oidc-read-provider-open-id-configuration"
  @spec oidc_read_provider_open_id_configuration(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_read_provider_open_id_configuration(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/oidc/provider/#{ExBao.Operation.escape(name)}/.well-known/openid-configuration",
      opts,
      []
    )
  end

  @doc ~S"""
  Retrieve public keys

  `GET /v1/identity/oidc/provider/{name}/.well-known/keys` — needs no token

  ## Arguments

    * `name` — Name of the provider
  """
  @operation "oidc-read-provider-public-keys"
  @spec oidc_read_provider_public_keys(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_read_provider_public_keys(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/oidc/provider/#{ExBao.Operation.escape(name)}/.well-known/keys",
      opts,
      []
    )
  end

  @doc ~S"""
  Retrieve public keys

  `GET /v1/identity/oidc/.well-known/keys` — needs no token
  """
  @operation "oidc-read-public-keys"
  @spec oidc_read_public_keys(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def oidc_read_public_keys(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "identity/oidc/.well-known/keys", opts, [])
  end

  @doc ~S"""
  CRUD operations on OIDC Roles

  `GET /v1/identity/oidc/role/{name}`

  ## Arguments

    * `name` — Name of the role
  """
  @operation "oidc-read-role"
  @spec oidc_read_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_read_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/oidc/role/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  CRUD operations for OIDC scopes.

  `GET /v1/identity/oidc/scope/{name}`

  ## Arguments

    * `name` — Name of the scope
  """
  @operation "oidc-read-scope"
  @spec oidc_read_scope(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_read_scope(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/oidc/scope/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Rotate a named OIDC key.

  `POST /v1/identity/oidc/key/{name}/rotate`

  ## Arguments

    * `name` — Name of the key

  ## Options

    * `:verification_ttl` (seconds) — Controls how long the public portion of a key will be available for verification after being rotated. Setting verification_ttl here will override the verification_ttl set on the key.
  """
  @operation "oidc-rotate-key"
  @spec oidc_rotate_key(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_rotate_key(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "identity/oidc/key/#{ExBao.Operation.escape(name)}/rotate",
      opts,
      body: [:verification_ttl]
    )
  end

  @doc ~S"""
  CRUD operations for OIDC assignments.

  `POST /v1/identity/oidc/assignment/{name}`

  ## Arguments

    * `name` — Name of the assignment

  ## Options

    * `:entity_ids` (array) — Comma separated string or array of identity entity IDs
    * `:group_ids` (array) — Comma separated string or array of identity group IDs
  """
  @operation "oidc-write-assignment"
  @spec oidc_write_assignment(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_write_assignment(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "identity/oidc/assignment/#{ExBao.Operation.escape(name)}",
      opts,
      body: [:entity_ids, :group_ids]
    )
  end

  @doc ~S"""
  CRUD operations for OIDC clients.

  `POST /v1/identity/oidc/client/{name}`

  ## Arguments

    * `name` — Name of the client.

  ## Options

    * `:access_token_ttl` (seconds) — The time-to-live for access tokens obtained by the client. Defaults to `"24h"`.
    * `:assignments` (array) — Comma separated string or array of assignment resources.
    * `:authorization_code` (boolean) — Whether or not to authorization code flow is allowed in this provider Defaults to `true`.
    * `:client_credentials` (boolean) — Whether or not to client credentials flow is allowed in this provider Defaults to `false`.
    * `:client_type` (string) — The client type based on its ability to maintain confidentiality of credentials. The following client types are supported: 'confidential', 'public'. Defaults to 'confidential'. Defaults to `"confidential"`.
    * `:id_token_ttl` (seconds) — The time-to-live for ID tokens obtained by the client. Defaults to `"24h"`.
    * `:key` (string) — A reference to a named key resource. Cannot be modified after creation. Defaults to the 'default' key. Defaults to `"default"`.
    * `:redirect_uris` (array) — Comma separated string or array of redirect URIs used by the client. One of these values must exactly match the redirect_uri parameter value used in each authentication request.
  """
  @operation "oidc-write-client"
  @spec oidc_write_client(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_write_client(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "identity/oidc/client/#{ExBao.Operation.escape(name)}",
      opts,
      body: [
        :access_token_ttl,
        :assignments,
        :authorization_code,
        :client_credentials,
        :client_type,
        :id_token_ttl,
        :key,
        :redirect_uris
      ]
    )
  end

  @doc ~S"""
  CRUD operations for OIDC keys.

  `POST /v1/identity/oidc/key/{name}`

  ## Arguments

    * `name` — Name of the key

  ## Options

    * `:algorithm` (string) — Signing algorithm to use. This will default to RS256. Defaults to `"RS256"`.
    * `:allowed_client_ids` (array) — Comma separated string or array of role client ids allowed to use this key for signing. If empty no roles are allowed. If "*" all roles are allowed.
    * `:rotation_period` (seconds) — How often to generate a new keypair. Defaults to `"24h"`.
    * `:verification_ttl` (seconds) — Controls how long the public portion of a key will be available for verification after being rotated. Defaults to `"24h"`.
  """
  @operation "oidc-write-key"
  @spec oidc_write_key(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_write_key(server, name, opts \\ []) do
    ExBao.Operation.call(server, :post, "identity/oidc/key/#{ExBao.Operation.escape(name)}", opts,
      body: [:algorithm, :allowed_client_ids, :rotation_period, :verification_ttl]
    )
  end

  @doc ~S"""
  CRUD operations for OIDC providers.

  `POST /v1/identity/oidc/provider/{name}`

  ## Arguments

    * `name` — Name of the provider

  ## Options

    * `:allowed_client_ids` (array) — The client IDs that are permitted to use the provider
    * `:issuer` (string) — Specifies what will be used for the iss claim of ID tokens.
    * `:scopes_supported` (array) — The scopes supported for requesting on the provider
  """
  @operation "oidc-write-provider"
  @spec oidc_write_provider(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_write_provider(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "identity/oidc/provider/#{ExBao.Operation.escape(name)}",
      opts,
      body: [:allowed_client_ids, :issuer, :scopes_supported]
    )
  end

  @doc ~S"""
  CRUD operations on OIDC Roles

  `POST /v1/identity/oidc/role/{name}`

  ## Arguments

    * `name` — Name of the role

  ## Options

    * `:client_id` (string) — Optional client_id
    * `:key` (string, required) — The OIDC key to use for generating tokens. The specified key must already exist.
    * `:template` (string) — The template string to use for generating tokens. This may be in string-ified JSON or base64 format.
    * `:ttl` (seconds) — TTL of the tokens generated against the role. Defaults to `"24h"`.
  """
  @operation "oidc-write-role"
  @spec oidc_write_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_write_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "identity/oidc/role/#{ExBao.Operation.escape(name)}",
      opts,
      body: [:client_id, :key, :template, :ttl],
      required: [:key]
    )
  end

  @doc ~S"""
  CRUD operations for OIDC scopes.

  `POST /v1/identity/oidc/scope/{name}`

  ## Arguments

    * `name` — Name of the scope

  ## Options

    * `:description` (string) — The description of the scope
    * `:template` (string) — The template string to use for the scope. This may be in string-ified JSON or base64 format.
  """
  @operation "oidc-write-scope"
  @spec oidc_write_scope(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def oidc_write_scope(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "identity/oidc/scope/#{ExBao.Operation.escape(name)}",
      opts,
      body: [:description, :template]
    )
  end

  @doc ~S"""
  Create a new alias.

  `POST /v1/identity/persona`

  ## Options

    * `:entity_id` (string) — Entity ID to which this persona belongs to
    * `:id` (string) — ID of the persona
    * `:metadata` (kvpairs) — Metadata to be associated with the persona. In CLI, this parameter can be repeated multiple times, and it all gets merged together. For example: bao <command> <path> metadata=key1=value1 metadata=key2=value2
    * `:mount_accessor` (string) — Mount accessor to which this persona belongs to
    * `:name` (string) — Name of the persona
  """
  @operation "persona-create"
  @spec persona_create(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def persona_create(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "identity/persona", opts,
      body: [:entity_id, :id, :metadata, :mount_accessor, :name]
    )
  end

  @doc ~S"""
  Update, read or delete an alias ID.

  `DELETE /v1/identity/persona/id/{id}`

  ## Arguments

    * `id` — ID of the persona
  """
  @operation "persona-delete-by-id"
  @spec persona_delete_by_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def persona_delete_by_id(server, id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "identity/persona/id/#{ExBao.Operation.escape(id)}",
      opts,
      []
    )
  end

  @doc ~S"""
  List all the alias IDs.

  `GET /v1/identity/persona/id`
  """
  @operation "persona-list-by-id"
  @spec persona_list_by_id(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def persona_list_by_id(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "identity/persona/id", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Update, read or delete an alias ID.

  `GET /v1/identity/persona/id/{id}`

  ## Arguments

    * `id` — ID of the persona
  """
  @operation "persona-read-by-id"
  @spec persona_read_by_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def persona_read_by_id(server, id, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "identity/persona/id/#{ExBao.Operation.escape(id)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Update, read or delete an alias ID.

  `POST /v1/identity/persona/id/{id}`

  ## Arguments

    * `id` — ID of the persona

  ## Options

    * `:entity_id` (string) — Entity ID to which this persona should be tied to
    * `:metadata` (kvpairs) — Metadata to be associated with the persona. In CLI, this parameter can be repeated multiple times, and it all gets merged together. For example: bao <command> <path> metadata=key1=value1 metadata=key2=value2
    * `:mount_accessor` (string) — Mount accessor to which this persona belongs to
    * `:name` (string) — Name of the persona
  """
  @operation "persona-update-by-id"
  @spec persona_update_by_id(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def persona_update_by_id(server, id, opts \\ []) do
    ExBao.Operation.call(server, :post, "identity/persona/id/#{ExBao.Operation.escape(id)}", opts,
      body: [:entity_id, :metadata, :mount_accessor, :name]
    )
  end

  # ── end of generated ──
end
