defmodule ExBao.Kubernetes do
  @moduledoc """
    The Kubernetes secrets engine: service account tokens.

    Generated from OpenBao's OpenAPI specification by `mix bao.gen`. One
    function per endpoint: path parameters are arguments, every other field
    is an option, and the answer is the server's own JSON body. An option
    the endpoint does not accept raises `ArgumentError` rather than being
    sent and ignored.
    
    Every function takes `:mount`, `"kubernetes"` by default.
  """

  use ExBao.Operation

  # ── generated by `mix bao.gen` from OpenBao 2.6.2 ──
  # Everything down to the closing marker is rewritten on every run. To
  # curate a function, move it above this block and keep its `@operation`:
  # the next run sees it there and stops generating it.

  @doc ~S"""
  Checks the Kubernetes configuration is valid.

  `GET /v1/kubernetes/check`

  ## Options

    * `:mount` — where the engine is mounted, `"kubernetes"` by default.
  """
  @operation "kubernetes-check-configuration"
  @spec check_configuration(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def check_configuration(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "kubernetes")}/check",
      opts,
      []
    )
  end

  @doc ~S"""
  Configure the Kubernetes secret engine plugin.

  `POST /v1/kubernetes/config`

  ## Options

    * `:disable_local_ca_jwt` (boolean) — Disable defaulting to the local CA certificate and service account JWT when running in a Kubernetes pod. Defaults to `false`.
    * `:kubernetes_ca_cert` (string) — PEM encoded CA certificate to use to verify the Kubernetes API server certificate. Defaults to the local pod's CA if found.
    * `:kubernetes_host` (string) — Kubernetes API URL to connect to. Defaults to https://$KUBERNETES_SERVICE_HOST:KUBERNETES_SERVICE_PORT if those environment variables are set.
    * `:service_account_jwt` (string) — The JSON web token of the service account used by the secret engine to manage Kubernetes credentials. Defaults to the local pod's JWT if found.
    * `:mount` — where the engine is mounted, `"kubernetes"` by default.
  """
  @operation "kubernetes-configure"
  @spec configure(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def configure(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "kubernetes")}/config",
      opts,
      body: [:disable_local_ca_jwt, :kubernetes_ca_cert, :kubernetes_host, :service_account_jwt]
    )
  end

  @doc ~S"""
  Configure the Kubernetes secret engine plugin.

  `DELETE /v1/kubernetes/config`

  ## Options

    * `:mount` — where the engine is mounted, `"kubernetes"` by default.
  """
  @operation "kubernetes-delete-configuration"
  @spec delete_configuration(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def delete_configuration(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "#{ExBao.Operation.mount(opts, "kubernetes")}/config",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage the roles that can be created with this secrets engine.

  `DELETE /v1/kubernetes/roles/{name}`

  ## Arguments

    * `name` — Name of the role

  ## Options

    * `:mount` — where the engine is mounted, `"kubernetes"` by default.
  """
  @operation "kubernetes-delete-role"
  @spec delete_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "#{ExBao.Operation.mount(opts, "kubernetes")}/roles/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Request Kubernetes service account credentials for a given OpenBao role.

  `POST /v1/kubernetes/creds/{name}`

  ## Arguments

    * `name` — Name of the OpenBao role

  ## Options

    * `:audiences` (array) — The intended audiences of the generated credentials
    * `:cluster_role_binding` (boolean) — If true, generate a ClusterRoleBinding to grant permissions across the whole cluster instead of within a namespace. Requires the OpenBao role to have kubernetes_role_type set to ClusterRole.
    * `:kubernetes_namespace` (string, required) — The name of the Kubernetes namespace in which to generate the credentials
    * `:ttl` (seconds) — The TTL of the generated credentials
    * `:mount` — where the engine is mounted, `"kubernetes"` by default.
  """
  @operation "kubernetes-generate-credentials"
  @spec generate_credentials(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def generate_credentials(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "kubernetes")}/creds/#{ExBao.Operation.escape(name)}",
      opts,
      body: [:audiences, :cluster_role_binding, :kubernetes_namespace, :ttl],
      required: [:kubernetes_namespace]
    )
  end

  @doc ~S"""
  List the existing roles in this secrets engine.

  `GET /v1/kubernetes/roles`

  ## Options

    * `:mount` — where the engine is mounted, `"kubernetes"` by default.
  """
  @operation "kubernetes-list-roles"
  @spec list_roles(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def list_roles(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "#{ExBao.Operation.mount(opts, "kubernetes")}/roles", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Configure the Kubernetes secret engine plugin.

  `GET /v1/kubernetes/config`

  ## Options

    * `:mount` — where the engine is mounted, `"kubernetes"` by default.
  """
  @operation "kubernetes-read-configuration"
  @spec read_configuration(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def read_configuration(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "kubernetes")}/config",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage the roles that can be created with this secrets engine.

  `GET /v1/kubernetes/roles/{name}`

  ## Arguments

    * `name` — Name of the role

  ## Options

    * `:mount` — where the engine is mounted, `"kubernetes"` by default.
  """
  @operation "kubernetes-read-role"
  @spec read_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "kubernetes")}/roles/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage the roles that can be created with this secrets engine.

  `POST /v1/kubernetes/roles/{name}`

  ## Arguments

    * `name` — Name of the role

  ## Options

    * `:allowed_kubernetes_namespace_selector` (string) — A label selector for Kubernetes namespaces in which credentials can be generated. Accepts either a JSON or YAML object. If set with allowed_kubernetes_namespaces, the conditions are conjuncted.
    * `:allowed_kubernetes_namespaces` (array) — A list of the Kubernetes namespaces in which credentials can be generated. If set to "*" all namespaces are allowed.
    * `:extra_annotations` (kvpairs) — Additional annotations to apply to all generated Kubernetes objects.
    * `:extra_labels` (kvpairs) — Additional labels to apply to all generated Kubernetes objects.
    * `:generated_role_rules` (string) — The Role or ClusterRole rules to use when generating a role. Accepts either a JSON or YAML object. If set, the entire chain of Kubernetes objects will be generated.
    * `:kubernetes_role_name` (string) — The pre-existing Role or ClusterRole to bind a generated service account to. If set, Kubernetes token, service account, and role binding objects will be created.
    * `:kubernetes_role_type` (string) — Specifies whether the Kubernetes role is a Role or ClusterRole. Defaults to `"Role"`.
    * `:name_template` (string) — The name template to use when generating service accounts, roles and role bindings. If unset, a default template is used.
    * `:service_account_name` (string) — The pre-existing service account to generate tokens for. Mutually exclusive with all role parameters. If set, only a Kubernetes service account token will be created.
    * `:token_default_audiences` (array) — The default audiences for generated Kubernetes service account tokens. If not set or set to "", will use k8s cluster default.
    * `:token_default_ttl` (seconds) — The default ttl for generated Kubernetes service account tokens. If not set or set to 0, will use system default.
    * `:token_max_ttl` (seconds) — The maximum ttl for generated Kubernetes service account tokens. If not set or set to 0, will use system default.
    * `:mount` — where the engine is mounted, `"kubernetes"` by default.
  """
  @operation "kubernetes-write-role"
  @spec write_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "kubernetes")}/roles/#{ExBao.Operation.escape(name)}",
      opts,
      body: [
        :allowed_kubernetes_namespace_selector,
        :allowed_kubernetes_namespaces,
        :extra_annotations,
        :extra_labels,
        :generated_role_rules,
        :kubernetes_role_name,
        :kubernetes_role_type,
        :name_template,
        :service_account_name,
        :token_default_audiences,
        :token_default_ttl,
        :token_max_ttl
      ]
    )
  end

  # ── end of generated ──
end
