defmodule ExBao.KV do
  @moduledoc """
    Version 2 of the key/value secrets engine: versioned secrets and their metadata.

    Generated from OpenBao's OpenAPI specification by `mix bao.gen`. One
    function per endpoint: path parameters are arguments, every other field
    is an option, and the answer is the server's own JSON body. An option
    the endpoint does not accept raises `ArgumentError` rather than being
    sent and ignored.
    
    Every function takes `:mount`, `"secret"` by default.
  """

  use ExBao.Operation

  # ── generated by `mix bao.gen` from OpenBao 2.6.2 ──
  # Everything down to the closing marker is rewritten on every run. To
  # curate a function, move it above this block and keep its `@operation`:
  # the next run sees it there and stops generating it.

  @doc ~S"""
  Write, Patch, Read, and Delete data in the Key-Value Store.

  `DELETE /v1/secret/data/{path}`

  ## Arguments

    * `path` — Location of the secret.

  ## Options

    * `:mount` — where the engine is mounted, `"secret"` by default.
  """
  @operation "kv-delete-data-path"
  @spec delete_data_path(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_data_path(server, path, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "#{ExBao.Operation.mount(opts, "secret")}/data/#{ExBao.Operation.escape_path(path)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Allows interaction with key metadata and settings in the KV store.

  `DELETE /v1/secret/metadata/{path}`

  ## Arguments

    * `path` — Location of the secret.

  ## Options

    * `:mount` — where the engine is mounted, `"secret"` by default.
  """
  @operation "kv-delete-metadata-path"
  @spec delete_metadata_path(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_metadata_path(server, path, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "#{ExBao.Operation.mount(opts, "secret")}/metadata/#{ExBao.Operation.escape_path(path)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Write, Patch, Read, and Delete data in the Key-Value Store.

  `PATCH /v1/secret/data/{path}`

  ## Arguments

    * `path` — Location of the secret.

  ## Options

    * `:data` (map) — The contents of the data map will be stored and returned on read.
    * `:options` (map) — Options for writing a KV entry. Set the "cas" value to use a Check-And-Set operation. If not set the write will be allowed. If set to 0 a write will only be allowed if the key doesn’t exist. If the index is non-zero the write will only be allowed if the key’s current version matches the version specified in the cas parameter.
    * `:version` (integer) — If provided during a read, the value at the version number will be returned
    * `:mount` — where the engine is mounted, `"secret"` by default.
  """
  @operation "kv-patch-data-path"
  @spec patch_data_path(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def patch_data_path(server, path, opts \\ []) do
    ExBao.Operation.call(
      server,
      :patch,
      "#{ExBao.Operation.mount(opts, "secret")}/data/#{ExBao.Operation.escape_path(path)}",
      opts,
      body: [:data, :options, :version],
      content_type: "application/merge-patch+json"
    )
  end

  @doc ~S"""
  Allows interaction with key metadata and settings in the KV store.

  `PATCH /v1/secret/metadata/{path}`

  ## Arguments

    * `path` — Location of the secret.

  ## Options

    * `:after` (string) — Optional entry to list begin listing after, not required to exist. Only used for listing.
    * `:cas_required` (boolean) — If true the key will require the cas parameter to be set on all write requests. If false, the backend’s configuration will be used.
    * `:custom_metadata` (map) — User-provided key-value pairs that are used to describe arbitrary and version-agnostic information about a secret.
    * `:delete_version_after` (seconds) — The length of time before a version is deleted. If not set, the backend's configured delete_version_after is used. Cannot be greater than the backend's delete_version_after. A zero duration clears the current setting. A negative duration will cause an error.
    * `:limit` (integer) — Optional number of entries to return; defaults to all entries. Only used for listing.
    * `:max_versions` (integer) — The number of versions to keep. If not set, the backend’s configured max version is used.
    * `:metadata_cas` (integer) — Check-and-set parameter for metadata updates. Must match the current metadata version for the update to succeed. Set to 0 for initial metadata creation.
    * `:metadata_cas_required` (boolean) — If true the key will require the cas parameter to be set on all metadata update requests. If false, the backend's configuration will be used.
    * `:mount` — where the engine is mounted, `"secret"` by default.
  """
  @operation "kv-patch-metadata-path"
  @spec patch_metadata_path(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def patch_metadata_path(server, path, opts \\ []) do
    ExBao.Operation.call(
      server,
      :patch,
      "#{ExBao.Operation.mount(opts, "secret")}/metadata/#{ExBao.Operation.escape_path(path)}",
      opts,
      body: [
        :after,
        :cas_required,
        :custom_metadata,
        :delete_version_after,
        :limit,
        :max_versions,
        :metadata_cas,
        :metadata_cas_required
      ],
      content_type: "application/merge-patch+json"
    )
  end

  @doc ~S"""
  Read the backend level settings.

  `GET /v1/secret/config`

  Configures settings for the KV store

  ## Options

    * `:mount` — where the engine is mounted, `"secret"` by default.
  """
  @operation "kv-read-config"
  @spec read_config(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def read_config(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "secret")}/config",
      opts,
      []
    )
  end

  @doc ~S"""
  Write, Patch, Read, and Delete data in the Key-Value Store.

  `GET /v1/secret/data/{path}`

  ## Arguments

    * `path` — Location of the secret.

  ## Options

    * `:mount` — where the engine is mounted, `"secret"` by default.
  """
  @operation "kv-read-data-path"
  @spec read_data_path(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_data_path(server, path, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "secret")}/data/#{ExBao.Operation.escape_path(path)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Allows interaction with key metadata and settings in the KV store.

  `GET /v1/secret/metadata/{path}`

  ## Arguments

    * `path` — Location of the secret.

  ## Options

    * `:list` (string) — Return a list if `true`
    * `:scan` (string) — Return a recursive list if `true`
    * `:mount` — where the engine is mounted, `"secret"` by default.
  """
  @operation "kv-read-metadata-path"
  @spec read_metadata_path(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_metadata_path(server, path, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "secret")}/metadata/#{ExBao.Operation.escape_path(path)}",
      opts,
      query: [:list, :scan]
    )
  end

  @doc ~S"""
  Read the structure of a secret entry from the Key-Value store with the values removed.

  `GET /v1/secret/subkeys/{path}`

  ## Arguments

    * `path` — Location of the secret.

  ## Options

    * `:mount` — where the engine is mounted, `"secret"` by default.
  """
  @operation "kv-read-subkeys-path"
  @spec read_subkeys_path(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_subkeys_path(server, path, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "secret")}/subkeys/#{ExBao.Operation.escape_path(path)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Allows listing detailed information about key metadata in the KV store.

  `GET /v1/secret/detailed-metadata/{path}`

  ## Arguments

    * `path` — Location of the secret.

  ## Options

    * `:mount` — where the engine is mounted, `"secret"` by default.
  """
  @operation "kv-scan-detailed-metadata-path"
  @spec scan_detailed_metadata_path(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def scan_detailed_metadata_path(server, path, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "secret")}/detailed-metadata/#{ExBao.Operation.escape_path(path)}",
      opts,
      fixed_query: %{"list" => "true", "scan" => "true"}
    )
  end

  @doc ~S"""
  Configure backend level settings that are applied to every key in the key-value store.

  `POST /v1/secret/config`

  Configures settings for the KV store

  ## Options

    * `:cas_required` (boolean) — If true, the backend will require the cas parameter to be set for each write
    * `:delete_version_after` (seconds) — If set, the length of time before a version is deleted. A negative duration disables the use of delete_version_after on all keys. A zero duration clears the current setting. Accepts a Go duration format string.
    * `:max_versions` (integer) — The number of versions to keep for each key. Defaults to 10
    * `:metadata_cas_required` (boolean) — If true, the backend will require the metadata_cas parameter to be set for each metadata update
    * `:mount` — where the engine is mounted, `"secret"` by default.
  """
  @operation "kv-write-config"
  @spec write_config(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def write_config(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "#{ExBao.Operation.mount(opts, "secret")}/config", opts,
      body: [:cas_required, :delete_version_after, :max_versions, :metadata_cas_required]
    )
  end

  @doc ~S"""
  Write, Patch, Read, and Delete data in the Key-Value Store.

  `POST /v1/secret/data/{path}`

  ## Arguments

    * `path` — Location of the secret.

  ## Options

    * `:data` (map) — The contents of the data map will be stored and returned on read.
    * `:options` (map) — Options for writing a KV entry. Set the "cas" value to use a Check-And-Set operation. If not set the write will be allowed. If set to 0 a write will only be allowed if the key doesn’t exist. If the index is non-zero the write will only be allowed if the key’s current version matches the version specified in the cas parameter.
    * `:version` (integer) — If provided during a read, the value at the version number will be returned
    * `:mount` — where the engine is mounted, `"secret"` by default.
  """
  @operation "kv-write-data-path"
  @spec write_data_path(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_data_path(server, path, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "secret")}/data/#{ExBao.Operation.escape_path(path)}",
      opts,
      body: [:data, :options, :version]
    )
  end

  @doc ~S"""
  Marks one or more versions as deleted in the KV store.

  `POST /v1/secret/delete/{path}`

  ## Arguments

    * `path` — Location of the secret.

  ## Options

    * `:versions` (array) — The versions to be archived. The versioned data will not be deleted, but it will no longer be returned in normal get requests.
    * `:mount` — where the engine is mounted, `"secret"` by default.
  """
  @operation "kv-write-delete-path"
  @spec write_delete_path(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_delete_path(server, path, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "secret")}/delete/#{ExBao.Operation.escape_path(path)}",
      opts,
      body: [:versions]
    )
  end

  @doc ~S"""
  Permanently removes one or more versions in the KV store

  `POST /v1/secret/destroy/{path}`

  ## Arguments

    * `path` — Location of the secret.

  ## Options

    * `:versions` (array) — The versions to destroy. Their data will be permanently deleted.
    * `:mount` — where the engine is mounted, `"secret"` by default.
  """
  @operation "kv-write-destroy-path"
  @spec write_destroy_path(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_destroy_path(server, path, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "secret")}/destroy/#{ExBao.Operation.escape_path(path)}",
      opts,
      body: [:versions]
    )
  end

  @doc ~S"""
  Allows interaction with key metadata and settings in the KV store.

  `POST /v1/secret/metadata/{path}`

  ## Arguments

    * `path` — Location of the secret.

  ## Options

    * `:after` (string) — Optional entry to list begin listing after, not required to exist. Only used for listing.
    * `:cas_required` (boolean) — If true the key will require the cas parameter to be set on all write requests. If false, the backend’s configuration will be used.
    * `:custom_metadata` (map) — User-provided key-value pairs that are used to describe arbitrary and version-agnostic information about a secret.
    * `:delete_version_after` (seconds) — The length of time before a version is deleted. If not set, the backend's configured delete_version_after is used. Cannot be greater than the backend's delete_version_after. A zero duration clears the current setting. A negative duration will cause an error.
    * `:limit` (integer) — Optional number of entries to return; defaults to all entries. Only used for listing.
    * `:max_versions` (integer) — The number of versions to keep. If not set, the backend’s configured max version is used.
    * `:metadata_cas` (integer) — Check-and-set parameter for metadata updates. Must match the current metadata version for the update to succeed. Set to 0 for initial metadata creation.
    * `:metadata_cas_required` (boolean) — If true the key will require the cas parameter to be set on all metadata update requests. If false, the backend's configuration will be used.
    * `:mount` — where the engine is mounted, `"secret"` by default.
  """
  @operation "kv-write-metadata-path"
  @spec write_metadata_path(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_metadata_path(server, path, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "secret")}/metadata/#{ExBao.Operation.escape_path(path)}",
      opts,
      body: [
        :after,
        :cas_required,
        :custom_metadata,
        :delete_version_after,
        :limit,
        :max_versions,
        :metadata_cas,
        :metadata_cas_required
      ]
    )
  end

  @doc ~S"""
  Undeletes one or more versions from the KV store.

  `POST /v1/secret/undelete/{path}`

  ## Arguments

    * `path` — Location of the secret.

  ## Options

    * `:versions` (array) — The versions to unarchive. The versions will be restored and their data will be returned on normal get requests.
    * `:mount` — where the engine is mounted, `"secret"` by default.
  """
  @operation "kv-write-undelete-path"
  @spec write_undelete_path(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_undelete_path(server, path, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "secret")}/undelete/#{ExBao.Operation.escape_path(path)}",
      opts,
      body: [:versions]
    )
  end

  # ── end of generated ──
end
