defmodule ExBao.LDAP do
  @moduledoc """
    The LDAP secrets engine: static, dynamic and library accounts.

    Generated from OpenBao's OpenAPI specification by `mix bao.gen`. One
    function per endpoint: path parameters are arguments, every other field
    is an option, and the answer is the server's own JSON body. An option
    the endpoint does not accept raises `ArgumentError` rather than being
    sent and ignored.
    
    Every function takes `:mount`, `"ldap"` by default.
  """

  use ExBao.Operation

  # ── generated by `mix bao.gen` from OpenBao 2.6.2 ──
  # Everything down to the closing marker is rewritten on every run. To
  # curate a function, move it above this block and keep its `@operation`:
  # the next run sees it there and stops generating it.

  @doc ~S"""
  Configure the LDAP secrets engine plugin.

  `POST /v1/ldap/config`

  ## Options

    * `:anonymous_group_search` (boolean) — Use anonymous binds when performing LDAP group searches (if true the initial credentials will still be used for the initial connection test). Defaults to `false`.
    * `:binddn` (string) — LDAP DN for searching for the user DN (optional)
    * `:bindpass` (string) — LDAP password for searching for the user DN (optional)
    * `:case_sensitive_names` (boolean) — If true, case sensitivity will be used when comparing usernames and groups for matching policies.
    * `:certificate` (string) — CA certificate to use when verifying LDAP server certificate, must be x509 PEM encoded (optional)
    * `:client_tls_cert` (string) — Client certificate to provide to the LDAP server, must be x509 PEM encoded (optional)
    * `:client_tls_key` (string) — Client certificate key to provide to the LDAP server, must be x509 PEM encoded (optional)
    * `:connection_timeout` (seconds) — Timeout, in seconds, when attempting to connect to the LDAP server before trying the next URL in the configuration. Defaults to `"30s"`.
    * `:deny_null_bind` (boolean) — Denies an unauthenticated LDAP bind request if the user's password is empty; defaults to true Defaults to `true`.
    * `:dereference_aliases` (string) — When aliases should be dereferenced on search operations. Accepted values are 'never', 'finding', 'searching', 'always'. Defaults to 'never'. Defaults to `"never"`.
    * `:discoverdn` (boolean) — Use anonymous bind to discover the bind DN of a user (optional)
    * `:groupattr` (string) — LDAP attribute to follow on objects returned by <groupfilter> in order to enumerate user group membership. Examples: "cn" or "memberOf", etc. Default: cn Defaults to `"cn"`.
    * `:groupdn` (string) — LDAP search base to use for group membership search (eg: ou=Groups,dc=example,dc=org)
    * `:groupfilter` (string) — Go template for querying group membership of user (optional) The template can access the following context variables: UserDN, Username Example: (&(objectClass=group)(member:1.2.840.113556.1.4.1941:={{.UserDN}})) Default: (|(memberUid={{.Username}})(member={{.UserDN}})(uniqueMember={{.UserDN}})) Defaults to `"(|(memberUid={{.Username}})(member={{.UserDN}})(uniqueMember={{.UserDN}}))"`.
    * `:insecure_tls` (boolean) — Skip LDAP server SSL Certificate verification - VERY insecure (optional)
    * `:length` (integer, deprecated) — The desired length of passwords that OpenBao generates.
    * `:max_page_size` (integer) — If set to a value greater than 0, the LDAP backend will use the LDAP server's paged search control to request pages of up to the given size. This can be used to avoid hitting the LDAP server's maximum result size limit. Otherwise, the LDAP backend will not use the paged search control. Defaults to `0`.
    * `:max_ttl` (seconds) — The maximum password time-to-live.
    * `:password_policy` (string) — Password policy to use to generate passwords
    * `:request_timeout` (seconds) — Timeout, in seconds, for the connection when making requests against the server before returning back an error. Defaults to `"90s"`.
    * `:schema` (string) — The desired LDAP schema used when modifying user account passwords. Defaults to `"openldap"`.
    * `:skip_static_role_import_rotation` (boolean) — Whether to skip the 'import' rotation.
    * `:starttls` (boolean) — Issue a StartTLS command after establishing unencrypted connection (optional)
    * `:tls_max_version` (string) — Maximum TLS version to use. Accepted values are 'tls10', 'tls11', 'tls12' or 'tls13'. Defaults to 'tls12' Defaults to `"tls12"`.
    * `:tls_min_version` (string) — Minimum TLS version to use. Accepted values are 'tls10', 'tls11', 'tls12' or 'tls13'. Defaults to 'tls12' Defaults to `"tls12"`.
    * `:ttl` (seconds) — The default password time-to-live.
    * `:upndomain` (string) — Enables userPrincipalDomain login with [username]@UPNDomain (optional)
    * `:url` (string) — LDAP URL to connect to (default: ldap://127.0.0.1). Multiple URLs can be specified by concatenating them with commas; they will be tried in-order. Defaults to `"ldap://127.0.0.1"`.
    * `:use_pre111_group_cn_behavior` (boolean) — In Vault 1.1.1 (prior to OpenBao's fork), a fix for handling group CN values of different cases unfortunately introduced a regression that could cause previously defined groups to not be found due to a change in the resulting name. If set true, the pre-1.1.1 behavior for matching group CNs will be used. This is only needed in some upgrade scenarios for backwards compatibility. It is enabled by default if the config is upgraded but disabled by default on new configurations.
    * `:use_token_groups` (boolean) — If true, use the Active Directory tokenGroups constructed attribute of the user to find the group memberships. This will find all security groups including nested ones. Defaults to `false`.
    * `:userattr` (string) — Attribute used for users (default: cn) Defaults to `"cn"`.
    * `:userdn` (string) — LDAP domain to use for users (eg: ou=People,dc=example,dc=org)
    * `:userfilter` (string) — Go template for LDAP user search filer (optional) The template can access the following context variables: UserAttr, Username Default: ({{.UserAttr}}={{.Username}}) Defaults to `"({{.UserAttr}}={{.Username}})"`.
    * `:username_as_alias` (boolean) — If true, sets the alias name to the username Defaults to `false`.
    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-configure"
  @spec configure(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def configure(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "#{ExBao.Operation.mount(opts, "ldap")}/config", opts,
      body: [
        :anonymous_group_search,
        :binddn,
        :bindpass,
        :case_sensitive_names,
        :certificate,
        :client_tls_cert,
        :client_tls_key,
        :connection_timeout,
        :deny_null_bind,
        :dereference_aliases,
        :discoverdn,
        :groupattr,
        :groupdn,
        :groupfilter,
        :insecure_tls,
        :length,
        :max_page_size,
        :max_ttl,
        :password_policy,
        :request_timeout,
        :schema,
        :skip_static_role_import_rotation,
        :starttls,
        :tls_max_version,
        :tls_min_version,
        :ttl,
        :upndomain,
        :url,
        :use_pre111_group_cn_behavior,
        :use_token_groups,
        :userattr,
        :userdn,
        :userfilter,
        :username_as_alias
      ]
    )
  end

  @doc ~S"""
  Configure the LDAP secrets engine plugin.

  `DELETE /v1/ldap/config`

  ## Options

    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-delete-configuration"
  @spec delete_configuration(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def delete_configuration(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "#{ExBao.Operation.mount(opts, "ldap")}/config",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage the static roles that can be created with this backend.

  `DELETE /v1/ldap/role/{name}`

  ## Arguments

    * `name` — Name of the role (lowercase)

  ## Options

    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-delete-dynamic-role"
  @spec delete_dynamic_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_dynamic_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "#{ExBao.Operation.mount(opts, "ldap")}/role/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage the static roles that can be created with this backend.

  `DELETE /v1/ldap/static-role/{name}`

  ## Arguments

    * `name` — Name of the role

  ## Options

    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-delete-static-role"
  @spec delete_static_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_static_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "#{ExBao.Operation.mount(opts, "ldap")}/static-role/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Check service accounts in to the library.

  `POST /v1/ldap/library/{name}/check-in`

  ## Arguments

    * `name` — Name of the set.

  ## Options

    * `:service_account_names` (array) — The username/logon name for the service accounts to check in.
    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-library-check-in"
  @spec library_check_in(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def library_check_in(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "ldap")}/library/#{ExBao.Operation.escape(name)}/check-in",
      opts,
      body: [:service_account_names]
    )
  end

  @doc ~S"""
  Check a service account out from the library.

  `POST /v1/ldap/library/{name}/check-out`

  ## Arguments

    * `name` — Name of the set

  ## Options

    * `:ttl` (seconds) — The length of time before the check-out will expire, in seconds.
    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-library-check-out"
  @spec library_check_out(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def library_check_out(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "ldap")}/library/#{ExBao.Operation.escape(name)}/check-out",
      opts,
      body: [:ttl]
    )
  end

  @doc ~S"""
  Check the status of the service accounts in a library set.

  `GET /v1/ldap/library/{name}/status`

  Check the status of the service accounts in a library.

  ## Arguments

    * `name` — Name of the set.

  ## Options

    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-library-check-status"
  @spec library_check_status(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def library_check_status(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "ldap")}/library/#{ExBao.Operation.escape(name)}/status",
      opts,
      []
    )
  end

  @doc ~S"""
  Update a library set.

  `POST /v1/ldap/library/{name}`

  Build a library of service accounts that can be checked out.

  ## Arguments

    * `name` — Name of the set.

  ## Options

    * `:disable_check_in_enforcement` (boolean) — Disable the default behavior of requiring that check-ins are performed by the entity that checked them out. Defaults to `false`.
    * `:max_ttl` (seconds) — In seconds, the max amount of time a check-out's renewals should last. Defaults to 24 hours. Defaults to `86400`.
    * `:service_account_names` (array) — The username/logon name for the service accounts with which this set will be associated.
    * `:ttl` (seconds) — In seconds, the amount of time a check-out should last. Defaults to 24 hours. Defaults to `86400`.
    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-library-configure"
  @spec library_configure(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def library_configure(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "ldap")}/library/#{ExBao.Operation.escape(name)}",
      opts,
      body: [:disable_check_in_enforcement, :max_ttl, :service_account_names, :ttl]
    )
  end

  @doc ~S"""
  Delete a library set.

  `DELETE /v1/ldap/library/{name}`

  Build a library of service accounts that can be checked out.

  ## Arguments

    * `name` — Name of the set.

  ## Options

    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-library-delete"
  @spec library_delete(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def library_delete(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "#{ExBao.Operation.mount(opts, "ldap")}/library/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Check service accounts in to the library.

  `POST /v1/ldap/library/manage/{name}/check-in`

  Force checking service accounts in to the library.

  ## Arguments

    * `name` — Name of the set.

  ## Options

    * `:service_account_names` (array) — The username/logon name for the service accounts to check in.
    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-library-force-check-in"
  @spec library_force_check_in(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def library_force_check_in(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "ldap")}/library/manage/#{ExBao.Operation.escape(name)}/check-in",
      opts,
      body: [:service_account_names]
    )
  end

  @doc ~S"""
  List the name of each set of service accounts currently stored.

  `GET /v1/ldap/library`

  ## Options

    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-library-list"
  @spec library_list(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def library_list(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "#{ExBao.Operation.mount(opts, "ldap")}/library", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Read a library set.

  `GET /v1/ldap/library/{name}`

  Build a library of service accounts that can be checked out.

  ## Arguments

    * `name` — Name of the set.

  ## Options

    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-library-read"
  @spec library_read(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def library_read(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "ldap")}/library/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  List all the dynamic roles OpenBao is currently managing in LDAP.

  `GET /v1/ldap/role`

  ## Options

    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-list-dynamic-roles"
  @spec list_dynamic_roles(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def list_dynamic_roles(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "#{ExBao.Operation.mount(opts, "ldap")}/role", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  This path lists all the static roles OpenBao is currently managing within the LDAP system.

  `GET /v1/ldap/static-role`

  ## Options

    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-list-static-roles"
  @spec list_static_roles(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def list_static_roles(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "#{ExBao.Operation.mount(opts, "ldap")}/static-role", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Configure the LDAP secrets engine plugin.

  `GET /v1/ldap/config`

  ## Options

    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-read-configuration"
  @spec read_configuration(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def read_configuration(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "#{ExBao.Operation.mount(opts, "ldap")}/config", opts, [])
  end

  @doc ~S"""
  Manage the static roles that can be created with this backend.

  `GET /v1/ldap/role/{name}`

  ## Arguments

    * `name` — Name of the role (lowercase)

  ## Options

    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-read-dynamic-role"
  @spec read_dynamic_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_dynamic_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "ldap")}/role/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage the static roles that can be created with this backend.

  `GET /v1/ldap/static-role/{name}`

  ## Arguments

    * `name` — Name of the role

  ## Options

    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-read-static-role"
  @spec read_static_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_static_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "ldap")}/static-role/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Request LDAP credentials for a dynamic role. These credentials are created within the LDAP system when querying this endpoint.

  `GET /v1/ldap/creds/{name}`

  ## Arguments

    * `name` — Name of the dynamic role.

  ## Options

    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-request-dynamic-role-credentials"
  @spec request_dynamic_role_credentials(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def request_dynamic_role_credentials(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "ldap")}/creds/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Request LDAP credentials for a certain static role. These credentials are rotated periodically.

  `GET /v1/ldap/static-cred/{name}`

  ## Arguments

    * `name` — Name of the static role.

  ## Options

    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-request-static-role-credentials"
  @spec request_static_role_credentials(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def request_static_role_credentials(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "ldap")}/static-cred/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Request to rotate the root credentials OpenBao uses for the LDAP administrator account.

  `POST /v1/ldap/rotate-root`

  ## Options

    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-rotate-root-credentials"
  @spec rotate_root_credentials(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def rotate_root_credentials(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "ldap")}/rotate-root",
      opts,
      []
    )
  end

  @doc ~S"""
  Request to rotate the credentials for a static user account.

  `POST /v1/ldap/rotate-role/{name}`

  ## Arguments

    * `name` — Name of the static role

  ## Options

    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-rotate-static-role"
  @spec rotate_static_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def rotate_static_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "ldap")}/rotate-role/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage the static roles that can be created with this backend.

  `POST /v1/ldap/role/{name}`

  ## Arguments

    * `name` — Name of the role (lowercase)

  ## Options

    * `:creation_ldif` (string, required) — LDIF string used to create new entities within the LDAP system. This LDIF can be templated.
    * `:default_ttl` (seconds) — Default TTL for dynamic credentials
    * `:deletion_ldif` (string, required) — LDIF string used to delete entities created within the LDAP system. This LDIF can be templated.
    * `:max_ttl` (seconds) — Max TTL a dynamic credential can be extended to
    * `:rollback_ldif` (string) — LDIF string used to rollback changes in the event of a failure to create credentials. This LDIF can be templated.
    * `:username_template` (string) — The template used to create a username
    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-write-dynamic-role"
  @spec write_dynamic_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_dynamic_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "ldap")}/role/#{ExBao.Operation.escape(name)}",
      opts,
      body: [
        :creation_ldif,
        :default_ttl,
        :deletion_ldif,
        :max_ttl,
        :rollback_ldif,
        :username_template
      ],
      required: [:creation_ldif, :deletion_ldif]
    )
  end

  @doc ~S"""
  Manage the static roles that can be created with this backend.

  `POST /v1/ldap/static-role/{name}`

  ## Arguments

    * `name` — Name of the role

  ## Options

    * `:dn` (string) — The distinguished name of the entry to manage.
    * `:rotation_period` (seconds) — Period for automatic credential rotation of the given entry.
    * `:skip_import_rotation` (boolean) — Skip the initial pasword rotation on import (has no effect on updates)
    * `:username` (string) — The username/logon name for the entry with which this role will be associated.
    * `:mount` — where the engine is mounted, `"ldap"` by default.
  """
  @operation "ldap-write-static-role"
  @spec write_static_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_static_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "ldap")}/static-role/#{ExBao.Operation.escape(name)}",
      opts,
      body: [:dn, :rotation_period, :skip_import_rotation, :username]
    )
  end

  # ── end of generated ──
end
