defmodule ExBao.RabbitMQ do
  @moduledoc """
    The RabbitMQ secrets engine.

    Generated from OpenBao's OpenAPI specification by `mix bao.gen`. One
    function per endpoint: path parameters are arguments, every other field
    is an option, and the answer is the server's own JSON body. An option
    the endpoint does not accept raises `ArgumentError` rather than being
    sent and ignored.
    
    Every function takes `:mount`, `"rabbitmq"` by default.
  """

  use ExBao.Operation

  # ── generated by `mix bao.gen` from OpenBao 2.6.2 ──
  # Everything down to the closing marker is rewritten on every run. To
  # curate a function, move it above this block and keep its `@operation`:
  # the next run sees it there and stops generating it.

  @doc ~S"""
  Configure the connection URI, username, and password to talk to RabbitMQ management HTTP API.

  `POST /v1/rabbitmq/config/connection`

  ## Options

    * `:connection_uri` (string) — RabbitMQ Management URI
    * `:password` (string) — Password of the provided RabbitMQ management user
    * `:password_policy` (string) — Name of the password policy to use to generate passwords for dynamic credentials.
    * `:username` (string) — Username of a RabbitMQ management administrator
    * `:username_template` (string) — Template describing how dynamic usernames are generated.
    * `:verify_connection` (boolean) — If set, connection_uri is verified by actually connecting to the RabbitMQ management API Defaults to `true`.
    * `:mount` — where the engine is mounted, `"rabbitmq"` by default.
  """
  @operation "rabbit-mq-configure-connection"
  @spec configure_connection(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def configure_connection(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "rabbitmq")}/config/connection",
      opts,
      body: [
        :connection_uri,
        :password,
        :password_policy,
        :username,
        :username_template,
        :verify_connection
      ]
    )
  end

  @doc ~S"""
  Configure the lease parameters for generated credentials

  `POST /v1/rabbitmq/config/lease`

  ## Options

    * `:max_ttl` (seconds) — Duration after which the issued credentials should not be allowed to be renewed Defaults to `0`.
    * `:ttl` (seconds) — Duration before which the issued credentials needs renewal Defaults to `0`.
    * `:mount` — where the engine is mounted, `"rabbitmq"` by default.
  """
  @operation "rabbit-mq-configure-lease"
  @spec configure_lease(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def configure_lease(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "rabbitmq")}/config/lease",
      opts,
      body: [:max_ttl, :ttl]
    )
  end

  @doc ~S"""
  Manage the roles that can be created with this backend.

  `DELETE /v1/rabbitmq/roles/{name}`

  ## Arguments

    * `name` — Name of the role.

  ## Options

    * `:mount` — where the engine is mounted, `"rabbitmq"` by default.
  """
  @operation "rabbit-mq-delete-role"
  @spec delete_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "#{ExBao.Operation.mount(opts, "rabbitmq")}/roles/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage the roles that can be created with this backend.

  `GET /v1/rabbitmq/roles`

  ## Options

    * `:mount` — where the engine is mounted, `"rabbitmq"` by default.
  """
  @operation "rabbit-mq-list-roles"
  @spec list_roles(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def list_roles(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "#{ExBao.Operation.mount(opts, "rabbitmq")}/roles", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Configure the lease parameters for generated credentials

  `GET /v1/rabbitmq/config/lease`

  ## Options

    * `:mount` — where the engine is mounted, `"rabbitmq"` by default.
  """
  @operation "rabbit-mq-read-lease-configuration"
  @spec read_lease_configuration(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def read_lease_configuration(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "rabbitmq")}/config/lease",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage the roles that can be created with this backend.

  `GET /v1/rabbitmq/roles/{name}`

  ## Arguments

    * `name` — Name of the role.

  ## Options

    * `:mount` — where the engine is mounted, `"rabbitmq"` by default.
  """
  @operation "rabbit-mq-read-role"
  @spec read_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "rabbitmq")}/roles/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Request RabbitMQ credentials for a certain role.

  `GET /v1/rabbitmq/creds/{name}`

  ## Arguments

    * `name` — Name of the role.

  ## Options

    * `:mount` — where the engine is mounted, `"rabbitmq"` by default.
  """
  @operation "rabbit-mq-request-credentials"
  @spec request_credentials(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def request_credentials(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "rabbitmq")}/creds/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage the roles that can be created with this backend.

  `POST /v1/rabbitmq/roles/{name}`

  ## Arguments

    * `name` — Name of the role.

  ## Options

    * `:tags` (string) — Comma-separated list of tags for this role.
    * `:vhost_topics` (string) — A nested map of virtual hosts and exchanges to topic permissions.
    * `:vhosts` (string) — A map of virtual hosts to permissions.
    * `:mount` — where the engine is mounted, `"rabbitmq"` by default.
  """
  @operation "rabbit-mq-write-role"
  @spec write_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_role(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "rabbitmq")}/roles/#{ExBao.Operation.escape(name)}",
      opts,
      body: [:tags, :vhost_topics, :vhosts]
    )
  end

  # ── end of generated ──
end
