defmodule ExBao.SSH do
  @moduledoc """
    The SSH secrets engine: signed certificates and one-time passwords.

    Generated from OpenBao's OpenAPI specification by `mix bao.gen`. One
    function per endpoint: path parameters are arguments, every other field
    is an option, and the answer is the server's own JSON body. An option
    the endpoint does not accept raises `ArgumentError` rather than being
    sent and ignored.
    
    Every function takes `:mount`, `"ssh"` by default.
  """

  use ExBao.Operation

  # ── generated by `mix bao.gen` from OpenBao 2.6.2 ──
  # Everything down to the closing marker is rewritten on every run. To
  # curate a function, move it above this block and keep its `@operation`:
  # the next run sees it there and stops generating it.

  @doc ~S"""
  Configure the default SSH issuer used for signing and verification operations.

  `POST /v1/ssh/config/ca`

  ## Options

    * `:generate_signing_key` (boolean) — Generate SSH key pair internally rather than use the private_key and public_key fields. Defaults to `true`.
    * `:issuer_name` (string) — Optional issuer name that can be used to identify the issuer.
    * `:key_bits` (integer) — Specifies the desired key bits when generating variable-length keys (such as when key_type="ssh-rsa") or which NIST P-curve to use when key_type="ec" (256, 384, or 521). Defaults to `0`.
    * `:key_type` (string) — Specifies the desired key type when generating; could be a OpenSSH key type identifier (ssh-rsa, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521, or ssh-ed25519) or an algorithm (rsa, ec, ed25519). Defaults to `"ssh-rsa"`.
    * `:private_key` (string) — Private half of the SSH key that will be used to sign certificates.
    * `:public_key` (string) — Public half of the SSH key that will be used to sign certificates.
    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-configure-default-ca"
  @spec configure_default_ca(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def configure_default_ca(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "#{ExBao.Operation.mount(opts, "ssh")}/config/ca", opts,
      body: [:generate_signing_key, :issuer_name, :key_bits, :key_type, :private_key, :public_key]
    )
  end

  @doc ~S"""
  Assign zero address as default CIDR block for select roles.

  `POST /v1/ssh/config/zeroaddress`

  ## Options

    * `:roles` (array) — [Required] Comma separated list of role names which allows credentials to be requested for any IP address. CIDR blocks previously registered under these roles will be ignored.
    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-configure-zero-address"
  @spec configure_zero_address(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def configure_zero_address(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "ssh")}/config/zeroaddress",
      opts,
      body: [:roles]
    )
  end

  @doc ~S"""
  Fetch a single issuer.

  `DELETE /v1/ssh/issuer/{issuer_ref}`

  ## Arguments

    * `issuer_ref` — Reference to a existing issuer; either "default" for the configured default issuer, an identifier or the name assigned to the issuer.

  ## Options

    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-delete-issuer"
  @spec delete_issuer(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_issuer(server, issuer_ref, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "#{ExBao.Operation.mount(opts, "ssh")}/issuer/#{ExBao.Operation.escape(issuer_ref)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage the 'roles' that can be created with this backend.

  `DELETE /v1/ssh/roles/{role}`

  ## Arguments

    * `role` — [Required for all types] Name of the role being created.

  ## Options

    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-delete-role"
  @spec delete_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_role(server, role, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "#{ExBao.Operation.mount(opts, "ssh")}/roles/#{ExBao.Operation.escape(role)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Assign zero address as default CIDR block for select roles.

  `DELETE /v1/ssh/config/zeroaddress`

  ## Options

    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-delete-zero-address-configuration"
  @spec delete_zero_address_configuration(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def delete_zero_address_configuration(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "#{ExBao.Operation.mount(opts, "ssh")}/config/zeroaddress",
      opts,
      []
    )
  end

  @doc ~S"""
  Creates a credential for establishing SSH connection with the remote host.

  `POST /v1/ssh/creds/{role}`

  ## Arguments

    * `role` — [Required] Name of the role

  ## Options

    * `:ip` (string) — [Required] IP of the remote host
    * `:username` (string) — [Optional] Username in remote host
    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-generate-credentials"
  @spec generate_credentials(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def generate_credentials(server, role, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "ssh")}/creds/#{ExBao.Operation.escape(role)}",
      opts,
      body: [:ip, :username]
    )
  end

  @doc ~S"""
  Fetch a single issuer.

  `GET /v1/ssh/issuer/{issuer_ref}/public_key` — needs no token

  ## Arguments

    * `issuer_ref` — Reference to a existing issuer; either "default" for the configured default issuer, an identifier or the name assigned to the issuer.

  ## Options

    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-get-issuer"
  @spec get_issuer(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def get_issuer(server, issuer_ref, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "ssh")}/issuer/#{ExBao.Operation.escape(issuer_ref)}/public_key",
      opts,
      []
    )
  end

  @doc ~S"""
  Request a certificate using a certain role with the provided details.

  `POST /v1/ssh/issue/{role}`

  ## Arguments

    * `role` — The desired role with configuration for this request.

  ## Options

    * `:cert_type` (string) — Type of certificate to be created; either "user" or "host". Defaults to `"user"`.
    * `:critical_options` (map) — Critical options that the certificate should be signed for.
    * `:extensions` (map) — Extensions that the certificate should be signed for.
    * `:key_bits` (integer) — Specifies the number of bits to use for the generated keys. Defaults to `0`.
    * `:key_id` (string) — Key id that the created certificate should have. If not specified, the display name of the token will be used.
    * `:key_type` (string) — Specifies the desired key type; must be `rsa`, `ed25519` or `ec` Defaults to `"rsa"`.
    * `:ttl` (seconds) — The requested Time To Live for the SSH certificate; sets the expiration date. If not specified the role default, backend default, or system default TTL is used, in that order. Cannot be later than the role max TTL.
    * `:valid_principals` (string) — Valid principals, either usernames or hostnames, that the certificate should be signed for.
    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-issue-certificate"
  @spec issue_certificate(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def issue_certificate(server, role, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "ssh")}/issue/#{ExBao.Operation.escape(role)}",
      opts,
      body: [
        :cert_type,
        :critical_options,
        :extensions,
        :key_bits,
        :key_id,
        :key_type,
        :ttl,
        :valid_principals
      ]
    )
  end

  @doc ~S"""
  Fetch a list of all issuers.

  `GET /v1/ssh/issuers`

  ## Options

    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-list-issuers"
  @spec list_issuers(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def list_issuers(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "#{ExBao.Operation.mount(opts, "ssh")}/issuers", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Manage the 'roles' that can be created with this backend.

  `GET /v1/ssh/roles`

  ## Options

    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-list-roles"
  @spec list_roles(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def list_roles(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "#{ExBao.Operation.mount(opts, "ssh")}/roles", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  List all the roles associated with the given IP address.

  `POST /v1/ssh/lookup`

  ## Options

    * `:ip` (string) — [Required] IP address of remote host
    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-list-roles-by-ip"
  @spec list_roles_by_ip(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def list_roles_by_ip(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "#{ExBao.Operation.mount(opts, "ssh")}/lookup", opts,
      body: [:ip]
    )
  end

  @doc ~S"""
  Configure the default SSH issuer used for signing and verification operations.

  `DELETE /v1/ssh/config/ca`

  ## Options

    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-purge-ca"
  @spec purge_ca(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def purge_ca(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "#{ExBao.Operation.mount(opts, "ssh")}/config/ca",
      opts,
      []
    )
  end

  @doc ~S"""
  Configure the default SSH issuer used for signing and verification operations.

  `GET /v1/ssh/config/ca`

  ## Options

    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-read-default-ca"
  @spec read_default_ca(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def read_default_ca(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "ssh")}/config/ca",
      opts,
      []
    )
  end

  @doc ~S"""
  Fetch a single issuer.

  `GET /v1/ssh/issuer/{issuer_ref}`

  ## Arguments

    * `issuer_ref` — Reference to a existing issuer; either "default" for the configured default issuer, an identifier or the name assigned to the issuer.

  ## Options

    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-read-issuer"
  @spec read_issuer(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_issuer(server, issuer_ref, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "ssh")}/issuer/#{ExBao.Operation.escape(issuer_ref)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Retrieve the 'default' issuer's public key.

  `GET /v1/ssh/public_key` — needs no token

  ## Options

    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-read-public-key"
  @spec read_public_key(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def read_public_key(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "ssh")}/public_key",
      opts,
      []
    )
  end

  @doc ~S"""
  Configure or read the default SSH certificate issuer.

  `GET /v1/ssh/config/issuers`

  ## Options

    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-read-read"
  @spec read_read(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def read_read(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "ssh")}/config/issuers",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage the 'roles' that can be created with this backend.

  `GET /v1/ssh/roles/{role}`

  ## Arguments

    * `role` — [Required for all types] Name of the role being created.

  ## Options

    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-read-role"
  @spec read_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_role(server, role, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "ssh")}/roles/#{ExBao.Operation.escape(role)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Assign zero address as default CIDR block for select roles.

  `GET /v1/ssh/config/zeroaddress`

  ## Options

    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-read-zero-address-configuration"
  @spec read_zero_address_configuration(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def read_zero_address_configuration(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "ssh")}/config/zeroaddress",
      opts,
      []
    )
  end

  @doc ~S"""
  Request signing an SSH key using a certain role with the provided details.

  `POST /v1/ssh/sign/{role}`

  ## Arguments

    * `role` — The desired role with configuration for this request.

  ## Options

    * `:cert_type` (string) — Type of certificate to be created; either "user" or "host". Defaults to `"user"`.
    * `:critical_options` (map) — Critical options that the certificate should be signed for.
    * `:extensions` (map) — Extensions that the certificate should be signed for.
    * `:key_id` (string) — Key id that the created certificate should have. If not specified, the display name of the token will be used.
    * `:public_key` (string) — SSH public key that should be signed.
    * `:ttl` (seconds) — The requested Time To Live for the SSH certificate; sets the expiration date. If not specified the role default, backend default, or system default TTL is used, in that order. Cannot be later than the role max TTL.
    * `:valid_principals` (string) — Valid principals, either usernames or hostnames, that the certificate should be signed for.
    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-sign-certificate"
  @spec sign_certificate(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def sign_certificate(server, role, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "ssh")}/sign/#{ExBao.Operation.escape(role)}",
      opts,
      body: [
        :cert_type,
        :critical_options,
        :extensions,
        :key_id,
        :public_key,
        :ttl,
        :valid_principals
      ]
    )
  end

  @doc ~S"""
  Submit a new issuer with an optional explicit name.

  `POST /v1/ssh/issuers/import`

  ## Options

    * `:generate_signing_key` (boolean) — Generate SSH key pair internally rather than use the private_key and public_key fields. Defaults to `true`.
    * `:issuer_name` (string) — Optional issuer name that can be used to identify the issuer.
    * `:key_bits` (integer) — Specifies the desired key bits when generating variable-length keys (such as when key_type="ssh-rsa") or which NIST P-curve to use when key_type="ec" (256, 384, or 521). Defaults to `0`.
    * `:key_type` (string) — Specifies the desired key type when generating; could be a OpenSSH key type identifier (ssh-rsa, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521, or ssh-ed25519) or an algorithm (rsa, ec, ed25519). Defaults to `"ssh-rsa"`.
    * `:private_key` (string) — Private half of the SSH key that will be used to sign certificates.
    * `:public_key` (string) — Public half of the SSH key that will be used to sign certificates.
    * `:set_default` (boolean) — If true, this issuer will be set as the default issuer for performing operations. Only one issuer can be the default issuer and, if there's one set, it will be overridden. Defaults to `false`.
    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-submit-issuer"
  @spec submit_issuer(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def submit_issuer(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "ssh")}/issuers/import",
      opts,
      body: [
        :generate_signing_key,
        :issuer_name,
        :key_bits,
        :key_type,
        :private_key,
        :public_key,
        :set_default
      ]
    )
  end

  @doc ~S"""
  Submit a new issuer with an optional explicit name.

  `POST /v1/ssh/issuers/import/{issuer_name}`

  ## Arguments

    * `issuer_name` — Optional issuer name that can be used to identify the issuer.

  ## Options

    * `:generate_signing_key` (boolean) — Generate SSH key pair internally rather than use the private_key and public_key fields. Defaults to `true`.
    * `:key_bits` (integer) — Specifies the desired key bits when generating variable-length keys (such as when key_type="ssh-rsa") or which NIST P-curve to use when key_type="ec" (256, 384, or 521). Defaults to `0`.
    * `:key_type` (string) — Specifies the desired key type when generating; could be a OpenSSH key type identifier (ssh-rsa, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521, or ssh-ed25519) or an algorithm (rsa, ec, ed25519). Defaults to `"ssh-rsa"`.
    * `:private_key` (string) — Private half of the SSH key that will be used to sign certificates.
    * `:public_key` (string) — Public half of the SSH key that will be used to sign certificates.
    * `:set_default` (boolean) — If true, this issuer will be set as the default issuer for performing operations. Only one issuer can be the default issuer and, if there's one set, it will be overridden. Defaults to `false`.
    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-submit-issuers-import-issuer_name"
  @spec submit_issuers_import_issuer_name(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def submit_issuers_import_issuer_name(server, issuer_name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "ssh")}/issuers/import/#{ExBao.Operation.escape(issuer_name)}",
      opts,
      body: [:generate_signing_key, :key_bits, :key_type, :private_key, :public_key, :set_default]
    )
  end

  @doc ~S"""
  This endpoint removes the stored host keys used for the removed Dynamic Key feature, if present.

  `DELETE /v1/ssh/tidy/dynamic-keys`

  ## Options

    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-tidy-dynamic-host-keys"
  @spec tidy_dynamic_host_keys(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def tidy_dynamic_host_keys(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "#{ExBao.Operation.mount(opts, "ssh")}/tidy/dynamic-keys",
      opts,
      []
    )
  end

  @doc ~S"""
  Fetch a single issuer.

  `POST /v1/ssh/issuer/{issuer_ref}`

  ## Arguments

    * `issuer_ref` — Reference to a existing issuer; either "default" for the configured default issuer, an identifier or the name assigned to the issuer.

  ## Options

    * `:issuer_name` (string) — Provide a name to the generated or existing issuer, the name must be unique across all issuers and not be the reserved value 'default'
    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-update-issuer"
  @spec update_issuer(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def update_issuer(server, issuer_ref, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "ssh")}/issuer/#{ExBao.Operation.escape(issuer_ref)}",
      opts,
      body: [:issuer_name]
    )
  end

  @doc ~S"""
  Validate the OTP provided by OpenBao SSH Agent.

  `POST /v1/ssh/verify` — needs no token

  ## Options

    * `:otp` (string) — [Required] One-Time-Key that needs to be validated
    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-verify-otp"
  @spec verify_otp(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def verify_otp(server, opts \\ []) do
    ExBao.Operation.call(server, :post, "#{ExBao.Operation.mount(opts, "ssh")}/verify", opts,
      body: [:otp]
    )
  end

  @doc ~S"""
  Configure or read the default SSH certificate issuer.

  `POST /v1/ssh/config/issuers`

  ## Options

    * `:default` (string) — Reference (name or identifier) to issuer to be used as the default.
    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-write-issuer-config"
  @spec write_issuer_config(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def write_issuer_config(server, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "ssh")}/config/issuers",
      opts,
      body: [:default]
    )
  end

  @doc ~S"""
  Manage the 'roles' that can be created with this backend.

  `POST /v1/ssh/roles/{role}`

  ## Arguments

    * `role` — [Required for all types] Name of the role being created.

  ## Options

    * `:algorithm_signer` (string) — [Not applicable for OTP type] [Optional for CA type] When supplied, this value specifies a signing algorithm for the key. Possible values: ssh-rsa, rsa-sha2-256, rsa-sha2-512, default, or the empty string.
    * `:allow_bare_domains` (boolean) — [Not applicable for OTP type] [Optional for CA type] If set, host certificates that are requested are allowed to use the base domains listed in "allowed_domains", e.g. "example.com". This is a separate option as in some cases this can be considered a security threat.
    * `:allow_commas_in_identity_templates` (boolean) — If true and templating is enabled, the values substituted in for allowed_users and allowed_domains template expressions might contain a comma (','). As these values are comma separated lists, this can enable injection attacks. Only use this, if the data used by the templates is trusted. Defaults to `false`.
    * `:allow_empty_principals` (boolean) — [Optional for CA type] If true, host and user certificates can be issued without any valid principals. For host certificates, this means that any domain a host claims to be will be trusted by the connecting client. For user certificates, when a CA certificate is placed in a user's AuthorizedKeys file, any principal on that certificate will be allowed to connect. When allowed_users or allowed_domains is set to * (corresponding to the role/certificate type), allow_empty_principals=false still permits issuance. It is recommend to leave this disabled.
    * `:allow_host_certificates` (boolean) — [Not applicable for OTP type] [Optional for CA type] If set, certificates are allowed to be signed for use as a 'host'. Defaults to `false`.
    * `:allow_subdomains` (boolean) — [Not applicable for OTP type] [Optional for CA type] If set, host certificates that are requested are allowed to use subdomains of those listed in "allowed_domains".
    * `:allow_user_certificates` (boolean) — [Not applicable for OTP type] [Optional for CA type] If set, certificates are allowed to be signed for use as a 'user'. Defaults to `false`.
    * `:allow_user_key_ids` (boolean) — [Not applicable for OTP type] [Optional for CA type] If true, users can override the key ID for a signed certificate with the "key_id" field. When false, the key ID will always be the token display name. The key ID is logged by the SSH server and can be useful for auditing.
    * `:allowed_critical_options` (string) — [Not applicable for OTP type] [Optional for CA type] A comma-separated list of critical options that certificates can have when signed. To allow any critical options, set this to an empty string.
    * `:allowed_domains` (string) — [Not applicable for OTP type] [Optional for CA type] If this option is not specified, client can request for a signed certificate for any valid host. If only certain domains are allowed, then this list enforces it.
    * `:allowed_domains_template` (boolean) — [Not applicable for OTP type] [Optional for CA type] If set, Allowed domains can be specified using identity template policies. Non-templated domains are also permitted. Defaults to `false`.
    * `:allowed_extensions` (string) — [Not applicable for OTP type] [Optional for CA type] A comma-separated list of extensions that certificates can have when signed. An empty list means that no extension overrides are allowed by an end-user; explicitly specify '*' to allow any extensions to be set.
    * `:allowed_user_key_lengths` (map) — [Not applicable for OTP type] [Optional for CA type] If set, allows the enforcement of key types and minimum key sizes to be signed.
    * `:allowed_users` (string) — [Optional for all types] [Works differently for CA type] If this option is not specified, or is '*', client can request a credential for any valid user at the remote host, including the admin user. If only certain usernames are to be allowed, then this list enforces it. If this field is set, then credentials can only be created for default_user and usernames present in this list. Setting this option will enable all the users with access to this role to fetch credentials for all other usernames in this list. Use with caution. N.B.: with the CA type, an empty list means that no users are allowed; explicitly specify '*' to allow any user.
    * `:allowed_users_template` (boolean) — [Not applicable for OTP type] [Optional for CA type] If set, Allowed users can be specified using identity template policies. Non-templated users are also permitted. Defaults to `false`.
    * `:cidr_list` (string) — [Optional for OTP type] [Not applicable for CA type] Comma separated list of CIDR blocks for which the role is applicable for. CIDR blocks can belong to more than one role.
    * `:default_critical_options` (map) — [Not applicable for OTP type] [Optional for CA type] Critical options certificates should have if none are provided when signing. This field takes in key value pairs in JSON format. Note that these are not restricted by "allowed_critical_options". Defaults to none.
    * `:default_extensions` (map) — [Not applicable for OTP type] [Optional for CA type] Extensions certificates should have if none are provided when signing. This field takes in key value pairs in JSON format. Note that these are not restricted by "allowed_extensions". Defaults to none.
    * `:default_extensions_template` (boolean) — [Not applicable for OTP type] [Optional for CA type] If set, Default extension values can be specified using identity template policies. Non-templated extension values are also permitted. Defaults to `false`.
    * `:default_user` (string) — [Required for OTP type] [Optional for CA type] Default username for which a credential will be generated. When the endpoint 'creds/' is used without a username, this value will be used as default username.
    * `:default_user_template` (boolean) — [Not applicable for OTP type] [Optional for CA type] If set, Default user can be specified using identity template policies. Non-templated users are also permitted. Defaults to `false`.
    * `:exclude_cidr_list` (string) — [Optional for OTP type] [Not applicable for CA type] Comma separated list of CIDR blocks. IP addresses belonging to these blocks are not accepted by the role. This is particularly useful when big CIDR blocks are being used by the role and certain parts of it needs to be kept out.
    * `:issuer_ref` (string) — Reference to the issuer used to sign requests serviced by this role.
    * `:key_id_format` (string) — [Not applicable for OTP type] [Optional for CA type] When supplied, this value specifies a custom format for the key id of a signed certificate. The following variables are available for use: '{{token_display_name}}' - The display name of the token used to make the request. '{{role_name}}' - The name of the role signing the request. '{{public_key_hash}}' - A SHA256 checksum of the public key that is being signed.
    * `:key_type` (string) — [Required for all types] Type of key used to login to hosts. It can be either 'otp' or 'ca'. 'otp' type requires agent to be installed in remote hosts.
    * `:max_ttl` (seconds) — [Not applicable for OTP type] [Optional for CA type] The maximum allowed lease duration
    * `:not_before_duration` (seconds) — [Not applicable for OTP type] [Optional for CA type] The duration that the SSH certificate should be backdated by at issuance. Defaults to `30`.
    * `:port` (integer) — [Optional for OTP type] [Not applicable for CA type] Port number for SSH connection. Default is '22'. Port number does not play any role in creation of OTP. For 'otp' type, this is just a way to inform client about the port number to use. Port number will be returned to client by OpenBao server along with OTP.
    * `:ttl` (seconds) — [Not applicable for OTP type] [Optional for CA type] The lease duration if no specific lease duration is requested. The lease duration controls the expiration of certificates issued by this backend. Defaults to the value of max_ttl.
    * `:mount` — where the engine is mounted, `"ssh"` by default.
  """
  @operation "ssh-write-role"
  @spec write_role(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def write_role(server, role, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "ssh")}/roles/#{ExBao.Operation.escape(role)}",
      opts,
      body: [
        :algorithm_signer,
        :allow_bare_domains,
        :allow_commas_in_identity_templates,
        :allow_empty_principals,
        :allow_host_certificates,
        :allow_subdomains,
        :allow_user_certificates,
        :allow_user_key_ids,
        :allowed_critical_options,
        :allowed_domains,
        :allowed_domains_template,
        :allowed_extensions,
        :allowed_user_key_lengths,
        :allowed_users,
        :allowed_users_template,
        :cidr_list,
        :default_critical_options,
        :default_extensions,
        :default_extensions_template,
        :default_user,
        :default_user_template,
        :exclude_cidr_list,
        :issuer_ref,
        :key_id_format,
        :key_type,
        :max_ttl,
        :not_before_duration,
        :port,
        :ttl
      ]
    )
  end

  # ── end of generated ──
end
