defmodule ExBao.TOTP do
  @moduledoc """
    The TOTP secrets engine.

    Generated from OpenBao's OpenAPI specification by `mix bao.gen`. One
    function per endpoint: path parameters are arguments, every other field
    is an option, and the answer is the server's own JSON body. An option
    the endpoint does not accept raises `ArgumentError` rather than being
    sent and ignored.
    
    Every function takes `:mount`, `"totp"` by default.
  """

  use ExBao.Operation

  # ── generated by `mix bao.gen` from OpenBao 2.6.2 ──
  # Everything down to the closing marker is rewritten on every run. To
  # curate a function, move it above this block and keep its `@operation`:
  # the next run sees it there and stops generating it.

  @doc ~S"""
  Manage the keys that can be created with this backend.

  `POST /v1/totp/keys/{name}`

  ## Arguments

    * `name` — Name of the key.

  ## Options

    * `:account_name` (string) — The name of the account associated with the key. Required if generate is true.
    * `:algorithm` (string) — The hashing algorithm used to generate the TOTP token. Options include SHA1, SHA256 and SHA512. Defaults to `"SHA1"`.
    * `:digits` (integer) — The number of digits in the generated TOTP token. This value can either be 6 or 8. Defaults to `6`.
    * `:exported` (boolean) — Determines if a QR code and url are returned upon generating a key. Only used if generate is true. Defaults to `true`.
    * `:generate` (boolean) — Determines if a key should be generated by OpenBao or if a key is being passed from another service. Defaults to `false`.
    * `:issuer` (string) — The name of the key's issuing organization. Required if generate is true.
    * `:key` (string) — The shared master key used to generate a TOTP token. Only used if generate is false.
    * `:key_size` (integer) — Determines the size in bytes of the generated key. Only used if generate is true. Defaults to `20`.
    * `:period` (seconds) — The duration used to generate a counter for the TOTP token calculation. Defaults to `30`.
    * `:qr_size` (integer) — The pixel size of the generated square QR code. Only used if generate is true and exported is true. If this value is 0, a QR code will not be returned. Defaults to `200`.
    * `:skew` (integer) — The number of delay periods that are allowed when validating a TOTP token. This value can either be 0 or 1. Only used if generate is true. Defaults to `1`.
    * `:url` (string) — A TOTP url string containing all of the parameters for key setup. Only used if generate is false.
    * `:mount` — where the engine is mounted, `"totp"` by default.
  """
  @operation "totp-create-key"
  @spec create_key(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def create_key(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "totp")}/keys/#{ExBao.Operation.escape(name)}",
      opts,
      body: [
        :account_name,
        :algorithm,
        :digits,
        :exported,
        :generate,
        :issuer,
        :key,
        :key_size,
        :period,
        :qr_size,
        :skew,
        :url
      ]
    )
  end

  @doc ~S"""
  Manage the keys that can be created with this backend.

  `DELETE /v1/totp/keys/{name}`

  ## Arguments

    * `name` — Name of the key.

  ## Options

    * `:mount` — where the engine is mounted, `"totp"` by default.
  """
  @operation "totp-delete-key"
  @spec delete_key(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def delete_key(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :delete,
      "#{ExBao.Operation.mount(opts, "totp")}/keys/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Request time-based one-time use password or validate a password for a certain key.

  `GET /v1/totp/code/{name}`

  ## Arguments

    * `name` — Name of the key.

  ## Options

    * `:mount` — where the engine is mounted, `"totp"` by default.
  """
  @operation "totp-generate-code"
  @spec generate_code(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def generate_code(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "totp")}/code/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Manage the keys that can be created with this backend.

  `GET /v1/totp/keys`

  ## Options

    * `:mount` — where the engine is mounted, `"totp"` by default.
  """
  @operation "totp-list-keys"
  @spec list_keys(ExBao.server(), keyword()) ::
          ExBao.Operation.result()
  def list_keys(server, opts \\ []) do
    ExBao.Operation.call(server, :get, "#{ExBao.Operation.mount(opts, "totp")}/keys", opts,
      fixed_query: %{"list" => "true"}
    )
  end

  @doc ~S"""
  Manage the keys that can be created with this backend.

  `GET /v1/totp/keys/{name}`

  ## Arguments

    * `name` — Name of the key.

  ## Options

    * `:mount` — where the engine is mounted, `"totp"` by default.
  """
  @operation "totp-read-key"
  @spec read_key(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def read_key(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :get,
      "#{ExBao.Operation.mount(opts, "totp")}/keys/#{ExBao.Operation.escape(name)}",
      opts,
      []
    )
  end

  @doc ~S"""
  Request time-based one-time use password or validate a password for a certain key.

  `POST /v1/totp/code/{name}`

  ## Arguments

    * `name` — Name of the key.

  ## Options

    * `:code` (string) — TOTP code to be validated.
    * `:expire_time` (int64) — Unix Epoch timestamp of the code expiry time.
    * `:generated` (int64) — Unix Epoch timestamp of the code generation.
    * `:period` (string) — TOTP configuration's period.
    * `:mount` — where the engine is mounted, `"totp"` by default.
  """
  @operation "totp-validate-code"
  @spec validate_code(ExBao.server(), String.t(), keyword()) ::
          ExBao.Operation.result()
  def validate_code(server, name, opts \\ []) do
    ExBao.Operation.call(
      server,
      :post,
      "#{ExBao.Operation.mount(opts, "totp")}/code/#{ExBao.Operation.escape(name)}",
      opts,
      body: [:code, :expire_time, :generated, :period]
    )
  end

  # ── end of generated ──
end
